### ISSUE TITLE
Add tensorBoard field to tf-job prototype

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/kubeflow#113]
Propose adding an optional param to https://github.com/google/kubeflow/blob/master/kubeflow/tf-job/prototypes/tf-job.jsonnet allowing user to provide tensorboard log dir which if provided is templated as follows
```yaml
  tensorBoard:
    logDir: import 'param://tensorboard_log_dir';
```

Propose naming optional param "tensorboard_log_dir", alternatively "tensorboard" or "log_dir"...

Unclear why but I've been observing even if tensorBoad logDir field is provided tboard does not launch unless a tfImage field is provided. One approach would be to also add a tfImage optional param and require it whenever tensorboard_log_dir is provided. Would probably be better to understand why this happens before updating the prototype.

**Comment by jlewi** [comment]
The TfJob controller needs an image which contains tensorboard in order to run tensorboard. That image is specified by TfImage which should be a standard TensorFlow image. The standard TensorFlow image contains common TensorFlow tools; tensorboard being one of them.

The TfImage can be configured per job but I also believe you can specify a default in the controller so that individual jobs don't have to specify one.

It would be fine to add an option to specify TfImage as well.

**Comment by jlewi** [comment]
This is obsolete because we are removing TensorBoard from TFJob. We will provide separate ksonnet configs to deploy TB separately.
