### ISSUE TITLE
TF serving supports request id

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1220]
The http proxy should support request id field.
This is useful when logging request/response, see https://github.com/kubeflow/kubeflow/issues/1000.

The field should be popped before sending to modelServer and thus have no effect.

**Comment by jlewi** [comment]
@lluunn If we use TFServing's HTTP proxy how do we record request id?

**Comment by lluunn** [comment]
I will figure out if istio can do it with its logging

**Comment by jlewi** [comment]
@lluunn Was the original issue referring to our custom HTTP proxy for TFServing and not the built in HTTP proxy for TFServing?

I assume switching to TFServing HTTP prox might change things because we might not be able to add a field to that proxy.

In light of that change and also the directional change to rely on ISTIO more. We might need to rethink how we do request/response logging.

it might be good to write up a doc  (or updating the previous) doc to outline various options such as using ISTIO.

**Comment by lluunn** [comment]
Originally referred to our http proxy.
I will investigate if we can do it with Istio, and if not what are the options.

**Comment by jlewi** [comment]
Duplicate of #1731 
We should just figure out what to do here as part of figuring out how to support request/response logging.
