### ISSUE TITLE
scripts/gke/deploy.sh fails when kubeflow_deployment_manager_configs/ exists

### ISSUE THREAD

**Issue by mmatiaschek** [kubeflow/kubeflow#1233]
KUBEFLOW_VERSION=0.2.2

scripts/gke/deploy.sh fails when kubeflow_deployment_manager_configs/ exists. Because of this no update of the cluster configuration is possible.

```
kubeflow exists
+ gcloud deployment-manager --project=child-growth-monitor deployments update kubeflow --config=cluster-kubeflow.yaml
ERROR: (gcloud.deployment-manager.deployments.update) Unable to read file 'cluster-kubeflow.yaml'. Unable to read file [cluster-kubeflow.yaml]: [Errno 2] No such file or directory: 'cluster-kubeflow.yaml'
```

**Comment by lluunn** [comment]
I remember I saw this once, but could not reproduce.

Did your deployment fail before with the same name?
Could you try a new deployment name?
`export DEPLOYMENT_NAME=new_name`

**Comment by lluunn** [comment]
#1206

**Comment by jlewi** [comment]
@mmatiaschek Are you trying to update an existing deployment? If you want to update an existing deployment did you try just issuing the gcloud command e.g.

```
gcloud deployment-manager --project=child-growth-monitor deployments update kubeflow --config=cluster-kubeflow.yaml
```
rather than rerunning deploy.sh

**Comment by jlewi** [comment]
The problem is here
https://github.com/kubeflow/kubeflow/blob/master/scripts/gke/deploy.sh#L103

We only CD into the directory containing the DM configs if the directory doesn't exist. Which is why cluster-kubeflow.yaml can be found when creating the deployment but not when the deployment exists.

Fix would be to just move that cd out of the if block.
