### ISSUE TITLE
Deploy knative for in cluster image builds

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#1317]
We need to support in cluster image building; e.g. to support firing off TFJobs for Jupyter #1240.

knative provides a build CRD
https://github.com/knative/build

We should include the build CRD as part of Kubeflow deployments so that we can start using it for in cluster builds

see also #289

**Comment by jlewi** [comment]
Downgrading to P2. Unless this is blocking #1240 I think its P2.

**Comment by walterhuangio** [comment]
Hi, I came across this issue. Including knative in deployment is by following the install guide of knative and include it into the deploy scripts and bootstrap automation of kubeflow. The build CRD will be available once knative is installed.

Would you consider this good for a first time contributor? If so, I can take a stab at it. Also, I assume that the stopping condition of this issue is by including knative in all possible variants of deployment of kubeflow. Is that correct?

**Comment by jlewi** [comment]
@walterhuangio We'd like a ksonnet package for installing knative artifacts. If knative provides YAML manifests for deploying it then I think we can just use ksonnet's native support for YAML.

See:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md

**Comment by walterhuangio** [comment]
@jlewi Thanks for the heads up. Yes Knative has YAML manifests for installation. There are different versions of yaml files for different deploy situations, minikube vs general k8s for example.

I'm starting to convert the yaml files to produce a new package. Sounds like you want knative to be a new package and not included in core right?

**Comment by jlewi** [comment]
@walterhuangio Yes a new package sounds great.

**Comment by jlewi** [comment]
@walterhuangio Any progress on this?

**Comment by chrisheecho** [comment]
/priority p2

based on jeremy's comments and number of issues we need to resolve on 0.4

**Comment by jbottum** [comment]
area/0.5.0

**Comment by jbottum** [comment]
remove-area 0.5.0

**Comment by chrisheecho** [comment]
/remove-priority p1
no eng resource
