### ISSUE TITLE
worker restart result in the TFJOB can not finish expectedly

### ISSUE THREAD

**Issue by langhuansanren** [kubeflow/kubeflow#147]
I can start the tfjob normally but sometimes ,it will get all kinds of error,for example the kubernetes nodes is in notready status(in fact,there are many exception can cause the worker restart),which result in workers restart,and the tfjob can not finish expectedly,so the resource can not recycle as usual,how to deal with this problem?

**Comment by jlewi** [comment]
Can you clarify what you think the desired behavior is?

If your cluster is unhealthy (e.g. nodes aren't ready) or its overloaded so TF keeps getting preempted, do you expect your job to fail?

Is your job resilient to interruptions? For example do you checkpoint progress? If you checkpoint progress then even if some of the workers are restarted, your job should be able to continue where it left off and make progress. So interruptions will make your job run slower but not prevent it from running.

**Comment by langhuansanren** [comment]
I expect that workers should not restart in some situation ,for example all workers go well in the beginning ,then after all workers have finished their tasks,one of workers restart before it is support to terminate for unknown reason,other workers has terminated,so the one worker can not terminate unless I kill the tfjob. which cause that GPUs are occupied forever.

So I want something could be done by programs to catch the  running exceptions of  tfjobs, and can kill it automatically

**Comment by gaocegege** [comment]
Hi, @langhuansanren 

I am not sure if I understand your comment. Do you mean that the TFJob is finished but there are some workers may be restarted accidentally?

**Comment by langhuansanren** [comment]
Hi, @gaocegege 
   Yes , sometimes some workers will not terminate or restart for unknown reason, and the tfjob would not go on running ,so it can not release the resources.

**Comment by gaocegege** [comment]
@langhuansanren 

Thanks for your reply. Now I think the PS created by the TFJob are running forever, and the workers may be restarted accidentally, so you want to delete these pods after the TFJob is finished to release the resources belong to the TFJob, right?

**Comment by langhuansanren** [comment]
@gaocegege 
 Yes , you got it,in conclusion,I am confused with two problems as follows:
1. How to know whether the tfjob has ended (now I determine if all the workers has terminated,will failed when the above exception happen )
2. if I can know whether  the tfjob has ended, how to delete the pod still running, in fact,  I do not really want to delete  tfjob because the normal worker's logs are usefull

**Comment by jlewi** [comment]
The TFJob controller determines when the job is done based on the TerminationPolicy. Right now the only policy we support is chief. Which means you can designate a single worker (or master) as the chief . Based on the exit code of the [chief](https://github.com/tensorflow/k8s#creating-a-job) we decide whether the job succeeded, had a permanent error or a retryable error.

So your code needs to signal to the job controller what you want to happen based on the exit code. 

The exit codes corresponding to were chosen to have intelligent behavior; e.g. a SIGTERM is treated as retryable since a SIGTERM can be an indication K8s preempted the job for some reason.

Feel free to make some suggestions about other termination policies you think we should support.

There's an open issue tensorflow/k8s#128 not to leave pods running after the job finishes.
