### ISSUE TITLE
How to deploy kubeflow by using offline computer

### ISSUE THREAD

**Issue by jokerwenxiao** [kubeflow/kubeflow#1522]
For some reason, my development environment has no network, so how do I deploy kubeflow?

**Comment by 372046933** [comment]
Currently, you have to initialize the `ks` project  online. After that, you can use `ks show` to generate `YAML` and then apply that on the offline machine.

**Comment by jokerwenxiao** [comment]
I have encountered some bottlenecks and I don't know what to do for this issue.
Can you write a detailed step?
Thank you！

**Comment by shalberd** [comment]
Furthermore, Web interface components like js, fonts etc get loaded from the Web instead of being in the containers. Not very good for regulated environments, hopefully people think of that for v0.6. IMO it#s just lazyness. I like Kubelflow a lot, but those points need to be considered. There are people out there wanting to run Kubeflow and the steps in the Web interfaces in their own datacenter.

**Comment by NickJasonLv** [comment]
> 
> 
> Currently, you have to initialize the `ks` project online. After that, you can use `ks show` to generate `YAML` and then apply that on the offline machine.

Can you write a detailed steps?
Thank you！

**Comment by NickJasonLv** [comment]
> 
> 
> Currently, you have to initialize the `ks` project online. After that, you can use `ks show` to generate `YAML` and then apply that on the offline machine.

@372046933 
Can you write a detailed steps?
Thank you！

**Comment by 3Xpl0it3r** [comment]
@NickJasonLv 1. cd ${KS_APP_PATH}/ks_app/  2 : ks show default  > kubeflow_offline.yaml 3. sed -i "s/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g" kubeflow_offline.yaml  4. kubectl apply -f kubeflow_offline.yaml

It works for me

@372046933 and 3x for your idea
