### ISSUE TITLE
On Premises deployment of Kubeflow fails unless ks flags are set v0.3

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#1615]
Please reference this [gist](https://gist.github.com/jtfogarty/511c2412466ec086f61046c6d554528f)

ksonnet is not picking up the http_proxy values or is expecting something other than what we have set.

Unless the changes detailed in the gist are made, the install process fails.  

```
 ks version
ksonnet version: 0.12.0
jsonnet version: v0.11.2
client-go version: kubernetes-1.10.4
```
Can the ks flags be added to the env.sh file and used in kfctl.sh / util.sh?

**Comment by jlewi** [comment]
@jtfogarty Thanks for creating this bug. Can you provide a little more explanation of what the issue is?

If I understand correctly based on our conversation in slack, in your on prem environment you have issues with ksonnet making external HTTP requests which are blocked in your on prem environment.

And you work around this by doing two things

  1. Setting `--api-spec=file:/home/kubeflow/swagger.json` so that it won't try to download the K8s API specs from an external site
  1. Setting ` --skip-default-registries` so that it won't try to download the default registries from GitHub?

Is that accurate?

**Comment by jtfogarty** [comment]
I'm able to do a wget on the swagger.json file from the Kubernetes master so the domain that hosts this file is open through our proxy.  I'm also able to do git clone from github form the master.  It seems to be an issue with how ksonnet uses the proxy.
After making the changes you listed, yes, the install completes successfully.

**Comment by jlewi** [comment]
I think we should make two changes.

1. We should add --skip-default-registries to the ks init command here

https://github.com/kubeflow/kubeflow/blob/master/scripts/util.sh#L49

2. We should define an extra environment variable ${KS_INIT_EXTRA_ARGS} to contain additional arguments to pass to the `ks init` command so that folks can specify additional arguments if needed.
