### ISSUE TITLE
Issues installing 0.3

### ISSUE THREAD

**Issue by matthen** [kubeflow/kubeflow#1871]
I followed the instructions at https://v0-3.kubeflow.org/docs/started/getting-started-gke/ - and found a few issues:

* `$KUBEFLOW_REPO` is used in commands, but not defined
* `$PROJECT` is not defined either
* If you follow the instructions you will get an error like:

`ERROR validating registry URL: registry path "...kubeflow/kubeflow" does not exist`

when running `${KUBEFLOW_REPO}/scripts/kfctl.sh generate k8s`

this is fixed by moving `$KUBEFLOW_SRC/kubeflow` to `$KUBEFLOW_REPO/kubeflow`. I guess that's an error you see when using `download.sh` rather than `git clone`

**Comment by connected-bsamadi** [comment]
You need to create a project on Google Cloud Platform and define the `PROJECT` variable yourself.
For `KUBEFLOW_REPO`, you can pick a name like kubeflow_repo. There is an issue with `KUBEFLOW_REPO` that you can fix by starting with a name and after running the download script, changing it to the full path. I have done it in the deploy_kubeflow.sh in here:
https://github.com/connected-bsamadi/kubeflow-tools

I am not sure how the commands in the official guide are executed.

**Comment by connected-bsamadi** [comment]
I tried using the full path before the download.sh. I think the error happens because by running download.sh, you end up one level upper in the folder structure.

**Comment by connected-bsamadi** [comment]
Here in `scripts/gke/util.sh`, the script expects `KUBEFLOW_REPO` to be the full path not a name:

```
generateDMConfigs() {
  # Create the DM configs if they don't exist.
  if [ ! -d "${KUBEFLOW_DM_DIR}" ]; then
    echo creating Deployment Manager configs in directory "${KUBEFLOW_DM_DIR}"
    mkdir -p "${KUBEFLOW_DM_DIR}"
    cp -r "${KUBEFLOW_REPO}"/deployment/gke/deployment_manager_configs/cluster* "${KUBEFLOW_DM_DIR}"
```

**Comment by jlewi** [comment]
I think this is a bug in the docs introduced by kubeflow/website#256.

The scripts auto-set KUBEFLOW_REPO based on location of kfctl.sh.
So when we changed the instructions to use KUBEFLOW_REPO rather than KUBEFLOW_SRC.

We ended up overwriting the default locale in the script. So that's probably why you have to set it and it has to be a full path.

**Comment by jlewi** [comment]
@davidstack should we roll back #256?

**Comment by matthen** [comment]
Thanks, I figured out how to do the installation, I'm just reporting issues with the guide.

**Comment by ashahba** [comment]
@jlewi and @matthen 
The changes to revert my bad commit for https://github.com/kubeflow/website/pull/256 and update the docs so that it's more clear around environment variables went in during: https://github.com/kubeflow/website/pull/277

So should we still keep this bug around or we can mark it as resolved?

**Comment by jlewi** [comment]
LGTM. I think we can close this.
