### ISSUE TITLE
Use ksonnet modules to better organize applications

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#1922]
ksonnet modules allow arbitrary groupings of components with specific parameters. Modules themselves may be nested. By declaring different environments that contain different modules as targets we would allow many applications to be defined. As an example

```
  # Create modules - groupings of components
  ks module create ui
  ks module create services
  ks module create notebooks
  # Generate components into above modules
  ks generate ambassador ambassador  --platform=${KUBEFLOW_PLATFORM} --module services
  ks generate centraldashboard centraldashboard --module ui
  ks generate metacontroller metacontroller --module notebooks
  ks generate profiles profiles --module notebooks
  ks generate notebooks notebooks --module notebooks
  # Create an environment to run notebooks
  ks env add notebooks --namespace=kubeflow
  ks env current --set notebooks
  ks env targets notebooks --module notebooks --module services --module ui
  ks apply notebooks
```

**Comment by ashahba** [comment]
Thanks @kkasravi for raising this.
It'll be nice to start with a base KF cluster and also be able manage dependencies for each component in a cleaner fashion.

As an end user I prefer being able to only deploy parts that I need rather than the whole stack with many components that I usually don't need.

**Comment by kkasravi** [comment]
closing this in lieu of #2022
