### ISSUE TITLE
Expose Istio's grafana dashboard

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#1969]
Similar to https://github.com/kubeflow/kubeflow/issues/644
But now for the Istio 1.0.

**Comment by lluunn** [comment]
It's done in #2051

**Comment by jamesthegiantpeach** [comment]
@lluunn I am having trouble finding the grafana.ini settings in this deployment. I ask because one should have to set the root_url and domain values in grafana.ini in order to use grafana from behind a reverse proxy or else you get the error pictured below. 
 
![image](https://user-images.githubusercontent.com/52935149/64136873-8e2d2080-cda9-11e9-85ab-b843d6caa013.png)

**Comment by lluunn** [comment]
Do you mind sending a PR to kubeflow/manifests repo to fix it?
Or could you show your overlay here?
I think there is some regression and the overwrite of root_url is gone. We should fix it and make it works by default.
