### ISSUE TITLE
kfctl / deploy-app: kubeflow components deployment composability API discussion 

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2024]
More and more use cases prefer only having components they want in their cluster instead of everything of kubeflow.
So it would be nice to have API / parameter / config file which defines what kfctl / deploy-app would deploy.

### The flexibility should not be per-component boolean control:
* there are lots of components, only some of them have self-explain names: not great user experience for beginner to go through all components names one by one and decide whether or not to select it.
* there are dependencies among components: ```katib -> operator; pipeline -> notebook, operator, argo; notebook -> operator; everything -> ambassador``` so likely a user-selected component combination would be partially broken.
* As we have more components on each release, user-facing API likely will keep changing.  

### Proposal of component control:
* offer major fields as ksonnet module: 
``
notebook 
ml-pipeline
hp-tuning
ml-operator
``
* user choose which ksonnet modules to install, kubeflow code take request, combine related ks components and apply to cluster.
* for example if user only want to run single jobs, only choose ```ml-operator``` field when make request.

### modules to components mapping:
![image](https://user-images.githubusercontent.com/37601826/49312096-eab88380-f497-11e8-806c-ec2583796658.png)

**Comment by kunmingg** [comment]
@jlewi @kkasravi

**Comment by kunmingg** [comment]
related: 
https://github.com/kubeflow/kubeflow/pull/2016
https://github.com/kubeflow/kubeflow/issues/2022

**Comment by kkasravi** [comment]
@kunmingg @jlewi @ashahba 

I like the concept of replacing ksonnet terminology with kubeflow's eg a 'service'. Your diagram captures a few kew features - like a 'service' can be nested. Not to bikeshed, but the term 'service' is awfully overloaded, what if we were to use a term like 'composite' or should we even stick with ksonnet's 'module'?

Would these services in the diagram be prebuilt so that they are available after bootstrap?
If we were to prebuild services which captured the current set of components (including #1996) we would have something that included:
- core
  - ambassador
  - centraldashboard
  - spartakus
- gcp
  - cert-manager
  - cloud-endpoints
  - google-cloud-filestore-pv
  - iap-ingress
  - metric-collector
  - prometheus
  - spartakus
- notebooks
  - jupyter
  - notebooks

**Comment by kkasravi** [comment]
### kubeflow cli/api requirements
1. services composition can be changed before and after the internal `ks apply <env>`
1. a subset of prototypes and other services can be selected when creating a given service
1. parameters can be specified for any prototype when creating the service or after the service is created

**Comment by kkasravi** [comment]
### kfctl `service` usage

```bash
kfctl service [-h|--help]
              create <name> [--apply] <component[/{prototype [--arg1=value --arg2=value]}]>+
              add <name> [--apply] <component[/{prototype [--arg1=value --arg2=value]}]>+
              set <name> [--apply] <component[/{prototype [--arg1=value --arg2=value]}]>+
```

### Use cases 

1. Create a core service that includes the prototypes core/{ambassador,centraldashboard,spartakus}
    **$** kfctl service create core 'core/{ambassador,centraldashboard,spartakus}'
    ```bash
    ks module create core
    ks pkg install kubeflow/core
    ks generate ambassador ambassador --module core
    ks generate centraldashboard centraldashboard --module core
    ks generate spartakus spartakus --module core
    ks env targets default --module core
    ```

1. Next, create a training service that includes the prototype tf-training/tf-job-operator 
    **$** kfctl service create tf-training tf-training/tf-job-operator
    ```bash
    ks module create training
    ks pkg install kubeflow/tf-training
    ks generate tf-job-operator tf-job-operator --module training
    ks env targets default --module core --module training
    ```

1. Next, create a notebooks service that includes the prototypes 'jupyter/{notebooks,jupyter}'
    **$** kfctl service create notebooks 'jupyter/{notebooks,jupyter}'
    ```bash
    ks module create notebooks
    ks pkg install kubeflow/jupyter
    ks generate jupyter jupyter --module notebooks
    ks generate notebooks notebooks --module notebooks
    ks env targets default --module core --module training --module notebooks
    ```

1. Deploy core, training and notebooks
    **$** kfctl apply
    ```bash
    ks apply default
    ```

1. Add a new service 'openvino' to the current services and deploy it right away
    **$** kfctl service create openvino --apply openvino
    ```bash
    ks module create openvino
    ks pkg install kubeflow/openvino
    ks generate openvino openvino --module openvino
    ks env targets default --module openvino
    ks apply default
    ks env targets default --module core --module training --module notebooks --module openvino
    ```

additional use cases will be added

**Comment by kkasravi** [comment]
@jlewi  - one possibility would be to add the `service` subcommand to kfctl.sh (I have this working in kfctl.sh) in which case it would be a 0.4.0 candidate - but only in kfctl.sh unless the UI could also do the equivalent @kunmingg

**Comment by jlewi** [comment]
> I like the concept of replacing ksonnet terminology with kubeflow's eg a 'service'. 

This seems like we start going down the road of defining our own application management solution.

Specifically, it looks like we are trying to solve the dependency problem; e.g. user wants to install app A and B both of which depend on C. So how do we let the user install both A and B and then automatically install C.

Resolving the transitive dependencies of packages seems like a non-trivial problem. Is this problem well suited to Kubeflow?

If we go down this road are we getting too far ahead of ksonnet, helm, and other generic solutions? Have we talked to anyone in sig-apps or ksonnet to see what they are thinking in terms of resolving this problem?

I saw this issue ksonnet/ksonnet#740 by @shomron; but there is no info.

Should we try to stick with ksonnet terminology and concepts as a way of anchoring ourselves and not getting to far ahead in terms of app management.

Based on our discussion last friday, I thought our initial goals were much more modest. Specifically I thought the goal was to allow a bunch of ksonnet app modifications (e.g. the ksonnet commands listed in Kam's [comment](https://github.com/kubeflow/kubeflow/issues/2024#issuecomment-443721635)) to be defined declaratively in a config so that one could effectively do the equivalent of

```
ks generate --config=/path/to/config.yaml
```

Where the config file would be something like: https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/gcp_prototype.yaml

The functionality to do this is largely already present inside our bootstrapper.

This wouldn't handle the dependency problem but it would make easier for people to share different combinations components & modules for different use cases. 

In terms of automatically resolving dependencies it seems like some blocking issues are

1. Figuring out how individual components specify their dependencies
1. Figuring out how and when dependencies get resolved

These seem like non-trivial problems that everyone building micro-service applications faces. 

One of the explicit goals of the [Application CRD](https://github.com/kubernetes-sigs/application) is 

> Provide an explicit mechanism for applications to declare dependencies on another application.

Although looking at the spec I don't see a dependency field.

Nonetheless, perhaps the actionable step for Kubeflow is to begin chunking up Kubeflow into well defined applications each with their own Application CRD; e.g. TFJob, PyTorch, Jupyter, Katib should each have their own Application CRD.

**Comment by jlewi** [comment]
To summarize, here's a possible list of concrete next steps

1. #1419 Replace kfctl.sh with a go binary
    * This unifies the CLI and service
1. Start using ksonnet modules to make it easier to manage groups of related components
1. Divide Kubeflow packages into Applications each with their own Application CRD
1. Investigate sig-apps plans for dependency management

**Comment by kunmingg** [comment]
Really like ksonnet module: updated previous text.
Can we have
```ks generate --config=/path/to/ks_module_list.yaml```?
Just list modules user want in config, so this config would be compatible with different kubeflow versions:
each module's scope defined in each kubeflow version.

**Comment by ashahba** [comment]
That's a great point @kunmingg 
Me and @kkasravi try to our best to keep it backwards compatible 🤞

**Comment by kkasravi** [comment]
I'll repost what I did [earlier](https://github.com/kubeflow/kubeflow/issues/2024#issuecomment-443721635) but with the kfctl command using a yaml, the contents of the yaml, and the ks commands.
The yaml will look like:
```yaml
apiVersion: apps.kubeflow.org/v1alpha1
kind: Application
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: application-sample
  name: kubeflow
spec:
  app:
    modules:
      name: notebooks
      components:
        - name: jupyter
          prototype: jupyter
        - name: notebooks
          prototype: notebooks
        - name: ambassador
          prototype: ambassador
        - name: centraldashboard
          prototype: centraldashboard
        - name: spartakus
          prototype: spartakus
      parameters:
        - component: ambassador
          name: ambassadorServiceType
          value: LoadBalancer
      packages:
        - name: core
        - registry: kubeflow
      registries:
        - name: kubeflow
```

which would have the following golqng definition
```yaml
type AppConfig struct {
	Env        string           `json:"env,omitempty"`
	Registries []RegistryConfig `json:"registries,omitempty"`
	Packages   []KsPackage      `json:"packages,omitempty"`
	Modules    []KsModule       `json:"modules,omitempty"`
	Parameters []KsParameter    `json:"parameters,omitempty"`
}

type KsModule struct {
	Name       string         `json:"name"`
	Components []*KsComponent `json:"components,omitempty"`
	Module     []*KsModule    `json:"module,omitempty"`
}
```

**Comment by kkasravi** [comment]
My suggestion based on @jlewi's [comment](). 

Close this discussion and proceed with the separate tasks below:

- [ ] kfctl-golang #1419 
- [ ] ksonnet module migration #2022 
- [ ] application metadata descriptor work #1856

We can coordinate in slack.

**Comment by jlewi** [comment]
@kkasravi LGTM to your plan. Thanks for creating all the issues.

I might suggest leaving this issue open for now just so we have a place for ongoing discussion about composability.

There's some connection here to the previous issue #1691 about the apps marketplace. If Kubeflow is a bunch of applications then in principle all of them can just be published in the container marketplace and people could just select which apps to install.

Right now kfctl is doing a lot more stuff in terms of bootstrapping the cluster and other stuff so there's a gap between what we could deliver with the marketplace today and what kfctl can deliver. But maybe that will go away over time.

**Comment by kunmingg** [comment]
@kkasravi 
Seems like ks module is more of a components instance than components prototype.
How can we make ks module reusable for all users that might have various parameter sets?

**Comment by kkasravi** [comment]
yes it could be thought of as a components instance.

given a package like kubeflow/core, we should treat this as a module not a component with the same name as the package. 

For user 'fred' - who submits a kubeflow application to bootstrapper called resnet, wouldn't this be persisted to a unique path under /opt/kubeflow/default? 

Maybe you're asking how a set of parameters could be shared across kubeflow applications?

**Comment by kkasravi** [comment]
@kunmingg 

We should use the output of `ks registry describe kubelow` 
as a list of available modules (not created modules). I'll see if I can add 
this entrypoint in the next day or so.

**Comment by jlewi** [comment]
@kkasravi What is bootstrapper? Are you creating some server that runs in cluster and is responsible for deploying things?  

> For user 'fred' - who submits a kubeflow application to bootstrapper called resnet, wouldn't this be persisted to a unique path under /opt/kubeflow/default?

Why are we submitting applications to bootstrapper?

In my mind there is no such thing as bootstrapper.  All we have is
https://github.com/kubeflow/kubeflow/tree/master/bootstrap

The name "bootstrap" is a legacy; it should be renamed kfctl because it is the go implementation of kfctl.

**Comment by jlewi** [comment]
Per @kkasravi  closing this issue

I opened #2233 to figure out how we want to use Application CRs.

We also have #1472 for documenting maturity of different components.
