### ISSUE TITLE
New Jupyter spawner Ui doesn't allow entering a custom image

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2060]
With the new spawner UI, it doesn't look like we can enter a custom docker image. We can only select prebuilt images.

@ioandr @vkoukis is this a quick fix we can complete before 0.4?

**Comment by ioandr** [comment]
The decision to use HTML `<select>` element for the Docker Image option was made to **always** show the **full list** of available Docker images. This was not the case in the old Jupyter UI, as users reported in Slack, since the autocomplete feature of HTML `<input>` + `<datalist>` combination that was previously used prevented some Image options from showing.

However, we believe it is crucial to allow users to specify custom Docker Images. We consider the following options:
- rollback to the HTML `<input>` + `<datalist>` combination that was used in the previous Jupyter UI
- add a radio button to choose between 'standard' and 'custom' Docker Image. If 'standard' is chosen, the  form will show the existing HTML `<select>` dropdown list. If 'custom' is chosen, the form will show an HTML `<input>` field where the user can provide the name/endpoint of the desired Docker image.

We lean towards the second option, as it is more flexible and provides a better user experience.

As a workaround for now, custom images can be specified in the `jupyter/ui/default/config.yaml` configuration file by adding an extra entry under the image options YAML key. For the change to take effect, the Jupyter component needs to be re-deployed using the ksonnet cli.

If there are no objections on the proposed solution, we will come back with a PR to fix this issue.

**Comment by ioandr** [comment]
@jlewi we have already started the implementation of  option 2, as described above. We will open a PR that should be ready for review very soon.

**Comment by jlewi** [comment]
@ioandr SGTM thanks
