### ISSUE TITLE
[Click-to-Deploy App] Support more deployment customization

### ISSUE THREAD

**Issue by IronPan** [kubeflow/kubeflow#2124]
Currently the click to deploy app only expose the GKE zone and Kubeflow version as the configurations. This is good for quick tryout, but it is too limited for production use cases. 

Some of specific cluster configurations, such as private cluster, GPU/TPU supports, are very common customizations. Ideally we should support advanced configuration section to allow most or all configurations supported in [cluster-kubeflow.yaml](https://github.com/kubeflow/kubeflow/blob/master/deployment/gke/deployment_manager_configs/cluster-kubeflow.yaml)

**Comment by jlewi** [comment]
So is the feature request just to make GPU and TPU options in the UI?

**Comment by IronPan** [comment]
The GPU and TPU are just some examples. Other examples include private cluster, GPU type, GPU node #. 

For Pipeline, it need to be able to configure whether to create a database, or using an existing one.

**Comment by jlewi** [comment]
Repasting my comment from my offline discussion

Why do you think adding configuration options to the UI would simplify the experience?

We have evidence that adding options to the UI creates a more complicated experience.

The consistent feedback we've gotten from users is that creating an OAuth client for IAP is too complicated. That is an entirely UI based experience, we even have screen shots here
https://www.kubeflow.org/docs/started/getting-started-gke/.

But still users are consistently tripped up trying to go through those steps. Which is why our goal is to try to reduce the number of options. The click to deploy app has a specific CUJ in mind

One click and then go to notebook; http://bit.ly/cuj_train_deploy_notebook

By one click we literally mean we want to count the number of clicks and minimize them. One click is not a synonym for UI based deployment.

I think if you start adding multiple fields and multiple steps the clicks accumulate fast and the process becomes very difficult and it becomes even more frustrating if you have to go through it multiple times.

The approach we are taking with the click to deploy app is to try to "auto" optimize the config.

For example, with GPUs we'd like to take advantage of cluster autoscaling and node provisioning to automatically provision GPUs. We'd like to do this conditionally based on whether there zone has GPU quotas or not.

If the users want to customize things beyond that, the general thinking is to give them access to the configs (deployment manager, K8s, ksonnet, etc...).

So the thinking is that we should be very selective in the options exposed via the web app.

**Comment by jlewi** [comment]
Reposting some offline discussion

From @IronPan 
> The specific pain point for CLI is slow iteration on "trial and error". The deployment name collision is a important factor of it. The ${KFAPP} env var is set and used as the ks artifact directory name. To avoid deployment name collision, use would start over with the very first command kfctl.sh init. A typical trial would take ~20 minutes. And it can easily accumulated to hours. In a session with the user, specifically, went through about 4~5 times and takes ~2hs, including identifying the problem and retry. 

Here's how this should work.
A user should do
kfctl init
kfctl generate
<make any changes they need>
kfctl apply

Now if they need to make changes the process would generally be
edit config files
kfctl apply

This will issue updates. For example users can follow this approach to 
1. Add Cloud NFS file store and mount it in JupyterHub
2. Change pipelines storage system
3. Add Node Pools to their cluster

The main limitation here is that some GCP properties can't be updated (e.g. certain cluster settings) so you need to do delete and then reapply to recreate.

In principle you should be able to just change the name of the deployment to allow creating a new deployment without having to delete the existing deployment. I expect if you just changed the name here it would work. If not this is something we can fix; please give it a try and open an issue if it doesn't or report back here.

We have a limitation right now in that we are using sed to modify the DM templates so we can only do substitution once (we depend on known values that get obliterated). This was a limitation of using shell scripts and not wanting to take on additional dependencies (e.g. yq) that make YAML manipulation easy. 

We are in the process of switching to a go based implementation which will make this type of resubstitution easy(#1419)

**Comment by IronPan** [comment]
Thanks Jeremy. 
> In principle you should be able to just change the name of the deployment to allow creating a new deployment without having to delete the existing deployment. I expect if you just changed the name here it would work. If not this is something we can fix; please give it a try and open an issue if it doesn't or report back here.

I gave a try by 
1. follow the CLI instruction and create a deployment
2. Update the DEPLOYMENT_NAME in env.sh to **foobar**
3. Redo the CLI deployment

I expect a new set of foobar-user/foobar-admin/foobar-vm GCP service account to create but they doesn't. This causes permission issues when I run stuff inside the cluster. 
Could you or someone take a look?
cc @kunmingg

**Comment by IronPan** [comment]
One thing I didn't do is 
`rm -rf gcp_config` 
before running 
`${KUBEFLOW_SRC}/scripts/kfctl.sh generate platform`
again. I suspect it cache the previous config and thus doesn't create a new one.
