### ISSUE TITLE
`ks apply cloud -c newjob` silently fails

### ISSUE THREAD

**Issue by s1113950** [kubeflow/kubeflow#217]
I had accidentally forgotten to change my `params.libsonnet` file after generating my job, which means I had a bunch of `null` values, including for the `image`.

When I ran the `ks apply` command, nothing happened. There was no failure, but there were also no jobs. 

Steps to reproduce:

```
ks generate tf-job newjob --name=newjob
ks apply cloud -c newjob
```
output will display that it is creating your jobs, but nothing will happen

**Comment by jlewi** [comment]
We could add some validation to the templates. jsonnet allows errors to be raised.

**Comment by aronchick** [comment]
These kind of validations are crucial - lack of validation and/or lack of
clear errors hurt the K8s community for years.

**Comment by jlewi** [comment]
I think the problem here is that TFJob controller is not properly validating the job spec and reporting errors; e.g. that image isn't set for a replica.

@gaocegege @ScorpioCPH  Any thoughts on how we should handle this? Would specifying a swagger spec for TFJob and relying on K8s to validate the spec solve this particular problem?

See also kubeflow/tf-operator#561

**Comment by jlewi** [comment]
Closing this issue since we have separate issues in tf-operator that have been fixed.
