### ISSUE TITLE
How should profiles support cloud credentials?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2192]
Context: http://bit.ly/kubeflow_cuj_multi_user
Doc:  http://bit.ly/kf_jupyter_design_doc

We would like to support multi-user Kubeflow where each team/user gets their own isolated namespace in which to use Kubeflow.

One design question we need to figure out is how to give pods cloud credentials (e.g. to access GCP/Azure/AWS) resources.

Currently when we deploy Kubeflow we create service accounts and store credentials for those service accounts in the Kubeflow namespace.

The new namespace created by the Profiles controller for each user/team won't have access to those secrets. So how would users get a credential to access cloud services?

Here are some options

1. Profiles controller could copy the secrets into each namespace
1. Profiles controller could create new service accounts, set IAM permission, and then store them in the namespace
1. Users could create and upload credentials as K8s secrets to their namespace

The first option goes against the idea of isolating users/teams in namespaces. We don't want each user/team to have the same set of privileges.

Option two might be convenient for user but

   * It requires profiles controller to have elevated privileges in order to be able to mint new accounts
   * How does profile controller know which service account and permissions to grant for each user/team

Option 3 seems like the most workable in the near term. We can think about providing utilities to make this easy.

   * For example, in GCP it would be convenient to have a script or UI to facilitate turning SA credentials into K8s secrets.

/cc @kkasravi

**Comment by kkasravi** [comment]
The profiles controller does operate with elevated permissions in order to create a namespace and a Permission CR in the namespace. The permissions controller then uses the Permissions CR to create a Role/Rolebinding for the user specified in the Profile CR. The user specified in the Profile CR can either be a ServiceAccount or a User. So the profiles controller is mostly doing 2 but could be expanded to include group info and more specific information in the Permissions CR that can be used to create Role/RoleBindings for group members for that namespace.
