### ISSUE TITLE
ImagePullBackOff while i pulled the images in advance

### ISSUE THREAD

**Issue by zoux86** [kubeflow/kubeflow#2196]
- k8s Environment:  
-        4 ubuntu 16.04 machines: 1  master and 3 node
-        version: 1.87
- 
- ksonnet version: 0.13.1
-        
- kubeflow version: v0.3.2

### Question: 
i want to use kubeflow in my local k8s cluster. The above is my environment. but due to GFW in china. i cannot pull the google images. so i use the proxy(ss+polipo), and Then i can pull google images in shell.
like this:
![image](https://user-images.githubusercontent.com/14087435/50579105-dc85ca80-0e7c-11e9-8ac9-add15a61476e.png)

and the i followed  Kubeflow quick start in https://www.kubeflow.org/docs/started/getting-started/

here is the result
![image](https://user-images.githubusercontent.com/14087435/50579338-15bf3a00-0e7f-11e9-9d25-a1e1ad28ab0c.png)

![image](https://user-images.githubusercontent.com/14087435/50579343-2374bf80-0e7f-11e9-9e6e-39afc7a50e04.png)

after kubectl describe the pod, the result is :  
root@kubernet-1:~# kubectl describe pod  centraldashboard-fd4f5c56c-w6mhm -n kubeflow
Name:           centraldashboard-fd4f5c56c-w6mhm
Namespace:      kubeflow
Node:           kubernet-3/192.168.14.54
Start Time:     Mon, 31 Dec 2018 09:59:09 +0000
Labels:         app=centraldashboard
                pod-template-hash=980917127
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kubeflow","name":"centraldashboard-fd4f5c56c","uid":"be732e2e-0ce2-11e9-bb4f-fa16...
Status:         Pending
IP:             10.244.2.3
Created By:     ReplicaSet/centraldashboard-fd4f5c56c
Controlled By:  ReplicaSet/centraldashboard-fd4f5c56c
Containers:
  centraldashboard:
    Container ID:   
    Image:          gcr.io/kubeflow-images-public/centraldashboard:v0.3.0
    Image ID:       
    Port:           8082/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from centraldashboard-token-xmtjt (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  centraldashboard-token-xmtjt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  centraldashboard-token-xmtjt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason      Age                  From                 Message
  ----     ------      ----                 ----                 -------
  Normal   BackOff     44m (x9753 over 1d)  kubelet, kubernet-3  Back-off pulling image "gcr.io/kubeflow-images-public/centraldashboard:v0.3.0"
  Warning  Failed      23m (x454 over 1d)   kubelet, kubernet-3  Failed to pull image "gcr.io/kubeflow-images-public/centraldashboard:v0.3.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  FailedSync  4m (x10373 over 1d)  kubelet, kubernet-3  Error syncing pod

### and then i use kfctl.sh to install kubeflow. But the result is the same. 
![image](https://user-images.githubusercontent.com/14087435/50579741-df83b980-0e82-11e9-8a56-cfbfe422086f.png)

### after kubectl describe the pod, the result is :  
Name:           centraldashboard-fd4f5c56c-gzlnh
Namespace:      kubeflow
Node:           zoux-3/192.168.14.81
Start Time:     Tue, 01 Jan 2019 16:13:26 +0000
Labels:         app=centraldashboard
                pod-template-hash=980917127
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kubeflow","name":"centraldashboard-fd4f5c56c","uid":"31c8785e-0de0-11e9-a0f4-fa16...
Status:         Pending
IP:             10.244.3.3
Created By:     ReplicaSet/centraldashboard-fd4f5c56c
Controlled By:  ReplicaSet/centraldashboard-fd4f5c56c
Containers:
  centraldashboard:
    Container ID:   
    Image:          gcr.io/kubeflow-images-public/centraldashboard:v0.3.0
    Image ID:       
    Port:           8082/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from centraldashboard-token-5bsnl (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  centraldashboard-token-5bsnl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  centraldashboard-token-5bsnl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason      Age                   From             Message
  ----     ------      ----                  ----             -------
  Warning  FailedSync  10m (x2535 over 10h)  kubelet, zoux-3  Error syncing pod
  Normal   BackOff     59s (x2461 over 10h)  kubelet, zoux-3  Back-off pulling image "gcr.io/kubeflow-images-public/centraldashboard:v0.3.0"
  

### **I have no idea how to solve these problems, can someone  help me and give me some advice. 
i would be very appreciated, thanks!!!**

**Comment by jlewi** [comment]
I'm not familiar with your proxy. This doesn't look like an issue with Kubeflow or kfctl.sh. Instead it looks like the issue is your proxy isn't working with Kubernetes as kubernetes is still trying to pull the images from gcr.io.

The current recommendation with China is to replicate the images to DockerHub or some other repo and then change the image parameters of the components to use those images.

This script might be useful to replicate images from gcr.io to DockerHub
https://github.com/kubeflow/kubeflow/tree/master/releasing/hubsync.

You'll need access to GCR though; e.g. through VPN or some other solution.

I thought we use to have a script to replace all the images but I can't find it. So you might have to do some work with sed.

@carmark @ddysher @cheyang Do you have any suggestion on the best way to deploy Kubeflow in China?

There's a long standing issue to do this as part of Kubeflow: kubeflow/kubeflow#211. This is an area where we'd love help if you are interested.

**Comment by zoux86** [comment]
@jlewi Thank you for your advice！i will try to change the image parameters of the components to use those images.  Is it right to modify this file??
[](https://github.com/kubeflow/kubeflow/blob/master/releasing/image_tags.yaml)

**Comment by dwang55** [comment]
I have the same problem when deploy kubeflow on local k82 cluster. Because of the GFW in china, I pull the all google images in advance. Then I use kfctl_k8s_istio.v1.0.2.yaml file to deploy kubeflow following the tutorial on website: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/. It makes me confused that although the yaml file does not specify the images' repo or tag, k8s will pull the specific docker images during installation.
Is theere any way to set the docker images manually?
