### ISSUE TITLE
Make arbitrary Jupyter images work with Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2208]
There's a lot of good jupyter images already out there.

For example #767 discusses a Jupyter image with swift support for TensorFlow.

We'd also like to support images with R.

As discussed in this [comment](https://github.com/kubeflow/kubeflow/issues/1643#issuecomment-425170924)

I think we want to

1. Document what requirements needed to be satisfied for an image to work with Kubeflow
1. Removing/reducing these requirements.

Ideally, any Jupyter runtime image should just work with Kubeflow. I think the only tweaks we've made are related to

1. filesystem permissions
1. support for backing /home/jovyan is backed by PV
1. requirements created by JupyterHub

I suspect backing /home/joyvan with a PV is the main compatibility issue with most arbitrary Jupyter images. I think we can work around this just by having an option by not mounting the PV at /home/jovyan but instead in a subdirectory. We already have an option at the ksonnet level that configures this for all jupyter instances; but we could potentially surface it in the spawner UI to allow it to be configured on a per instance database.

I think JupyterHub might impose some additional constraints; e.g. at a minimum I think JupyterHub needs to be installed in the Jupyter image itself and the version must match the JupyterHub version.

Its possible this requirement will go away in 0.5 if we remove JupyterHub.

**Comment by jlewi** [comment]
The Jupyter notebook CR is available in 0.4. It would be good to try that out with some arbitrary notebook images starting with the stock TensorFlow images which include jupyter.

**Comment by jlewi** [comment]
If someone wants to help out, a great way would be to try running a PyTorch notebook with our CR; see #1057

**Comment by DavidSpek** [comment]
As said in the last part of my comment https://github.com/kubeflow/community/issues/344#issuecomment-697370531, the only change that is needed to run the standard jupyter images is the `CMD` command. After some playing around the only the only variables necessary to still get a working notebook are:
`CMD ["sh","-c", "jupyter lab --NotebookApp.token='' --NotebookApp.base_url=${NB_PREFIX}"]`
I'm not sure what the removal of `--notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.password='' --NotebookApp.allow_origin='*'` will all influence, however, `port` for example is already the default and seems redundant to specify. If somebody with more knowledge than me could explain which variables are essential other than `jupyter lab --NotebookApp.token='' --NotebookApp.base_url=${NB_PREFIX}"` and why I would like to further look into making standard Jupyter images compatible with Kubeflow.

**Comment by DavidSpek** [comment]
@jlewi Currently the NB_PREFIX variable that is used for `--NotebookApp.base_url=${NB_PREFIX}` is set by the notebook controller.
https://github.com/kubeflow/kubeflow/blob/7f5e242f4671f453eaee72e4319a5f7f190f7725/components/notebook-controller/controllers/notebook_controller.go#L326

```
container.Env = append(container.Env, corev1.EnvVar{
		Name:  "NB_PREFIX",
		Value: "/notebook/" + instance.Namespace + "/" + instance.Name,
	})
```

Wouldn't it be possible to pass the arguments directly rather than changing the `CMD` and rebuilding the images?
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes

I'm not sure how to go about testing a custom version of the notebook controller, and seeing as I am not a programmer I'd be brute forcing it. If anybody can point me in the right direction to implementing and testing this it is much appreciated.

**Comment by thesuperzapper** [comment]
@DavidSpek Its `NB_PREFIX` is currently set as an environment variable?

What exactly would be the benefit of strongly tying our container images to a specific version of Jupyter (when things like `--NotebookApp.base_url=XXXX` may not be the same across Jupyter releases), this is also not to speak of RStudio/Theia.

However, @kimwnasptd and I were discussing whether we should do the prefix rewriting outside of Jupyter Itself (in another container running something like an apache web server), as this would pretty much mean we natively support any Web-IDE which can be put in a Docker container.

**Comment by DavidSpek** [comment]
@thesuperzapper Yeah I was thinking about that after I replied and started looking at RStudio and VS Code Server very briefly as well. There do seem to be some legacy environment variables for jupyter notebooks like  `$JPY_BASE_URL` but I'm not sure that is the best way to go being legacy and all. 

Doing the rewriting inside another container seems like a good solution. Is there some place I can read up on that discussion? Would this solution also be able to deal with the other command argument(s) needed, such as `--NotebookApp.token=''`? If multiple Web-IDE's are wanting to be supported, what logic would it use to determine what other command arguments need to be passed?

**Comment by kimwnasptd** [comment]
@thesuperzapper doesn't RSTudio have a way to configure its backend to expect requests under a prefix, like the `NotebookApp.base_url`?

**Comment by DavidSpek** [comment]
@kimwnasptd From what I can find it is configured in nginx or apache. https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy

**Comment by DavidSpek** [comment]
Also, this seems to be an existing Dockerfile for RStudio in Kubeflow.
https://github.com/StatCan/kubeflow-containers/tree/master/r-studio

**Comment by thesuperzapper** [comment]
@kimwnasptd RStudio does not have that feature.

In my images I am using an embedded `apache2` server in the Docker image to do the path rewriting based off the `NB_PREFIX` environment variable, but we could do something similar for ALL containers.

__run.sh__
```sh
# allow apache2 to use the NB_PREFIX provided by kubeflow
# note: we strip off any trailing / for consistency
shopt -s extglob;
echo "export NB_PREFIX_NO_SLASH=${NB_PREFIX%%+(/)}" >> /etc/apache2/envvars
```

__rstudio-proxy.conf__
```xml
<VirtualHost *:8888>

  RedirectMatch permanent ^${NB_PREFIX_NO_SLASH}$ ${NB_PREFIX_NO_SLASH}/

  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} =websocket
  RewriteRule ${NB_PREFIX_NO_SLASH}/(.*)     ws://localhost:8787/$1  [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket
  RewriteRule ${NB_PREFIX_NO_SLASH}/(.*)     http://localhost:8787/$1 [P,L]

  ProxyRequests Off
  ProxyPass ${NB_PREFIX_NO_SLASH}/ http://localhost:8787/
  ProxyPassReverse ${NB_PREFIX_NO_SLASH}/ http://localhost:8787/

  Redirect 404 /

</VirtualHost>
```

**Comment by DavidSpek** [comment]
@thesuperzapper I feel like the conversation is drifting a bit away from Jupyter images. But [this image](https://hub.docker.com/r/rocker/binder) seems to be running a jupyter notebook image on the standard port but adding `?urlpath=rstudio` to the url will get you to RStudio. Maybe it is possible to use this image as a base for RStudio or use a similar method to create the images

**Comment by DavidSpek** [comment]
@kimwnasptd @thesuperzapper RStudio v1.4.869-4 Preview for RStudio-Server has "New `X-RStudio-Root-Path` header or the new `www-root-path` for specifying the exact path prefixes added by a path-rewriting proxy (Pro #1410)."

https://rstudio.com/products/rstudio/download/preview-release-notes/

**Comment by supertetelman** [comment]
This issue was cross-posted in a issue I opened a while ago (https://github.com/kubeflow/kubeflow/issues/3838). Back in an older version of the jupyter-web-app my team had a custom solution where we just allowed users to directly modify the Docker CMD (see screenshot here: https://github.com/kubeflow/kubeflow/issues/3838#issuecomment-565576572).

This used the default container image if nothing was given or overrode it with whatever the user wanted. We found this great for allowing users to use any containers with a WebApp installed,  whether it was originally designed for Kubeflow or not.

My team and the people I work with make heavy use of Docker containers from http://ngc.nvidia.com/. These all have Jupyter installed (or matlab/R), but none of them start it by default. They open up to a shell to make running quick code "easier" for developers. Anytime we are using these containers in Kubeflow we need to create a 2-line Dockerfile overwriting the command, build it, and push it somewhere (which is a problem for people without access to a private registry).

Having something similar as an "advanced" configuration (introduced in https://github.com/kubeflow/kubeflow/pull/5332) seems like it could be a decent workflow to enable this behavior without impacting current workflows.
