### ISSUE TITLE
Miniconda version is pretty old and different versions of tini are used within Jupyter Dockerfiles

### ISSUE THREAD

**Issue by ashahba** [kubeflow/kubeflow#2374]
Currently we use `Miniconda v4.4.10` which is nearly a year old and `tini` versions are both `0.10.0` or `0.17.0`.
We should update `Miniconda` to the latest version and also ensure `tini` is upgraded to latest version everywhere to get the latest and greatest fixes.

**Comment by ashahba** [comment]
Looks like `Miniconda` versions newer that `4.5.4` have `Python 3.7` as default however `TensorFlow` doesn't support `3.7` yet 🤔

**Comment by jlewi** [comment]
@ashahba Do you mean in our Jupyter images? What is the priority of this issue?

We have related issues #2208 #2358 to see if we can use stock Jupyter images.  Would this indirectly solve the problem because we could stop building our own Jupyter images? For example we could just use the stock TensorFlow images?

**Comment by ashahba** [comment]
Oh in fact that sounds even better.
My idea about this was simple. Upgrade to latest but it turned out `TensorFlow` only support up to `Python 3.6` so any `Miniconda` images with `3.7` version is going to fail unless we add more custom code to make it work.
Let me review those tickets as well and get a better understanding before I commit to them 🙂

**Comment by ashahba** [comment]
However the notes about why that version of the `Miniconda` is the latest one we can use and also avoiding `pip install --upgrade pip` sets the priority to closer to `high` than `medium`.
