### ISSUE TITLE
Add a page on kubeflow.org referencing design docs on drive

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/kubeflow#2379]
To make the design docs more discoverable from the main web site, can we please add a page referencing the main docs with a brief description of them?

/assign @sarahmaddox 
/cc @vicaire @jlewi

**Comment by paveldournov** [comment]
The high level design overviews (which is what some of the docs are) are essentially in-depth concept guides for the users, who deploy/operate and extend the system, so I think it would be great to have them referenced as such from the documentation pages on the site. Linking from github is also a good idea, but in that case the user first needs to know what the repo is for.

**Comment by sarahmaddox** [comment]
Please would you link to the docs you mean? I've found these two, both publicly visible:

* [Kubeflow Pipeline Design Doc](https://docs.google.com/document/d/1O5n02SzMYmLH0cMkykxHWWWe7eMzaP1vk7Y3fBbLoD8/edit#) - this one seems useful as a conceptual guide to Pipelines. I'd recommend linking to it from the Pipelines section of the docs, rather than a generic page of design docs.
* [Kubeflow Jupyter Design Doc](https://docs.google.com/document/d/1VEAxANT9136nV___ZNnFfW7SnRP9yZePpy_rF43edgo/edit#) - this one seems less useful as a conceptual introduction, as it's more a discussion of implementation choices.

Happy to continue the discussion on a PR!

/unassign

**Comment by jlewi** [comment]
I tend to agree with @sarahmaddox that developer focused information is not really the target audience for the design docs. 

We've been putting most of our information targeting developers in GitHub e.g.

* In ROADMAP.md
* Developer Guide / Contribution Guide

> in-depth concept guides for the users, who deploy/operate and extend the system

@paveldournov If we think the design doc contains useful information for deploying/operating and extending the system should we pull this information out into suitable docs on the web page?
