### ISSUE TITLE
Add a "What kubeflow isn't" section to the README.

### ISSUE THREAD

**Issue by jayunit100** [kubeflow/kubeflow#2381]
Hi kubeflow.

## Question

I've been seeing a few  issues which might expand the boundaries of kubeflow (spark, airflow, persistence).  Which has made me ask the question: What are the boundaries for the project's scope?

## Suggestion 

I've been wondering wether there should be a section in the README about what kubeflow *is not*, i.e. what the boundaries are.  I'm of course in no position to define these boundaries, but just as a new community member whose been learning about it lately, and evaluating it for a few ideas, I'm not sure where it might fit into the broader technology roadmap for a tactically focused enterprise or startup.  

## Examples 

I think it might help drive adoption and help people decide wether or not kubeflow is the right tool for them.  I think these issues bring up some great ideas, so maybe the start would be to close/refocus them, and then alongside, craft the **what kubeflow isn't** section.

If kubeflow is really open to integration with any ML related project, and is really just an integration community for running these types of apps on kube,  then thats fine to, and I've just answered my own question :). 

- https://github.com/kubeflow/kubeflow/issues/382
- https://github.com/kubeflow/kubeflow/issues/155
- https://github.com/kubeflow/kubeflow/issues/191

## Context

I've suggested to the (increasingly smaller) Apache BigTop community which I used to be very active in, that we should possibly consider becoming leaner and contributing/partnering with kubeflow, as it seems to have lots of momentum and a bright future, and a good way to further evaluate this question is to determine what the boundaries, test plan, and use cases (current and future) are for the functionality of the overall project.

**Comment by jlewi** [comment]
That's a really good suggestion and a really tough question :)

If you look at our [ROADMAP](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md) we're increasingly taking a user focused approach writing CUJs focused on solving problems MLEngineers and Datascientists are facing.

So if we encounter a gap or problem in that CUJ that we can fix, should we not do so because it is outside our charter? If it makes sense to upstream it and contribute to some other communities kubernetes/flink/TensorFlow we should do that.

So as an example in regards to ETL (#382 and #1583 (Flink Runner)) building an ETL framework isn't our core charter. However, if you look at TFX which is solving a lot of ML related problems, it requires Beam to handle processing large amounts of data. So to use TFX you need a Beam runner like Flink. So  ideally the Flink community produces a Flink operator to make it super easy to run on K8s but if not I would consider that to be something we should consider investing in.

**Comment by skonto** [comment]
> I'm wondering if we could also make it more generic - to be able to launch spark jobs against any cluster and not just k8s.
The new Lyft operator is a good candidate: https://github.com/lyft/flinkk8soperator/issues
