### ISSUE TITLE
kfctl should try and apply all components rather than just the application component

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2391]
currently kfctl (both the bash and golang versions) call `ks apply -c metacontroller`, `ks apply -c application`. The application component fetches all other components and adds labels to each resource as part of it's apply. It would be preferred if we could do a `ks apply -c ` for each component but use the updated resource that the application component has processed.

**Comment by jlewi** [comment]
Summarizing some discussion from slack here:

Some discussion here:
https://kubeflow.slack.com/archives/CF94DURGF/p1548435495001500

In kfctl.sh
https://github.com/kubeflow/kubeflow/commit/c8f88366e88dda63a6fd9d499ce16d664c457dba#diff-8a6f2d237f052b07ca594c20830ed9d2

@kkasravi did some jsonnet magic involving generating the manifests for all components via the Application and then doing `kubectl apply -f dump.yaml`.

That was the best solution we could come up with to consistently add certain labels to all resources so that they could all be linked to the Application.

Hopefully with go we have more options and we can directly apply the individual resources.

**Comment by jlewi** [comment]
@kunmingg @gabrielwen is this fixed?

**Comment by kunmingg** [comment]
Fixed by https://github.com/kubeflow/kubeflow/pull/2801
