### ISSUE TITLE
notebook controller Add CRD validation

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#2417]
The first PR is merged #2336, things to improve:

- [x] e2e test (we have one test for the jsonnet-metacontroller one, we should make it run on this one)
- [x] status field should reflect the error if there is any. See #2269.
- [ ] ttlSecondsAfterFinished: This is in the original jsonnet controller spec, but not being used yet. I think we want to cleanup the notebook after idle for a period?
- [ ] CRD validation. 

Istio integration: #2172 , #2173

**Comment by jlewi** [comment]
Lets scope this issue to adding notebook CRD Validation.
We can use separate issues to track
  * Istio integration

I don't know what ttlSecondsAfterFinished was intended for; I'm not sure its relevant any more. We use statefulsets for jupyter and I don't see why we would need a TTL.

**Comment by jlewi** [comment]
/assign @zabbasi 

Looks like @zabbasi has some PRs pending to fix the CRD validation.

**Comment by lluunn** [comment]
The ttl was that we want to kill the idle notebook pod after some time; why statefulsets don't need to have ttl?

**Comment by zabbasi** [comment]
There is another issue which takes care of idle notebooks: https://github.com/kubeflow/kubeflow/issues/1394

**Comment by zabbasi** [comment]
> The ttl was that we want to kill the idle notebook pod after some time; why statefulsets don't need to have ttl?

There is another issue which takes care of idle notebooks: #1394

**Comment by jlewi** [comment]
@lluunn I was thinking the TTL was used not to GC idle pods but to garbage collect terminated resources.

With Argo workflows, TFJobs, batch jobs and other resources where the resources are run to completion we run into problems because we eventually accumulate so many resources that the API server can no longer efficiently list those resources and get requests hang.

So to address that the pattern is to add a ttlSecondsAfterFinished which GC's completed resources after the TTL expires.

WIth notebooks we don't have that problem. As @zabbasi says I think we can use #1394 to track culling of idle notebooks which is a more involved change.

**Comment by jlewi** [comment]
Fixed by #109.

**Comment by MartinForReal** [comment]
related #5152
