### ISSUE TITLE
Migrate the application-controller to golang

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2421]
The application component will emit other components when `kfctl apply` is called. This includes global resources such as clusterroles, clusterrolebindings and crds. An application controller will be deployed which tracks resources deployed within the namespace and reparents these resource's controller to itself. This should all be migrated to golang since the current controller is based on metacontroller and does not delete global resources.

**Comment by jlewi** [comment]
Should we write a design doc to make sure we are all on the same page? (See also #2233)

My understanding was that we aren't actually using the application controller to deploy any resources. 

Does the need for the Application controller go away now that we are moving kfctl to a go binary?
I thought all we needed to do was set labels consistently across all the K8s resources so that Kubeflow K8s resources are owned by the Kubeflow app.

**Comment by kkasravi** [comment]
Design doc is [here](https://bit.ly/2BukRoW)

**Comment by jlewi** [comment]
Adding this to 0.6; I think we're already oversubscribed for 0.5

**Comment by jlewi** [comment]
Per https://bit.ly/2BukRoW I think the current plan is to use the sig-apps controller and not build our own controller. So I'm closing this out.

/lifecycle obsolete.
