### ISSUE TITLE
JupyterHub authenticator with Active Directory

### ISSUE THREAD

**Issue by antigenius0910** [kubeflow/kubeflow#2459]
Hi,

Thanks for the awesome project once again!!

I followed kubeflow's README about jupyterHub here https://github.com/kubeflow/kubeflow/blob/master/components/jupyterhub/README.md
and get a clear understanding about how pod jupyter-0 get config through jupyter_config.py and being apply as a configmaps.

However, I would like to config LDAP auth as mentioned on below post.
https://zero-to-jupyterhub.readthedocs.io/en/stable/authentication.html?fbclid=IwAR2kAy4KICUHdQ_P8o9XcRZ00BQdu3pJ8OKQLMHe7_kzJQVL5cGs7rOAv_E#authenticating-with-ldap

All the config seems fine but the problem I am facing is the docker image jupyter-0 doesn't have jupyterhub-ldapauthenticator installed as module. I can step in the pod and do a "pip install jupyterhub-ldapauthenticator" but then I can't restart jupyterHub since the pod is being config running JupyterHub as pid 1. 

```
ychuang@C02W80YAG8WL:~$ kubectl exec -it jupyter-0  -- /bin/bash
root@jupyter-0:/srv/jupyterhub# ps -ef | grep jupyterhub
root         1     0  0 11:56 ?        00:00:01 /opt/conda/bin/python /opt/conda/bin/jupyterhub -f /etc/config/jupyter_config.py
```

It will always came out as below of I do "jupyterhub -f /etc/config/jupyter_config.py" in pod jupyter-0
```
[E 2019-02-12 12:14:56.216 JupyterHub app:1839] Failed to bind hub to http://0.0.0.0:8081/hub/
[E 2019-02-12 12:14:56.218 JupyterHub app:1938]
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1936, in launch_instance_async
        await self.start()
      File "/opt/conda/lib/python3.6/site-packages/jupyterhub/app.py", line 1834, in start
        self.http_server.listen(port, address=ip)
      File "/opt/conda/lib/python3.6/site-packages/tornado/tcpserver.py", line 144, in listen
        sockets = bind_sockets(port, address=address)
      File "/opt/conda/lib/python3.6/site-packages/tornado/netutil.py", line 163, in bind_sockets
        sock.bind(sockaddr)
    OSError: [Errno 98] Address already in use
```

I can restart the pod but then when the pod get restarted it doesn't have module jupyterhub-ldapauthenticator any more.

Does anyone knows how to solve this problem? or how can I get the docker file for jupyter-0 so I can re-write it and put it to my own docker registry?

Best,
Yen

**Comment by antigenius0910** [comment]
After checking on some forum. I design to add extra layer myself. But still think there should be a better way to do this. will keep update to see it this new image works for AD authentication.

```
#docker pull gcr.io/kubeflow/jupyterhub-k8s:v20180531-3bb991b1
#docker history f3c9c0973f76
#docker run -i -t --name jupyterhub_ad f3c9c0973f76 /bin/bash 

(step into container)
###update some tool and install ldapauthenticator
apt update
apt -y install inetutils-ping vim dnsutils
pip install jupyterhub-ldapauthenticator
(step out of container)

#docker stop jupyterhub_ad
#docker commit jupyterhub_ad kubeflow:jupyterhub-k8s-ad
#docker images kubeflow:jupyterhub-k8s-ad
#docker images -a

EPOSITORY                                                       TAG                  IMAGE ID            CREATED             SIZE
kubeflow                                                         jupyterhub-k8s-ad    1ec756c2de35        23 seconds ago      930MB
gcr.io/kubeflow/jupyterhub-k8s                                   v20180531-3bb991b1   f3c9c0973f76        8 months ago        780MB
```

**Comment by jlewi** [comment]
We are moving away from JupyterHub. Furthermore, we don't want to do auth in JupyterHub because we have many web applications (e.g. pipelines, katib, central dashboard) that require authentication and we don't want to re-implement this for every web app.

We'd like to have a single entrypoint that sits in front of all the apps and verifies the request. This is described in more detail in the CUJ and design doc in the ROADMAP.
https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md#enterprise-readiness

In this design you could potentially use something like [dex](https://github.com/dexidp/dex) to link to your identity system.

I don't see Active Directory listed on the dex page put its possible that's doable through one of the other protocols (like LDAP). 

I believe Active Directory is a Microsoft technology so I'm going to label this as Azure in the hope of spurring Microsoft involvement.

/cc @aronchick
