### ISSUE TITLE
due to naming of cluster resources, it's not possible to have more than one instance of kubeflow in a cluster

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2528]
kfctl should allow multiple kubeflow instances to be deployed to different namespaces even though there are cluster level resources within a typical kubeflow deployments.
`kfctl delete all` should not delete other instances or cluster resources belonging to other kubeflow deployments.

**Comment by jlewi** [comment]
Some resources in Kubeflow like CRDs are global resources. So I think there's more than just naming issues preventing multiple KF deployments in the same cluster.

Since CRD's are cluster level, it will be very difficult to install two different versions of Kubeflow with two different versions of the CRD's.
