### ISSUE TITLE
Multi user for Jupyterhub

### ISSUE THREAD

**Issue by gidutz** [kubeflow/kubeflow#2577]
When deploying Kubeflow on GKE, each user is authenticated using IAP.
When other Users would like to access the JupyterHub cluster (in order to work on the same notebooks) they get forbidden warning.

The same issue can be applied on other deployments. the user that created the cluster should be given Admin privilege and should be an easy way to add and remove users from the cluster

![screen shot 2019-02-28 at 13 18 35](https://user-images.githubusercontent.com/6208212/53563070-af435900-3b5b-11e9-8f7e-03982c991e37.png)

**Comment by jlewi** [comment]
Are you trying to share jupyter kernels?

Why not have every user launch their own jupyter kernel and share notebooks (ipynb files) through git or NFS?

**Comment by gidutz** [comment]
The idea is that the jupyter environment has two main goals:

1. A dirty environment for research and EDA - I don't want to commit (push to repo) on a draft notebook. instead one can create a notebook server and let others use it to perform messy research together. This will also enable me to share files and outputs with users working on the same playground.

2. Kaggle like kernels - lets say I want to commit to a notebook and share it with the team working on the project - for example - I developed an EDA that I want to share. It would have been nice if the pipelines screen would contain a tab for notebooks in which everyone can share useful notebooks and pipeline stages to be later used by other users.

I thinks that these stages would make Kubeflow an environment for mutually developing pipelines and not only running experiments of existing pipelines.

**Comment by jlewi** [comment]
I think if you wanted to do this with JupyterHub in 0.4 you might be able to accomplish that by configuring JupyterHub auth. Right now we configure JupyterHub to use IAP and only the user that owns the notebook can access it.

In 0.5 we are working on removing JupyterHub and switching to using ISTIO to control access to notebooks. 

With ISTIO a cluster admin should just be able to modify the ISTIO service rules in order to grant multiple users access to a particular jupyter instance.

**Comment by gidutz** [comment]
Awsome!
