### ISSUE TITLE
notebook manager - Volume name should default to name of notebook

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2592]
Right now the volume used for the notebook home directory /home/jovyan always defaults to "notebook-workspace".

This default will be invalid if the user tries to create multiple notebooks in a given namespace because the volume would already exist.

I think it would be better to make the volume name default to the name of the notebook so it would default to being unique for each notebook

/cc @vkoukis @kimwnasptd

**Comment by kimwnasptd** [comment]
When creating a natebook the current default behavior is to also create a new PVC for it (option `New` in Workspace Volume). There is a field for the name of that PVC with, as you noted, a default value of `notebook-workspace`. So the question is, what default value should we put there? 

We want to be able to both have a default behavior that works but we also don't want to restrict users as to what names to use if they want to create a new Volume. We could leave this field blank, when the `New` option is selected, and if the user sends the form without filling it out then the new PVC will have the name of the notebook. This would be our default behavior. 
Then if the user would like to give a different name to the newly created PVC they can just fill this field and the new PVC will use that name instead.

WDYT @jlewi ?

**Comment by kimwnasptd** [comment]
I could also restore the previous default behavior. Before if the Volume's name already exists in the cluster, then the UI won't create a new Volume but use the existing one instead. 
Later on when we have multi-user support, the default name of this volume could be `{username}-workspace` instead of `notebook-workspace`. 

This way by default the UI will use the user's PVC forthe new Notebooks they create.

**Comment by jlewi** [comment]
Can we do something like the following

* Default is to create a new volume
* Volume name will default to the notebook name
* As user types notebook name; volume name will change to match the notebook name
* User has the ability to explicitly give the volume a different name

is it possible to keep the volume name in sync with notebook name but still give user a way to make them not the same?

Could we do something like we do for the image name where there is a option selector the user can select to either name the volume after the notebook or to use a custom name?

/cc @kimwnasptd

**Comment by kimwnasptd** [comment]
@jlewi ok now I understand what you're thinking. I agree with having the volume name to be synced with the notebook's name. But I think we can skip the radio button and get a more clean experience.

* Default is to create new volume
* As user types the notebook name; volume's name value will be updated to match the notebook name
* If the user wants a different volume name, then they just edit the volume's name field
* If they decide to change the notebook's name; the volume's name will automatically match the new name (because of bullet 2)

One last thing from the UX perspective is the scenario where the PVC name they submit already exists. I think it makes sense to just use the existing PVC, rather than giving a warning (webapp can't create it since it already exists).

**Comment by jlewi** [comment]
Seems good to me.
