### ISSUE TITLE
[Front-End][Tracker] Create front-end tests for dashboard and notebooks

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#2618]
## About:
Tracker issue for all unit and integration testing we want to add to various front-end projects within Kubeflow

### Dashboard
General functionality and user flows

### Notebooks
We would like to test the notebooks page in selenium to test the construction of a notebook, which will eventually be made into a presubmit test. For now, it should be able to run manually

/assign @avdaredevil @prodonjs 
/cc @jlewi

**Comment by prodonjs** [comment]
The code for the notebooks front-end is in [components/jupyter-web-app](https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app/default/kubeflow/jupyter). It probably makes sense to have tests included and run against that component rather than working through centraldashboard but ideally, our test framework can be used for all of the front-end components that need to be tested.

**Comment by avdaredevil** [comment]
Yeah I was wondering if we want to make another Kubeflow repo for testing all different components, or configure at the component level?

**Comment by jlewi** [comment]
So we have tests for central dashboard but not notebooks.

I think we should file a separate issue for notebooks that we add to 0.6 and close this issue.

**Comment by avdaredevil** [comment]
Closing since Notebooks is not needed for this release
