### ISSUE TITLE
kfctl kustomize test suite (unit and e2e)

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2630]
the kustomize components in the repo kubeflow/manifests should have similar unit, e2e tests as ksonnet.

**Comment by swiftdiaries** [comment]
/assign @swiftdiaries 
I'll pick this one up :)

**Comment by jlewi** [comment]
@swiftdiaries How's it going with the testing? Do we have an E2E test that could be used to verify that deploying with kustomize is working?

**Comment by swiftdiaries** [comment]
I'm not sure about the approach for unit testing components. 
I'm working on kfctl kustomize E2E test, I should have something before EOD or early tomorrow

**Comment by jlewi** [comment]
@swiftdiaries How's this coming?  Looks like you have #3060 in progress?

**Comment by swiftdiaries** [comment]
#3060 is for the E2E test. Now that #2971 is merged, I'll go ahead and merge that.
For the unit tests of manifests, I'm currently exploring the kustomize test harness. [Reference](https://github.com/kubernetes-sigs/kustomize/tree/master/pkg/target).

I'm having a bit of trouble because the implementation is split between two packages inside the same directory. I'm not sure how to import them for use inside Kubeflow. Any advice on how to do that?

**Comment by jlewi** [comment]
@swiftdiaries unfortunately you are probably the expert; so I don't have much help to offer. Were you able to make any progress?

**Comment by kkasravi** [comment]
@swiftdiaries I just [copied](https://github.com/kubeflow/manifests/pull/34/files#diff-ba78b29234976b9867e1c7aaaf216b8d) it into manifests/tests including the loadertest .

I also autogen'd the tests with a bash script -

**Comment by jlewi** [comment]
@swiftdiaries What's the current status?

* Do we have an ETA for an E2E test?
* What are the blockers if any?

**Comment by jlewi** [comment]
@swiftdiaries Any update I think @kkasravi committed the fixes to make kustomize +  ISTIO work on master. Can we get #3060 updated and merged.

**Comment by swiftdiaries** [comment]
Cool thanks!
I'll get it updated and push it before tomorrow :)

**Comment by jlewi** [comment]
According to @kkasravi #3375 pulled in @swiftdiaries changes in #3060.

Lets verify that we have a postsubmit test that is running and passing using ISTIO and kustomize and then close this issue.

**Comment by jlewi** [comment]
kfctl_go_test.py is setting the package manager to kustomize here
https://github.com/kubeflow/kubeflow/blob/5f1762a5a973d3441f010096357ba882f2c9386e/testing/kfctl/kfctl_go_test.py#L91

So all tests using kfctl_go_test.py should be using kustomize.

Here's a postsubmit run.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/kubeflow_kubeflow/kubeflow-postsubmit/1139677020716797952

The postsubmit failed for tests
kubeflow-postsubmit-kfctl-go-iap-istio-5f1762a-7952-53f2-phase
kubeflow-postsubmit-kfctl-go-basic-auth-5f1762a-7952-7721-phase

The logs for the deploy step for kubeflow-postsubmit-kfctl-go-iap-istio-5f1762a-7952-53f2-phase are attached.

The logs seem to confirm that kustomize is being used; lots of references to kustomize.go no references to ksonnet.go.

So the problem now is that the postsubmits appear to have started failing on 06/13

[Uploading kubeflow-postsubmit-kfctl-go-iap-istio-5f1762a-7952-53f2-1130131588.log.txt…]()

**Comment by jlewi** [comment]
Here are the logs for the postsubmit failure. The test is failing because its waiting for the studyjob-controller deployment to be ready but that deployment is not found.

My suspicion is that this is a bug in the kustomize manifest. This would explain why it wouldn't be caught in presubmit because we currently don't run the E2E tests on presubmits for kubeflow/manifests

[kubeflow-postsubmit-kfctl-go-iap-istio-5f1762a-7952-53f2-944830470.log.txt](https://github.com/kubeflow/kubeflow/files/3294829/kubeflow-postsubmit-kfctl-go-iap-istio-5f1762a-7952-53f2-944830470.log.txt)

**Comment by jlewi** [comment]
@swiftdiaries Any update on this? Now that kubeflow/manifests#139 is merged can we close this or is there more work to be done?

**Comment by jlewi** [comment]
@swiftdiaries ping?

**Comment by swiftdiaries** [comment]
/close 
Closing as E2E and unit tests are merged and working as expected in kubeflow/manifests.
There is work to be done to improve maintainability of the tests. I'll open another issue for that.
