### ISSUE TITLE
Build kubeflow docker images on power

### ISSUE THREAD

**Issue by dreamryx** [kubeflow/kubeflow#2633]
We have test running latest mnist example with kubeflow 4.0 on Power 8 (ppc64le architecture). During the test, we have built a lot of kubeflow docker images on power and want to contribute the dockerfiles. We supposed to have two options:

 - Due to a lot of changes of dockerfiles is just replace the base image, we can follow the way in k8s - create temp docker file and replcace the base image variable to build images for different arch. For example, https://github.ibm.com/platformcomputing/kubernetes/tree/master/cluster/images/hyperkube. To make makefile look nice, this way better have a fixed registry contains images for different platforms with consistent naming style.
 
 - Add new dockerfiles with suffix "-ppc64le". Then each dockerfile can be used to built image for specific platform.

**Comment by gyliu513** [comment]
@jlewi any comments for this? Seems there are also some discussions at https://github.com/kubeflow/kubeflow/issues/925

FYI @hougangliu @jinchihe

**Comment by jlewi** [comment]
IIUC your are proposing modifying all Kubeflow related Docker images in order to build versions for power. 

So this is a pretty big change that touches pretty much all of Kubeflow. If so it would be great to put together a doc documenting this in more detail and discuss it in the community meeting or perhaps the developer summit if your there.

Can/Should we localize all power related changes in a single location

e.g. could we have  a repo kubeflow/power that would contain dockerfiles and other tooling needed to build for power? Can we use automation to keep this in sync with the underlying repos so for example if the TFJob Dockerfile is updated in kubeflow/tf-operator this change is automatically propogated to kubeflow/power

**Comment by gyliu513** [comment]
Thanks @jlewi , your comments really helps!!

Compared with `create a new repo kubeflow/power`, we prefer the big change. As in the future, we may also want to support [s390x](https://en.wikipedia.org/wiki/Linux_on_z_Systems) as well. Creating a repo for each platform maybe difficult to manage.

So we will try to create a design document first and try to review it in community meeting after ready for review.

Besides, we also have another issue https://github.com/kubeflow/kubeflow/issues/2226 which want to unify the kubeflow image build and location. As currently, all of the base images in kubeflow are already multi-arch docker images, so it is pretty simple to enable those images to support POWER, we already have some PRs as follows:
- https://github.com/kubeflow/tf-operator/pull/893/files This is trying to update the hardcode `amd64` to a variable so that it can be configured on different platforms.
- https://github.com/kubeflow/pipelines/pull/567/files 

So how about continue the task in https://github.com/kubeflow/kubeflow/issues/2226 first and make all of the arch for docker image can be configurable? This can make sure the kubeflow can be build on the platform as customer want.

Meanwhile, we will try to create a design document for how to refactor the overall Dockerfiles in kubeflow repo and make it follow the k8s style for better management in future. Comments?

FYI @chenzhiwei @dreamryx

**Comment by jlewi** [comment]
We are starting to work on 0.6 which will be released end of June (our releases are quarterly).

If you'd like this to be part of 0.6 it would be great if one or more folks would step up and take the lead on making this happen. 

In addition to submitting a proposal it would be good to provide regular updates at the community and PM meetings.

**Comment by gyliu513** [comment]
Thanks @jlewi , we will try to attend the meeting and provide the update.

**Comment by denfromufa** [comment]
I'm interested in power8/power9 builds too

**Comment by animeshsingh** [comment]
@denfromufa what' driving your interest in the Power8/9 builds?

**Comment by animeshsingh** [comment]
Discussion doc here
https://docs.google.com/document/d/1CDYYdWi9qP96qaddyI8eO3r1w3yXb5wNBfE5csnRgVs/edit#

**Comment by jmsking** [comment]
Hi,@jlewi, i am in China, and i have already pull all needed images to work nodes, and i need modify the imagePullPolicy from "Always" to "IfNotPresent", when i execute:
**$kfctl generate all -V**
**$cd $KFAPP**
**$grep -r "Change to IfNotPresent"**
```
manifests/manifests-56e2fb15db286198f7a53723cb1fbfecf3fe83fb/tests/workflows/components/kfctl_go_test.jsonnet:    // TODO(jlewi): Change to IfNotPresent.
kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/testing/workflows/components/unit_tests.jsonnet:    // TODO(jlewi): Change to IfNotPresent.
kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/testing/workflows/components/kfctl_go_test.jsonnet:    // TODO(jlewi): Change to IfNotPresent.
kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/testing/workflows/components/kfctl_test.jsonnet:    // TODO(jlewi): Change to IfNotPresent.
kubeflow/kubeflow-0dbd2550372c003ba69069aeee283bd59fb1341f/testing/workflows/components/click_deploy_test.jsonnet:    // TODO(jlewi): Change to IfNotPresent.
```
**my question is: need i only change the imagePullPolicy of these files from "Always" to "IfNotPresent"?**

my kubeflow' version is v0.6.2

_Any help i will appreciate!_

**Comment by jinchihe** [comment]
Hey @jmsking,
Theoretically the image will not pull again if your nodes have the image. But here I want to confirm, is that related with POWER？or you used POWER platform and build yourself with same name of image so that you do not want to pull again?

**Comment by jmsking** [comment]
Hi, @jinchihe because i can't pull image from gcr.io in china, so i get all needed image from dockerhub, and i pull these image to all k8s cluster work node, but when i restart install kubeflow, there still some pod occur ErrImagePull, so i doubt that the imagePullPolicy is "Always", so i need modify these "Always" to "IfNotPresent", but i don't know how to find these

**Comment by jinchihe** [comment]
@jmsking you can check the cluster the image policy in the pod, if needed, you can just edit related deployment. Personally your problem is not related this one that's discussing build image for POWER platform, I suggest creating new ticket if any problem, or get help in Slack. Thanks.

**Comment by jmsking** [comment]
OK, how can i contact you, because i have some question for kubeflow, and can i ask for your help? thx

**Comment by jinchihe** [comment]
> OK, how can i contact you, because i have some question for kubeflow, and can i ask for your help? thx

contact me by Slack or Wechat 18091802816. I will remove the info later once you contact me. Thanks.

**Comment by jinchihe** [comment]
> OK, how can i contact you, because i have some question for kubeflow, and can i ask for your help? thx

You can get help by Slack :-）
