### ISSUE TITLE
kfctl config files should be moved to kustomization

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#2685]
Right now under bootstrap/config we have 
gcp_prototype.yaml
kfctl_basic_auth.yaml
kfctl_default.yaml
kfctl_iap.yaml

Each file repeats a lot of information and should be an overlay on a base file. 
This can be a kustomize component.

One possibility would be to have a kustomize transformer config that references the base config but applies variants to the client spec fields as described [here](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md)

**Comment by jlewi** [comment]
Right now these files are listing which ksonnet packages and how they should be configured in different scenarios (e.g. using IAP vs. basic auth).

So I agree we'll need to come up with a corresponding solution for this problem when we migrate off ksonnet to kustomize.

**Comment by jlewi** [comment]
I recall discussing this somewhere; maybe in slack? 

Is using overlays the right direction?

Overlays add a lot of complexity. In particular, overlays hurt readability because in order to understand what the actual config file would be, one has to go through the mental gymnastics of combining the overlays.

In contrast, if each YAML file provides a self-contained description of how kubeflow should be deployed then its much easier to reason about.

If we are worried about duplication in the YAML files, can we use tooling (kustomize, jsonnet, jinja, etc...) to maintain templates from which we generate the YAML files? But check in the YAML files and let a single YAML file be the input to kfctl.

This avoids pushing the complexity of generating those templates into kfctl.

The other way we can deal with duplication is to write tests that verify expectations which should be true across a set of YAML files. For example, if there a bunch of YAML files for which a bunch of ISTIO related settings should all be the same we can write a test to verify that this is true across all the configs.

**Comment by kkasravi** [comment]
> The other way we can deal with duplication is to write tests that verify expectations which should be true across a set of YAML files. For example, if there a bunch of YAML files for which a bunch of ISTIO related settings should all be the same we can write a test to verify that this is true across all the configs.

we have something like this under /manifests/tests - where expected is embedded in the golang code and it's compared with generated.

> Overlays add a lot of complexity. In particular, overlays hurt readability because in order to understand what the actual config file would be, one has to go through the mental gymnastics of combining the overlays.

This has been greatly simplified to merging one or more kfctl_default.yaml
```
config
├── base
│   └── kfctl_default.yaml
└── overlays
    ├── application
    │   └── kfctl_default.yaml
    ├── basic_auth
    │   └── kfctl_default.yaml
    ├── gcp
    │   └── kfctl_default.yaml
    ├── istio
    │   └── kfctl_default.yaml
    ├── ksonnet
    │   └── kfctl_default.yaml
    └── kustomize
        └── kfctl_default.yaml
```

Merges are simple appends on lists (components, packages, componentParams).
So it's pretty easy to see what base + gcp would look like

**Comment by kkasravi** [comment]
we could store these different 'mixins' under config (like we used to - maybe kfctl_basic_auth_istio.yaml, kfctl_gcp_istio.yaml) so that kfctl isn't doing this dynamically as part of the CLI options. But we should have unit tests so that changes in the underlying templates are reflected in the generated yamls. 

an argument against doing this is to compare what we do with kustomize with what we did with ksonnet which was far more complex, with different yamls being produced as a function of parameters specified in the prototypes.

**Comment by jlewi** [comment]
A key goal is being able to give each platform owner/vendor a way to define what the KF experience looks like on their platform.

Can this approach scale to handle that?

What does the OWNERs files look like and how does this end up looking?

Consider the following

1. On GCP we decide we want the SparkOperator, no PyTorch CR, and ISTIO always
2. Azure decides they want to install Lyft's FlinkOperator, PyTorch CR and no TFJob, and ISTIO always

How would they do that? 

Doesn't the use of overlays make this very difficult? 

I think I would have to first create a base for GCP and Azure that defines the set of applications I want. The existing ISTIO overlay is dependent on the base since its to set the ISTIO flag for each application that takes it. So I can't reuse the existing ISTIO overlay. And why would I use an overlay at all in this case rather than just setting the ISTIO parameter for each application in the new bases "kfctl_gcp.yaml" and "kfctl_aws.yaml".

Or suppose some folks now want to create a set of variants that only installs TF related components but for multiple clouds?

> an argument against doing this is to compare what we do with kustomize with what we did with ksonnet which was far more complex, with different yamls being produced as a function of parameters specified in the prototypes.

I'm not sure I understand what complexity you are referring to.

**Comment by kkasravi** [comment]
> Consider the following

> On GCP we decide we want the SparkOperator, no PyTorch CR, and ISTIO always
> Azure decides they want to install Lyft's FlinkOperator, PyTorch CR and no TFJob, and ISTIO always
> How would they do that?

But can we generalize a set of choices per platform? That is, the same argument holds when bundling a set of choices for Azure - a given kubeflow user/vendor that uses Azure may want different choices than what we would bundle in kf_azure.yaml. Currently we have 2 areas where specific choices can be made - 1. creating a 'default' platform under bootstrap/config and 2. editing `app.yaml` after `kfctl init...` but before `kfctl generate...`. The first area can be driven by cli options (--use_istio, --use_basic_auth, --platform) but it doesn't seem possible to provide a kf_azure.yaml that would address requirements for each user of azure - eg your second point above.

 > I think I would have to first create a base for GCP and Azure that defines the set of applications I want. The existing ISTIO overlay is dependent on the base since its to set the ISTIO flag for each application that takes it. So I can't reuse the existing ISTIO overlay. And why would I use an overlay at all in this case rather than just setting the ISTIO parameter for each application in the new bases "kfctl_gcp.yaml" and "kfctl_aws.yaml".

The current base does assume a set of applications, though the ISTIO overlay that adds istio to all components that need a virtual-service is harmless - if the component isn't listed then the overlay wouldn't be applied. But I see your point. 

I think I mentioned in PR #3375 that overlays probably make most sense when adding services across components vs merely appending additional components. Even then using kustomize to generate a `<platform>.yaml` would need to have platform specific overlays in order to match the base set of components defined for the platform. I agree that tooling should probably be used to generate platform files as well as specific customizations per platform. Tooling could be as simple as `kustomize edit ... kf_azure.yaml` or more sophisticated using kustomize plugins. I think we can close this issue and open one related to customizing the default files under bootstrap/config.

**Comment by kkasravi** [comment]
@jlewi if ok with you I can close and open a new issue to address how platform yamls are modified.

**Comment by jlewi** [comment]
@kkasravi SGTM.
