### ISSUE TITLE
click-to-deploy and kfctl should share code for shared logic.

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#2712]
We have gcp_util / k8s_utils / ksonnet_util / kustomize_util which can be shared between click-to-deploy and kfctl.

click-to-deploy API rewrite and kustomize migration could be 2 chances to help with this effort.

**Comment by jlewi** [comment]
At a minimum to deploy 0.5 do we need to rewrite the handler for "/e2edeploy" to use the kfctl library so that the logic is the same?

Could we add support for this and rollout it out to prod behind a query argument so that we could test it out before making it the default? And then change the default so that users will use the new logic but can fall back to the old logic if necessary.

**Comment by kunmingg** [comment]
TODOs:
- https://github.com/kubeflow/kubeflow/issues/2610
- refactor kfctl interface to fit use case of app backend.
- app backend: add execute path using libs imported from kfctl.
- kfctl:
  1. Monitoring integration
  2. retry wrapper around API calls

**Comment by jlewi** [comment]
@kunmingg Any update? Looks like we are waiting on #3045.

**Comment by kunmingg** [comment]
Will try to merge #3045 early this week.

**Comment by jlewi** [comment]
I believe the updated click to deploy is in staging and we just need to wait for it to be in prod before we can close this issue.

**Comment by jlewi** [comment]
Closing this because the new refactored backend which uses the same logic is now in prod.
