### ISSUE TITLE
Include platform specific links in central dashboard

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2885]
I think it might be valuable if the central dashboard could include links to platform/cloud resources related to Kubeflow.

For example on GCP it would be useful to have links to

1. the deployment manager page associated with a Kubeflow deployment
1. the GKE cluster page for a deployment
1. stackdriver logs.

I think this raises some design questions

1. How do we make the links pluggable since they will be different on every platform?

/cc @prodonjs @avdaredevil

**Comment by prodonjs** [comment]
It looks like Spartakus is able to ascertain the platform information from the other nodes in the cluster (https://github.com/kubernetes-incubator/spartakus/blob/a593c5e0f13efa415752bf4ebaccdacddf7e979a/pkg/volunteer/kubernetes.go#L64), so that pattern can be followed assuming that the Central Dashboard's server component has the appropriate roles within the cluster.

If we can get a map of what we'd want to show for each platform, this is something we can target for 0.6.0.

**Comment by jlewi** [comment]
@avdaredevil see https://github.com/kubeflow/kubeflow/issues/2976#issuecomment-485407082 for not being blocked on uber Application K8s resource being defined.

**Comment by prodonjs** [comment]
@jlewi https://kubeflow-1.endpoints.prodonjs-kubeflow-dev.cloud.goog/ demonstrates the behavior for GCP-specific platform-links. We extract the project ID and use it to build the links that display below the *GCP Information* header. Currently, we don't have any links defined for other platforms.

We also retrieve the version number from the first Application CR found in the namespace of the dashboard to show it in the bottom right-hand corner. If no CR exists, we display unknown.

Any thoughts?
