### ISSUE TITLE
Why is basic auth required

### ISSUE THREAD

**Issue by hongye-sun** [kubeflow/kubeflow#2890]
I usually use port-forward to connect to a KF cluster, but after recent release in v0.5.0-rc1, it appears that basic auth is required for the KF setup.

I can no longer run my KFP client code by directly pointing to localhost with forwarded port. I need to figure out how to pass the basic auth from the client code.

This might not be a too big deal, but I wonder why basic auth is required even I don't want to expose a public endpoint and just want to use port forward to access the cluster.

**Comment by jlewi** [comment]
basic auth is not required.

I believe you are deploying via click to deploy on GCP and selecting the "skip IAP" button.

I believe skip IAP was just configuring a dummy OAuth credential for IAP so users wouldn't have to setup IAP.

Since IAP was disabled users would need an alternative way to connect and so in the past people would connect directly to services running inside the cluster (e.g Jupyter or Ambassador).

port-forwarding to Ambassador was never explicitly supported or unsupported.

Ambassador is largely an internal detail of how access to Kubeflow services from outside the cluster is configured which will vary a lot from platform to platform.

As illustrated in #11 Ambassador was expected to be behind an ingress or exposed via K8s loadbalancer or node-port on which people could access it. How people do that as well as enforce auth is very platform specific.

With click-to-deploy and GCP we exposed ingress via an external IP address that was then secured via IAP.

For click to deploy we explicitly wanted to make Kubeflow accessible on a public but secure IP because we wanted people to be able to use Kubeflow entirely form a webbrowser with no client side installation. So requiring a client side tool kubectl/ssh/vpn to setup a secure tunnel would have defeated that goal.

The skip IAP was a kludge for people who were more interested in not having to create OAuth credentials as opposed to setting up client side tools to connect to their cluster.

In more recent releases we offered basic auth as a less secure but simpler way to setup a publicly accessible but secure endpoint.

The skip IAP option was then changes to mean use basic auth rather than IAP to configure my cluster.

Basic auth is implemented using Ambassador's [external auth](https://www.getambassador.io/reference/services/auth-service/) support.

One of the goals of having a centralized gateway (#11) is to apply security policies in a centralized way . So the gateway was configured to reject any traffic which wasn't secure. This means if you have basic auth configured all traffic needs to have basic auth credentials attached or it will be rejected.

So that's one issue with doing kubectl port-forward.

The second is that our implementation of basic auth depends on it being configured with the host it is intended to serve on. When we deployed Kubeflow on GCP we configured basic auth using fully qualified domain name used with the public endpoint that we configured. When you do kubectl port-forward the host is no localhost and it doesn't match.

This is a more general problem in that some webapps need to be configured explicitly with the path they are serving on. So if Kubeflow is deployed and configured to serve on `https://${FQDN}` port-forwarding to individual apps may or may not work based on the application.

In this case, the basic auth gatekeeper is one such example.
