### ISSUE TITLE
[GCP] Make autofill work with click to deploy

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#2952]
We'd like autofill to work with the click to deploy app.

In particular, we'd like web browsers to treat client id and client secret as username/password and store them securely while still allowing the user the convenience of auto-filling them when a user comes back to deploy.kubeflow.cloud

/assign @avdaredevil

**Comment by avdaredevil** [comment]
@prodonjs I think local storage could tackle this issue, right? Since we don't really have a database. And we would do some stylistic changes to make it look like something was auto-filled

The only caveat in this comes if users want to change the fields, do we want to remember more identities, or just the last successful one? @jlewi

**Comment by Ark-kun** [comment]
AFAIK, you just need to specify the proper input types and the browser will handle it automatically.
It's more of the browser's business to remember and auto-fill the identities.
