### ISSUE TITLE
[GCP] Document how to deal with deployment crashes no default network

### ISSUE THREAD

**Issue by KMFidom** [kubeflow/kubeflow#2969]
Keep getting this error when deploying kubeflow. I have made id anonymous by replacing my project ID with these words.

kubeflow: {"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Project \"PROJECT_ID\" has no network named \"default\".","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/PROJECT_ID/zones/us-east1-c/clusters","httpMethod":"POST"}}

**Comment by jlewi** [comment]
Reference:
https://cloud.google.com/vpc/docs/vpc#default-network

**Comment by jlewi** [comment]
@LukasBlank 

If you need to customize your network the way to do this is 

1.  Run `kfctl generate`
1. Edit the deployment manager configs in ${KFAPP}/gcp_configs
1. Run `kfctl apply`

The configs are using deployment manager. You can find the docs here.
https://cloud.google.com/deployment-manager/docs/configuration/create-basic-configuration

They are basically just defining GCP objects declaratively using jinja for templating. The specs should map 1:1 to the payload in GCP APIs.
So if you look at the GKE API; a create request takes a cluster object
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters

It would be great to get this added to our documentation

**Comment by LukasBlank** [comment]
@jlewi 
oh sorry, my bad. It works now that i edit the cluster.jinja instead of the yaml. Have never done this before and did not really understand what i was trying to do. Would definitely be great to be added to the documentation but thank you very much anyways :)

**Comment by jlewi** [comment]
Lets use this to track updating the docs.

I think we should update the GCP troubleshooting guide.
https://www.kubeflow.org/docs/gke/troubleshooting-gke/

**Comment by guhcampos** [comment]
Hello!

I'm having the same problem. In my case, the network `default` does not exist because I use a Shared VPC architecture to bind together multiple projetcs in the company. Before stumbling into this issue I had found #3082 which is now closed, but I could not find any documentation about Shared VPC usage in Kubeflow docs.

I tried the "update after generate" approach, but that led me to the following error during apply:

```
couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp: Missing plugin gcp
```

which I'm still trying to debug. I'll update if I find a fix.

**Comment by jlewi** [comment]
@guhcampos I'd suggest opening up a new issue for your specific problem. If you can post on the issue details like your app.yaml that will debug things.

The error

```
Apply failed for gcp: Missing plugin gcp
```

Indicates its looking in your app.yaml file for a GCP plugin spec and not finding one.

If you can provide more detail about how you are trying to set things up (e.g. what commands you ran) that will make it easier to troubleshoot.

**Comment by guhcampos** [comment]
@jlewi indeed it was a simple misconfiguration, I had tried so many different setups this last one was an attempt I tried by creating my own GKE cluster with Terraform, then moving to setup Kubeflow on it with `kfctl`, which failed because I had run `init` with only the k8s components.

I ended up setting up the `default` network on my project so at least I can get to test Kubeflow before integrating it into my setup. It went well and it's currently up and running, so there's no need for the additional issue. The docs on customising the GCP deployment would be much appreciated =)

As a suggestion, I'd say the whole setup process tries to hide a lot from the user deploying Kubeflow, which is great if it's someone with little background just trying it out, but for most of us with highly customised production environments on AWS/GCP it may be too limiting, so the docs could go deeper into telling us what's going on. I learned a lot by looking at the Deployment Manager and Kustomize source code to the point I'm tending to not use `kfctl` at all so I can have more control of the deployment outcome. 

That's fine: I understand I'm expected to read the code if I want to go crazy on stuff, but I felt there's a large gap between the "just press this button to get started" and the "deploy kubeflow to your existing environment" use cases.

**Comment by amygdala** [comment]
A note that other user(s) have reported this as well, with newly created projects.  It sounds like the default network is not reliably set up properly (?). 
Could it make sense to create that network it if it doesn't exist, as part of the deployment actions?

**Comment by sarjeet2013** [comment]
I was hitting this issue and able to resolve this by adding following in 2 files:

In cluster.jinja:
```

**Comment by carlose2108** [comment]
Hi @sarjeet2013 

I'm new on Kubeflow and I have the same issue. Where do I add this files in GCP to fix it?

Thanks a lot.

**Comment by jlewi** [comment]
@carlose2108 

The deployment manager configs will being `${KF_DIR}/gcp_configs`. There is more information in the docs
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#application-layout

You will want to 

1. Run `kfctl build` to generate the configs
1. Modify the configs
1. Run `kfctl apply`

More info 
https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#understanding-the-deployment-process

**Comment by githubwua** [comment]
Alternatively, we can build a GKE cluster according to this doc, and specify a non-default network for the GKE cluster nodes.

  https://cloud.google.com/ai-platform/pipelines/docs/configure-gke-cluster

After which, we can specify the GKE cluster when creating a new kubeflow instance.

  https://cloud.google.com/ai-platform/pipelines/docs/setting-up#existing-cluster
