### ISSUE TITLE
Firefox Height issues for Dashboard

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#3065]
## About
Issue brought up: https://kubeflow.slack.com/archives/C7REE0EHK/p1555394151061800
![image](https://user-images.githubusercontent.com/5303018/56452623-b7ac4a80-62e7-11e9-9803-10c679848f6b.png)

**Comment by avdaredevil** [comment]
This was actually resolved by #2859. @prodonjs' cluster has this change in but @zabbasi's does not. Need to see why that is

**Comment by avdaredevil** [comment]
This seems to be in v0.5.0. Have to chalk these issues to a slightly older 0.5.0 release:
https://github.com/kubeflow/kubeflow/blob/v0.5-branch/components/centraldashboard/public/styles.css#L11

**Comment by prodonjs** [comment]
Interesting, @zabbasi, can you provide the container image from the centraldashboard Pod in your cluster? This change was in the tagged release, but because of the way the container images are tagged, it's not obvious which image in https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/centraldashboard?gcrImageListsize=30 corresponds to the golden release of 0.5.0.

@avdaredevil Going forward, we probably adjust the build process to make it easier to determine the specific commit hash for the running image to make it easy to determine the source tree in use.

**Comment by avdaredevil** [comment]
@prodonjs The change has now been addressed in #3100
