### ISSUE TITLE
[GCP] Use managed certificates instead of cert-manager

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3079]
In 0.6 we should switch to using GCP managed certificates
https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

This is blocked on upgrading to GKE 1.12 or later see #3023

**Comment by strangemonad-faire** [comment]
I'm curious what the benefit is given that this will only work in gcp/gke. When running in other clouds, you'll still have to use certmanager / let's encrypt correct? I feel like there's already a good number of issues that arise due to the complexity in documenting differences that arise in different cloud environments. 

Personally, my preference would be to have a resource to manage cert management move into mainline k8s (much like ingress and storage are common resources that work across clouds).

**Comment by jlewi** [comment]
/assign @zabbasi 

@zabbasi might have cycles to take a look this week.

**Comment by jlewi** [comment]
@strangemonad-faire The intent here isn't to create a generic solution. The intent here is to optimize the experience on GCP. Using managed certificates has a lot of advantages. One of them is that we no longer need to accept HTTP traffic for certmanager.

**Comment by lluunn** [comment]
I can pick this up after the workload identity
