### ISSUE TITLE
Use kftctl to install Kubeflow on on-prem cluster

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#3162]

**Comment by swiftdiaries** [comment]
/assign @swiftdiaries 
[PR link](https://github.com/kubeflow/kubeflow/pull/3026)

**Comment by solovyevt** [comment]
Just to clarify: is it impossible to use kfctl for on-premise now? Why using `kfctl apply k8s` for that?

**Comment by yanniszark** [comment]
Platform `existing_arrikto` can install Kubeflow, using kfctl, on existing, on-prem Kubernetes clusters.
Based on that, should we close this issue or is there more to do?

Refs:
* https://github.com/kubeflow/kubeflow/pull/3538
* https://www.kubeflow.org/docs/started/getting-started-k8s/

**Comment by jlewi** [comment]
I think we should refactor exiting_arrikto.yaml to make Dex and ISTIO more composable.
See
https://github.com/kubeflow/kubeflow/issues/3694#issuecomment-514371058

I think some of the changes we need are

* Create a kustomize package to install Dex
* Use KfDef.Spec.Applications to list Dex and ISTIO as applications to be installed

This might be partially blocked by #3709  and making kfctl support more reconcile semantics.

@yanniszark what was the information that isn't known during the generate phase? Is it the IP address? Where does that get used? Creating the certificates.

**Comment by yanniszark** [comment]
> @yanniszark what was the information that isn't known during the generate phase? Is it the IP address? 

Exactly.

> I think we should refactor exiting_arrikto.yaml to make Dex and ISTIO more composable.

I agree and I believe this work is tracked in #3739.
I proposed closing because this issue is about installing in an on-prem cluster and that can now be done.

I believe improvements to the existing approach should be tracked in followup issues, like #3739.
What do you think?

**Comment by johnugeorge** [comment]
@yanniszark I am confused here as we are mixing up things.  

It is quite difficult to have a generic config for existing clusters or on-prem config.  There is no single config that can satisfy needs of all deployments. Opinionated KF installation should be under a platform. 

Existing k8s cluster is different from on prem cluster. Existing cluster can be in any cloud or on prem. My expectation of KFctl run on an existing k8s cluster would be installation of all KF repo packages with their direct dependencies(like in the previous releases without any external dependency). It should be simple and should work without any extra configuration.  Auth should not be mandated for the base installation unlike a platform installation(eg: GCP) . Given our composable architecture of manifests, Users should be able to select and add any component based on their needs. So they can add it later if they need to use in their env. See https://github.com/kubeflow/kubeflow/pull/3663  

Similarly for on prem installation, we should follow the same composable architecture. See  https://github.com/kubeflow/manifests/pull/195  which are just kustomize packages.  However, most of the on prem users ask for a reference config because of the constraints in the env.  Auth/Authorization is one of them.  We should discuss if we can come up with one base reference config which is completely vendor neutral.  This can be also used to ensure kubeflow build sanity for on-prem clusters.  See comment https://github.com/kubeflow/kubeflow/issues/3694#issuecomment-514105334

**Comment by jbottum** [comment]
I appreciate the strategy defined by johnu.   We might need to define some phases as there are conflicting requirements i.e. make it simple, work everywhere, and provide enough to be useable.  In addition, how can we we effectively test it (for every release).    I wonder if we can use the low bar and high ceiling concepts to define some specific deliverables (that can be effectively tested)
