### ISSUE TITLE
Verify Istio gateway/virtual services for different components on premise

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#3182]

**Comment by yanniszark** [comment]
I've been looking into how the Istio Gateway and VirtualServices work and I would love to help with this issue.

From my understanding, the goal of this issue is to have Kubeflow working with Istio without caring for any form of auth.
In other words, make sure the `User->Gateway->KF Components` routes are functional.

My plan is the following:
1. Start from a clean master config.
2. Deploy with the default `kfctl` commands and start checking components.
3. For each component, note what is missing from `kfctl`.
4. Patch `kfctl` so that it deploys correctly with Istio.

**Comment by swiftdiaries** [comment]
Awesome ! Thanks for picking this up :) 
I'll assign the issue to you 
/assign @yanniszark

**Comment by swiftdiaries** [comment]
From my initial look into this, the pipelines and katib UI routes work as expected but the other virtual services don't. 
Also, I had to install Istio and Kubeflow Gateway separately. And set the istio-ingressgateway service in the istio namespace to NodePort to make it adapt for on-premise clusters.
Hope this helps :)

**Comment by yanniszark** [comment]
@swiftdiaries thanks for the help!
I have made a few fixes and now it seems to work using the default installation guide.
This means it will also work for an on-prem installation.
The work is tracked in #3376

**Comment by yanniszark** [comment]
I believe this can close now, these services were confirmed as part of the existing_arrikto PR (https://github.com/kubeflow/kubeflow/pull/3538)
Deploying with [existing_arrikto](https://www.kubeflow.org/docs/started/getting-started-k8s/#Kubeflow-for-Existing-Clusters---by-Arrikto) confirms that these services work in an on-prem environment.

/close
