### ISSUE TITLE
Make it easier for users to add additional scopes to GKE cluster

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#3361]
e.g. if someone wants to allow the compute nodes to access bigquery automatically

**Comment by holdenk** [comment]
I think we can do this by updating `scripts/gke/deployment_manager_configs/cluster.jinja`

**Comment by jlewi** [comment]
Yes that will work. 

Is there a reason you want to grant additional scopes to the VM service account though?

Why not grant your process a service account with appropriate credentials rather than relying on the VM service account?

Using VM service accounts is not considered best practice because all pods running on the VM have access to the VM service account.

So by design we try to grant the VM service account minimal permissions which is basically GCS for GCR and stackdriver for logging.

**Comment by holdenk** [comment]
@jlewi using a process SA would be reasonable. I was thinking for common read-only data sources it might make sense (e.g. bigquery), but if it's a pattern we don't want to encourage folks to use then making it easier isn't ideal.

**Comment by jlewi** [comment]
@holdenk any suggestions on what can be improved? Right now we create an SA and store the service account as a K8s secret that can be mounted into pods.

So granting additional permissions would mean changing IAM roles for that account

**Comment by holdenk** [comment]
Maybe making it easy for folks to list additional permissions they want on their standard SA that's being stored as a secret?
