### ISSUE TITLE
kfctl: remove ksonnet, move to v2

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3368]
We should remove all references to ksonnet and move to v2 for kfctl and bootstrap 

- [x] move kfctl code from under bootstrap to kubeflow/kfctl
- [x] kubeflow/kfctl/go.mod should now have module github.com/kubeflow/kubeflow/kfctl/v2
- [x] bootstrap go.mod should now have module github.com/kubeflow/kubeflow/bootstrap/v2
- [x] replace all references of github/kubeflow/kubeflow/bootstrap with either github/kubeflow/kubeflow/bootstrap/v2 or github/kubeflow/kubeflow/kfctl/v2
- [x] replace alls references to /tmp/v2 with kubernetes v1.13.4, client-go v10.0, kustomize v2.1.0 (#3497), controller-runtime v0.1.12 

background info:
there are  [2 alternatives](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) for v2 modules. We currently use ‘major subdirectory’ but will move to ‘major branch’. 

In order to load both ksonnet and kustomize in kfctl we implemented v2 modules for the following (v2.zip):
- k8s.io:
  - api@v1.13.4
  - apimachinery@v1.13.4
  - cli-runtime@v1.13.4
  - apiextensions-apiserver@v1.13.4
  - apiserver@v1.13.4
  - client-go@v10.0
- sigs.k8s.io
  - application@sha67ae7f915d4ea994e0805886928d9ec40e9526a2
  - controller-runtime@v0.1.12
  - kustomize@v2.0.3

Additional info is [here](https://research.swtch.com/vgo-module)

**Comment by jlewi** [comment]
Bump to P0 because the v2.zip code is causing problems.

To minimize churn; can we do a multi step process. In particular, can we get rid of the dependency on different versions of K8s libs without refactoring the directory structure in [kubeflow/bootstrap](https://github.com/kubeflow/kubeflow/tree/master/bootstrap)

My suggestion is as follows

1. Open several PRs to remove all imports of ksonnet

    * Open separate PRs for each module/package
    * e.g. one PR would remove the import in 
 https://github.com/kubeflow/kubeflow/blob/master/bootstrap/pkg/kfapp/ksonnet/ksonnet.go
    * Rather than simply deleting ksonnet.go which would require us to delete the caller code; we can just replace code in ksonnet.go with returning an error.
       * This is just a way of preventing PRs from becoming large and touching every file in the tree (painful for other people working on the code base)

1. Once we no longer depend on ksonnet can can we update go.mod so that the version of the library currently being referenced in kubeflow/bootstrap/pkg/ is now pointing to k8s 1.13? 
   * e.g in the [requires](https://github.com/kubeflow/kubeflow/blob/1211bd69730e2110d8c1df7b2b68c83b35870d77/bootstrap/go.mod#L106) section can we just change it to 

     ```
     k8s.io/api => k8s.io/api v0.0.0-20180601181742-8b7507fac302
     k8s.io/api/v2 => /tmp/v2/k8s.io/api
     ```

     * So that both versions point to the same, newer version of the library

1. Open up multiple PRs to replace V2 imports e.g. 'k8s.io/api/v2 -> k8s.io/api/v2'
1. Stop building /tmp/v2.zip since we no longer need it.

**Comment by jlewi** [comment]
@kkasravi Are you back? Any interest in picking this up?

**Comment by kkasravi** [comment]
Yes i’ll get this
/assign @kkasravi
