### ISSUE TITLE
update testing to use kustomize e2e tests

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3400]
testing assumes ksonnet and needs to allow for kustomize testing

**Comment by jlewi** [comment]
@kkasravi Can you clarify what this issue is about? Do you mean that the kfctl e2e tests need to deploy Kubeflow using kustomize? Or Do you mean that our E2E infrastructure is using ksonnet to describe our E2E workflows and that needs to be changed to kustomize?

**Comment by kkasravi** [comment]
[kubeflow/testing/test_deploy.py](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py) uses "ks" rather than kustomize to [init](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L123) a project, install packages, deploy a model using [tf-serving](https://github.com/kubeflow/kubeflow/blob/master/testing/test_deploy.py#L178), deploy katib, pytorch...

**Comment by ashahba** [comment]
I stated a PR here: https://github.com/kubeflow/testing/pull/405 for this story yesterday.
Although it started with renaming as of now and everything still runs with `ksonnet`.
It'll be sometime before everything is in place after the switch to `Kustomize` has been flipped.

Corresponding PRs are probably needed across other repos living under `https://github.com/kubeflow` in order to make this move happen across the board.

**Comment by jlewi** [comment]
Is this issue a duplicate of #2630?

We've been using #2630 to track adding an E2E test that uses kustomize + ISTIO.

@swiftdiaries has PR #3060 pending to update the E2E tests to use kustomize + ISTIO.

kubeflow/testing/test_deploy.py is no longer used.

@ashahba Can you clarify how kubeflow/testing#405 fits in?

**Comment by kkasravi** [comment]
@jlew closing this issue since it is a duplicate of #2630 
/close
