### ISSUE TITLE
Cannot connect to notebook: Error: "Sorry, /notebook/kubeflow/kfp-notebook is not a valid page"

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/kubeflow#3414]
I've deployed KFP 0.1.20 with IAP using web deployer.
I've created a notebook using the Kubeflow UI (default configuration and image).
When I click "Connect" I'm redirected to the  https://foo.endpoints.bar.cloud.goog/notebook/kubeflow/kfp-notebook page which shows "Sorry, /notebook/kubeflow/kfp-notebook is not a valid page".

![image](https://user-images.githubusercontent.com/1829149/58906122-1541fe00-86c0-11e9-9d3a-a9c956fbb720.png)

**Comment by jlewi** [comment]
@Ark-kun The URL looks correct. Is your notebook actually running; what does

What is the output of 

```
kubectl -n kubeflow get notebooks
```

**Comment by Edilmo** [comment]
I have the same issue. I have try with different names and also deleting the PVC generated before to retry.
The output of `kubectl -n kubeflow get notebooks` in my case is showing the list of running notebooks:
```
git:(master) kubectl -n kubeflow get notebooks
NAME      AGE
daniela   23d
edi       5h
hillary   25d
isabel    3d
lino      25d
miguel    22d
```

The kubernetes cluster is ok from a resource perspective and there is not pods with error or pending state.

Any advice?

**Comment by zabbasi** [comment]
Thanks @Edilmo . Can you please check the services in your cluster and check if you can connect to notebooks using port-forward (` kubectl port-forward `)?

**Comment by Edilmo** [comment]
Doing `kubectl port-forward -n kubeflow svc/edi 8888:80` the notebook is accessible through this URL: http://localhost:8888/notebook/kubeflow/edi/tree

Any other URLs like the followings are not working:
- http://localhost:8888/
- http://localhost:8888/tree
- http://localhost:8888/tree?
- http://localhost:8888/lab
-http://localhost:8888/edi/
- http://localhost:8888/edi/tree
- http://localhost:8888/edi/tree?

I don't know if that is relevant or not. 

Any other idea how to debug this?
Which component is in charge of the redirection?
Or is a problem at the ingress level?

FYI, the deployment was done using Istio. So the ingress is going through envoy.

**Comment by zabbasi** [comment]
@Edilmo have you deployed from master?
/cc @gabrielwen @lluunn

**Comment by jlewi** [comment]
Ambassador is the service used to provide the reverse proxy. 

Can you provide the output of

kubectl get service -o yaml edi

We'd like to see whether that has the proper YAML annotation for Ambassador.

Since your able to connect through the central dashboard to other pages like the notebooks spawner page that indicates Ambassador is correctly handling some routes.

What is the status of the Ambassador pods

```
kubectl get pods -l service=ambassador
```

Try forcing an ambassador pod restart by deleting the pods

```
kubectl delete pods -l service=ambassador
```
@Edilmo Is it just the new notebook that isn't accessible or is it old notebooks that aren't accessible?

**Comment by Edilmo** [comment]
> @Edilmo have you deployed from master?
> /cc @gabrielwen @lluunn

I followed the instructions [here - Deploy using CLI](https://www.kubeflow.org/docs/gke/deploy/deploy-cli). I'm not aware of what `kfctl init` command does.

**Comment by Edilmo** [comment]
Hi @jlewi 

All the previous notebooks are accessible, it's just the new ones.

Here the details:

```
mammut-deploy git:(master) kubectl get service -n kubeflow -o yaml edi 
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: notebook_kubeflow_edi_mapping
      prefix: /notebook/kubeflow/edi
      rewrite: /notebook/kubeflow/edi
      timeout_ms: 300000
      service: edi.kubeflow
      use_websocket: true
  creationTimestamp: 2019-06-06T17:05:21Z
  name: edi
  namespace: kubeflow
  ownerReferences:
  - apiVersion: kubeflow.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: edi
    uid: 44b0cb90-887d-11e9-baea-42010a8000e3
  resourceVersion: "13092041"
  selfLink: /api/v1/namespaces/kubeflow/services/edi
  uid: 44bab4d3-887d-11e9-baea-42010a8000e3
spec:
  clusterIP: 10.0.11.161
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    statefulset: edi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

```
mammut-deploy git:(master) kubectl get pods -n kubeflow -l service=ambassador
NAME                          READY     STATUS    RESTARTS   AGE
ambassador-7b8477f667-6pdnp   1/1       Running   0          27d
ambassador-7b8477f667-9vpz7   1/1       Running   0          27d
ambassador-7b8477f667-nk8bs   1/1       Running   0          27d
```

About restarting ambassador, how long could take that? (I don't want to affect the others guys working in this cluster)

Thanks in advance!!

**Comment by jlewi** [comment]
Can you upload the logs for the ambassador pods? Are you running on GCP? It would be good to grab the logs before you restart the pods.

What happens if you try to access the notebook directly and not through the central dashboard e.g.

```
https://${DOMAN}/notebook/kubeflow/ed1
```

Since the notebook is accessible through kubectl port-forward, I suspect a problem with Ambassador.

It looks like Ambassador may not be registering routes for the new notebooks. Ambassador works by watching for new services. So if it is having problem contacting the Master that could be the problem.

Can you check what routes are registered in Ambassador.

```
kubectl port-forward <AMBASSADOR POD> 8877:8877
http://localhost:8877/ambassador/v0/diag/
```
(ref [Ambassador docs](http://localhost:8877/ambassador/v0/diag/))

Do you see a route for the newer notebooks?

@Edilmo Restarting Ambassador should just take a couple seconds to restart. If you want to avoid disrupting initial workloads you could try deleting the Ambassador pods individually and waiting for each pod to restart before deleting the next one.


Here are the next steps I'd follow

1. Follow above instructions to access the debug UI for one of the Ambassador pods

    * Check if there is an entry for the new notebook and if so is it reported as healthy?

1. Fetch the logs for the associated pods
    
    * Upload them to the issue and look for any errors

1. Delete one of the Ambassador pods and wait for it to be restarted

1. Repeat the above steps to see if anything is different for the new Ambassador pod.

**Comment by travishen** [comment]
I has same issue. Recreate ambassador pods fixed it.

```

**Comment by jlewi** [comment]
@Edilmo @Ark-kun Does recreating the Ambassador pods fix it for you?

**Comment by Edilmo** [comment]
Hi @jlewi 

Answering your questions:

-  The new notebook was not accessible even if I try directly the link in the browser.
- Certainly the ambassador was not registering routes for the new notebooks, the "Ambassador Diagnostic Overview" page was not showing the route for the new notebooks.
- Recreating the Ambassador fix the problem!!!
- yes, I'm using a kubernetes cluster in GKE.

The logs of the 3 ambassador pods:
[ambassador-7b8477f667-6pdnp.csv.txt](https://github.com/kubeflow/kubeflow/files/3294669/ambassador-7b8477f667-6pdnp.csv.txt)
[ambassador-7b8477f667-9vpz7.csv.txt](https://github.com/kubeflow/kubeflow/files/3294670/ambassador-7b8477f667-9vpz7.csv.txt)
[ambassador-7b8477f667-nk8bs.csv.txt](https://github.com/kubeflow/kubeflow/files/3294671/ambassador-7b8477f667-nk8bs.csv.txt)

Sorry for the late response.
Let me know if I can help with something else.

**Comment by jlewi** [comment]
@Edilmo thanks. So it looks like the issue is with Envoy or Ambassador. It looks like the temporary work around is to restart the Ambassador pods.

0.6 will include updated versions of Envoy and ISTIO.  So I think the next step would be to wait for 0.6 to become available and then see if this problem reoccurs with ISTIO.

I will leave this issue open until we have a 0.6 release available.

#3559 is tracking 0.6

**Comment by Edilmo** [comment]
Thanks @jlewi for your help!!!

**Comment by jlewi** [comment]
0.6 is now available so I'm going to close this bug.

Please try 0.6 and open a new issue if the problem still occurs.

**Comment by Felihong** [comment]
Hi, I just encountered a similar problem using Kubeflow v0.6.2. It is deployed under this instruction https://www.kubeflow.org/docs/gke/deploy/deploy-cli/ on GCP and the default TensorFlow notebooks work fine. 

However, With a customised image (build with this Dockerfile: https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile) , there is a 404 error saying the requested page does not exist. 

I've updated the Entrypoint and specified the BASE_URL feature 
`ENTRYPOINT ["tini", "--"]` 
`ENV NB_PREFIX /notebook/kubeflow/test`
`CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]`

I've also tried port-forwarding, it doesn't work either.
Any thoughts?

**Comment by jlewi** [comment]
@Felihong looks like an issue with your Jupyter setup. If your port-forwarding to the notebook and jupyter and you are getting 404s then something not involving Kubeflow is going on.

You can compare against our latest Jupyter images which are based on the stock TensorFlow images.
https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile

**Comment by jlewi** [comment]
I'm closing this because the original issue was filed with KF 0.5 which is no longer supported.
