### ISSUE TITLE
kustomize should fail if it can't find a component in app.yaml

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/kubeflow#3426]
kustomize package-manager will do a best-effort in generating and deploying components. It should error out if the component can't be found

**Comment by yanniszark** [comment]
Thanks @kkasravi for opening this issue!
Giving a little more context on how this came up:

**What happened:**

* I used kfctl + kustomize to install Kubeflow. My KfDef included component `istio`.
* I deployed Kubeflow but I saw that Istio was not installed.
* Istio was not installed because it is in package gcp, a package I had not included in KfDef.

**What I expected to happen:**

* Istio should be installed since I specified it in components.
* If Istio (or any component) can't be installed (because it can't be found), `kfctl` should fail and not succeed.
