### ISSUE TITLE
multi-user UI for access management

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3437]
MVP:
each user can create / delete their reserved profile (managed namespace).

Ideally we should support 
1. namespace owner share / revoke access with other users 
2. provide admin page which can manage all namespaces access permissions.

**Comment by jlewi** [comment]
@kunmingg Is this about the UI implementation?

**Comment by jlewi** [comment]
/assign @avdaredevil 

Backend changes are in PR.
Front end not started yet.

ETA Wednesday for something working.

**Comment by jlewi** [comment]
@avdaredevil Any update on this?

**Comment by avdaredevil** [comment]
All components are done, all functionality implemented, tests **in**complete for the new components (older tests updated/fixed).

Presenting to abhishek and kunming today. Resolving a small issue with `createBinding`

**Comment by jlewi** [comment]
Reopening because it doesn't look like we've built images and updated the manifests.

**Comment by jlewi** [comment]
I see a bunch of PRs committed recently
#3503 
#3758 

Have we build updated images and updated the kustomize manifests to deploy them?
Is the new UI and changes being picked by our auto-deployed clusters.

**Comment by jlewi** [comment]
IIUC the multi-user UI is adding support for the following

1. Automatic creation of a profile when the user first accesses the UI
1. Filtering namespaces shown in the namespace selector to only show namespaces user has access to

Some users are reporting problems #3859 with not seeing any namespaces which may be related to the above functionality.

I think we want to test that everything is working in the following scenarios

1. GCP with IAP
1. No auth  using kfctl_k8s_istio.yaml [instructions](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/)
1. Basic Auth using dex [instructions](https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/)

**Comment by avdaredevil** [comment]
Re. points aforementioned

| 1. Automatic creation of a profile when the user first accesses the UI
Not exactly, there is a registration flow where a namespace name is presented to the user, they may keep or change then confirm. Now they're onboarded

| 2. Filtering namespaces shown in the namespace selector to only show namespaces user has access to
Yes, this is correct.

| Some users are reporting problems #3859 with not seeing any namespaces which may be related to the above functionality.
As mentioned in the issue, this is now introduced because now instead of querying all namespaces from Kubernetes, we rely exclusively on kfam / profile controller to get a list of bindings in non-iap (basic, unsecured) networks, then de-dupe and return a list of workgroups / namespaces. Their issue lies in the fact that kfam is not returning any bindings. (this was requested by @kunmingg and @abhi-g)

**Comment by yanniszark** [comment]
@avdaredevil 

> Not exactly, there is a registration flow where a namespace name is presented to the user, they may keep or change then confirm. Now they're onboarded

How can I access this flow? It isn't presented to me when I access the Central Dashboard.

> we rely exclusively on kfam / profile controller to get a list of bindings in non-iap

A binding to what user?
Do you assume a default user if none exists? (anonymous@kubeflow.org)

**Comment by yanniszark** [comment]
There is also a bug in the Central Dashboard code, see https://github.com/kubeflow/kubeflow/issues/3859#issuecomment-520940322

**Comment by avdaredevil** [comment]
@yanniszark This flow should only show in IAP / Authenticated Flows (non GCP as well, though you need to configure variables)
- User identity is extracted via [these environment variables](https://github.com/kubeflow/kubeflow/blob/7c0932a117f2f2dc232271992d0348c4747021eb/components/centraldashboard/app/server.ts#L23-L24)

In basic/unsecured modes:
- We query all Workgroup Bindings for all users
- Nope we don't expect anonymous@kubeflow.org to have bindings, though that is the identity we use

**Comment by deepdad** [comment]
https://github.com/kubeflow/kubeflow/issues/3901#issuecomment-521200663
The namespaces issue is now gone with this setup.

**Comment by jlewi** [comment]
This should now be available in the v0.6-branch
See: http://bit.ly/2ZgOE1v.

So I'm going to close this. 
#3860 is tracking v0.6.2
