### ISSUE TITLE
jupyter resource limits？

### ISSUE THREAD

**Issue by Jonuknownothingsnow** [kubeflow/kubeflow#3467]
We could specify the total amount of resource(CPU/mem) that should reserve when create a notebook server, but can I limit the maximum resources the notebook server use? haven't figure out how to do this

**Comment by abbyearnin** [comment]
+1

Looking at the StatefulSet for my Jupyter Server created using KubeFlow, I noticed that Resource Requests were configured, but there were no Resource Limits.

**Comment by abbyearnin** [comment]
@Jonuknownothingsnow I figured it out, you can specify limits on your server by filling in the Extra Resources (the name is very misleading, in fact it is the resources to limit).

For example, enter in the value
` {"cpu": "500m","memory": "1Gi"}`
as an Extra Resource in order to limit your server cpu and memory.

**Comment by Jonuknownothingsnow** [comment]
@abbyearnin tks, I guess maybe I should just use jupyterhub on kubernetes and wait the kubeflow 1.0 comeout 🤔
