### ISSUE TITLE
kfctl E2E test deploying on existing kubernetes cluster; simulated on prem cluster

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3496]
We need an E2E test for deploying on an existing Kubernetes cluster.

There's a couple ways we could do this

1. We could use minikf
1. We could use GKE to simulate an existing kubernetes cluster

**Comment by jlewi** [comment]
Might be good to use a tool like kops or kubeadm to setup a conformant K8s cluster on GCP and use that as our test bed.

**Comment by jlewi** [comment]
Lets use this issue to track an E2E test for 
https://github.com/kubeflow/kubeflow/blob/master/bootstrap/config/kfctl_k8s_istio.yaml

**Comment by krishnadurai** [comment]
@jlewi Sure we'll set up tests with the above config

**Comment by nrchakradhar** [comment]
@krishnadurai 
I remember a PR from @swiftdiaries for using KinD (Kubernetes in Docker) for kubeflow e2e test. It could be a first step towards this testing. Its now possible to have KinD run in Kubernetes also as per [seldon comment](https://github.com/kubernetes-sigs/kind/issues/303#issuecomment-546705931)

Do we consider this or are there better choices?

**Comment by krishnadurai** [comment]
@nrchakradhar the PR which you are mentioning is #4237. 

@swiftdiaries could you please provide the context around KinD and how we can go on to introduce it?

**Comment by jlewi** [comment]
Wouldn't using a tool like

* [kops](https://github.com/kubernetes/kops)
* [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/)
* [kubespray](https://github.com/kubernetes-sigs/kubespray)

Be a better tool than KinD for simulating and testing an on prem cluster? IIUC KinD is targeting a local (single machine) environment. 

With tools like kops I would expect we can use Cloud VM's to setup a simulated on prem deployment.

**Comment by swiftdiaries** [comment]
KinD is specifically for CI environments and ephemeral (so it doesn't add to frequent resource quota out  of bound errors that break Prow). The problem with using `gcloud` or `kops` or `kubeadm` is that it creates resources external to the workflow. Istio uses `KinD` a lot and `kubeadm` uses `KinD` to test `kubeadm` 
I am working on a GitHub action to test `kfctl` to remove the dependency with Prow and enable developers to speed up their dev cycles by using their own PR branch for iterating.
https://github.com/swiftdiaries/kind-kfctl-github-actions/
It builds on an existing GitHub action that installs `KinD`: https://github.com/engineerd/setup-kind
It just seems cleaner and hopefully improve developer productivity by using GitHub Actions

**Comment by jlewi** [comment]
@swiftdiaries Can I suggest putting together a short doc describing what you are doing? Specifically about replacing prow with GitHub actions.  Can you open up another issue to discuss since I think replacing prow with a GitHub action is unrelated to this issue?

@swiftdiaries You raise a good point about quota. If we use Kind

* Are the logs emitted in some sensible fashion? i.e. if you have an entire Kubernetes cluster running in a single pod and everything is emitting logs to standout/stderr how do we begin to make sense of that?
* Are we going to have problems when we reach the point where Kubeflow as a whole no longer fits into a single machine and we are trying to do E2E testing?
* Is Kind going to give us enough flexibility to test out various E2E scenarios?

   * E.g. suppose we want to test the latest Kubernetes version, with a different type of networking overlay, and enable certain Kubernetes APIServer options like OIDC; will we be able to do that with Kind?

I might suggest splitting these into separate issues

1. One issue for setting up a test bed to mimic on prem clusters with different settings
1. A separate issue for improving developer velocity and simplifying testing

**Comment by marcindulak** [comment]
@jlewi

The issue got stale, but I'll try to answer your questions

1. A kind cluster consists of docker containers as k8s master and worker nodes. Logs are emitted in a standard way (accessible with kubectl log, etc)
2. The largest VMs available on today's clouds have hundreds of vCPUs and dozens of GB of RAM per vCPU. I'm still fitting kubeflow on a laptop with 4 cores and 32 GB of RAM.
3. Kind node docker images are regularly maintained https://hub.docker.com/r/kindest/node/tags. Kind has been used to demonstrate various CNIs and overlay networks https://github.com/mauilion/kind-cni-playground, and has a limited IPv6 support https://kind.sigs.k8s.io/docs/user/configuration/. It is possible to pass kube-apiserver flags on the kind cluster creation https://kind.sigs.k8s.io/docs/user/quick-start/#enable-feature-gates-in-your-cluster, and someone on the http://slack.k8s.io/ #kind channel claimed OIDC setup in kind in the past.

I guess the point of having a github action was to have a simple e2e test that sets up a kind cluster, installs kubeflow, and runs e.g. `jupyter nbconvert --execute --clear-output mnist_vanilla_k8s.ipynb` https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb. An action like this may run for 30 minutes, be flaky (but much faster and less flaky than kubeadm, kops or kubespray, since with kind the "installation" of k8s is already taken care of), but could possibly help to keep kubeflow in an installable state and the demo notebook runnable https://github.com/kubeflow/examples/issues/725
