### ISSUE TITLE
why my kubeflow cannot create new Volumes, use only existing ones？？

### ISSUE THREAD

**Issue by JK-97** [kubeflow/kubeflow#3612]
![image](https://user-images.githubusercontent.com/16853338/60757874-d696bf00-a042-11e9-8c0c-b1da24c4c59f.png)
![image](https://user-images.githubusercontent.com/16853338/60757885-f0380680-a042-11e9-8662-0417d3e72343.png)

as the image,i can not create a new,but can use a existing one. 
so i have to use:
kubectl create -f some-pvc.yaml
kubectl create -f some-pv.yaml
to create a new.

and then new a note book server to bind with it. Only then can it be created normally

**Comment by kimwnasptd** [comment]
@JK-97 this is because there not a default Storage Class in the cluster. If the webapp doesn't find a default StorageClass it will not let the user to create a new Notebook.

In the new iteration of the UI there is a more informative message regarding this behavior, plus the ability to select another StorageClass through the webapp's `config.yaml`.

**Comment by jlewi** [comment]
@JK-97 You could also create new volumes using kubectl and then the should show up in the UI.
