### ISSUE TITLE
kfctl without platform not working

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3626]
```
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate k8s -V
```
This will give error:
`ERRO[0000] Couldn't find component istio-crds filename="kustomize/kustomize.go:454"`

After removed the istio components from app.yaml, the generate succeeds.
But apply failed with:
```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from /Users/lunkai/kfdev/kops-test/kf0708/kustomize/minio.yaml Error: persistentvolumes "minio-pv" is forbidden: error querying GCE PD volume dls-kf-storage-artifact-store: disk is not found
```

See #3618 3618

**Comment by lluunn** [comment]
remove minio and mysql from components, the apply succeeded.

**Comment by yanniszark** [comment]
Hi @lluunn, I'd like to say that I bumped into very similar problems while writing the `existing_arrikto` config file, which is tailored towards running on existing kubernetes clusters.
For example, I changed minio and mysql to use a default storage class.

Because of that, I propose using the `existing_arrikto` config file, with the following procedure:

```bash
# Apply Istio
kubectl apply -f deployment/existing/istio
# Deploy for existing K8s
kfctl init --config=bootstrap/config/kfctl_existing_arrikto.0.6.yaml
kfctl generate k8s
kfctl apply k8s
```

**Comment by jlewi** [comment]
@yanniszark see my comments in in #3627 about the use cases I think we want to support.

**Comment by vjrantal** [comment]
I tested the config `kfctl_k8s_istio.yaml` from the master branch (commit d0c11dd67ebd514f4d6e584b74fecf880245a86c) on my Kubernetes cluster with these steps:

```
kfctl init ${KFAPP} --config=bootstrap/config/kfctl_k8s_istio.yaml -V
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V
```

The deployment succeeded, all pods seemed to be running fine and I was able to access the dashboard. However, creation of new notebook servers got stuck to a state that to the end user looks like this:

<img width="1188" alt="Screenshot 2019-07-17 at 14 35 54" src="https://user-images.githubusercontent.com/207474/61372600-4ce7bc80-a8a0-11e9-8d66-55b9a37b3aac.png">

@lluunn I was curious if you tested notebook server creation as part of fixing this issue? If yes and if that is tested to work with latest master branch, I'll keep debugging my setup.

As further information, I had istio injection enabled for the used namespace:

```
$ kubectl get ns --show-labels | grep kubeflow
kubeflow       Active   4h52m   istio-injection=enabled
```

In the notebook-controller-deployment logs I can see something like this:

```
$ kubectl logs notebook-controller-deployment-66b548f989-9ckjz -n kubeflow
...
{"level":"info","ts":1563346365.466873,"logger":"controller","msg":"Creating Service","namespace":"kubeflow","name":"nbserver"}
{"level":"info","ts":1563346365.536583,"logger":"controller","msg":"Creating virtual service","namespace":"kubeflow","name":"notebook-kubeflow-nbserver"}
{"level":"info","ts":1563346365.647643,"logger":"controller","msg":"Pod not found..."}
{"level":"info","ts":1563346365.6479487,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"nbserver"}
{"level":"info","ts":1563346365.6991074,"logger":"controller","msg":"Pod not found..."}
{"level":"info","ts":1563346365.6993618,"logger":"controller","msg":"Updating StatefulSet","namespace":"kubeflow","name":"nbserver"}
{"level":"info","ts":1563346365.7126508,"logger":"controller","msg":"Pod not found..."}
...
```

However, after that, I can't seem to find any logs that would indicate what the root cause is.

**Comment by vjrantal** [comment]
@lluunn I think I found the problem now:

```
create Pod nbserver-0 in StatefulSet nbserver failed error: pods "nbserver-0" is forbidden: error looking up service account kubeflow/default-editor: serviceaccount "default-editor" not found
```

Those seem to be set in file `components/profile-controller/pkg/controller/profile/profile_controller.go`. I wonder should that be executed with the `kfctl_k8s_istio` config?

**Comment by lluunn** [comment]
Please see this issue: https://github.com/kubeflow/kubeflow/issues/3639

**Comment by Jeffwan** [comment]
`minio` and `mysql` comes from kustomize overlay. Ideally, it should use PVC and default storage class. Any reason it use a separate PV there?
