### ISSUE TITLE
Update docs_dev/tf_serving.md to reflect current status (as of 0.6)

### ISSUE THREAD

**Issue by carmine** [kubeflow/kubeflow#3629]
I was reviewing docs_dev/tf_serving.md and noticed it is out of date wrt to current work. Most of the issues in next steps are completed.

**Comment by jlewi** [comment]
@carmine do you know if this got fixed as part of doc sprint?

**Comment by sarahmaddox** [comment]
@jlewi AFAICT no-one worked on this issue during the doc sprint.

The file referred to in this issue hasn't been updated since October last year:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/tf_serving.md

The docs on the website are here:
https://www.kubeflow.org/docs/components/serving/
https://www.kubeflow.org/docs/components/serving/tfserving_new/

There were no doc sprint PRs that addressed the tfserving doc, apart from reorg of the site structure.

**Comment by jbottum** [comment]
@carmine @sarahmaddox since we are moving to kfserving, i think that most of our efforts will be focused there.   I do believe that the tfserving docs should be up to date but in a priority call, I think that we will see more focus on kfserving.    Can we close this issue or define a path to close it ?

**Comment by sarahmaddox** [comment]
Hallo @jbottum My focus is on the website docs (https://www.kubeflow.org/docs/components/serving/tfserving_new/) which we do need to keep up to date for Kubeflow users.

For the doc on GitHub (https://github.com/kubeflow/kubeflow/blob/master/docs_dev/tf_serving.md) I'd recommend that we remove all user-focused content and link to the website docs instead. The GitHub README can then contain contributor-focused content only. That content should be correct (that is, not misleading). If it's currently misleading, then it's better to remove it if there's no bandwidth to update it.
