### ISSUE TITLE
notebook controller v1beta1

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#3655]
Notebook controller should go v1beta1 in 0.7

#3656 is tracking everything we need for 1.0

~~We should figure out the required features and file separate issues for them (see #3654)~~

Some things that come to mind

* Prometheus monitoring
* Support for multiple versions

**Comment by jlewi** [comment]
See #3654 and go/tf-operator-1-0 for guidance.

**Comment by lluunn** [comment]
> - Support for multiple versions

What does version here mean?

**Comment by jlewi** [comment]
Version means multiple versions of the custom resource e.g. Notebook v1beta1 and Notebook V1.

**Comment by jlewi** [comment]
Are there any changes to Notebook spec and status that we should make?

Here are some questions we have

1. What support do we have for letting users set annotations and labels on the statefulset and pods created by the notebook controller?
1. Do we support letting users add init containers and sidecars?
1. #3772 do we need to surface more information about errors?

**Comment by kimwnasptd** [comment]
@jlewi regarding more Pod configurations (init containers, sidecars, annotations, labels etc) we will not need to modify the Notebook Spec. The spec already has a `PodTemplateSpec` field, so we could add any extra functionality by exposing these options from the UI.

But for setting annotations/labels to the StatefulSet, we would need to add some fields in the Notebook Spec to specify those.

So regarding the questions:
1. We will need change the API if we want to allow the user to set annotations/labels to the StatefulSet. No changes in the API need to be made for more configurations to the Pods
2. Yes, the current API supports adding init/sidecar containers. We need to expose these options to the UI
3. #3772 will surface the information as [NotebookConditions](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go#L48), which are already part of the API. We might need to extend the API in order to better handle the [ContainerState](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/pkg/apis/notebook/v1alpha1/notebook_types.go#L45) field. Right now we expose only one container, but we should expose information about all the containers in the underlying Pod, in order to accurately show the Status of the Notebook (#3820)

**Comment by lluunn** [comment]
What's the use case that users need to set annotation/label on the statefulset?

Should the UI just expose the whole podspec? e.g. in a advanced mode view or something.

**Comment by jlewi** [comment]
Thanks. I think a use case for setting annotations/labels would be to use PodDefaults to inject init containers; see #2889 

@kimwnasptd Regarding annotations and labels; I'm wondering if we should just take the Notebooks labels and annotations and apply them directly to the statefulset and pod. Or if we should allow users to set those independently of the Notebook's labels and annotations.

**Comment by jlewi** [comment]
I created #3940 to update the CRD definition. I think we should try to do that this week. I think if we simultaneously serve v1alpha1 and v1beta1 then it should be easier to begin making changes to support v1beta1 without breaking things.

**Comment by lluunn** [comment]
I am investigating how to support multiple versions.

According to the kubebuilder book: https://book.kubebuilder.io/multiversion-tutorial/tutorial.html
Sample [here](https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/multiversion-tutorial/testdata/project)
We can do the following IIUC:
1.  `cp -r api/v1alpha1 api/v1beta1`, and make changes in v1beta1.
1.  choose the "stored", or the "Hub" version. I think we will choose v1beta1.
1. define the webhook for conversion between alpha and beta.
1. The controller should watch the Hub version (v1beta1 for us)

However, the pattern in tf-operator seems different. There are two controller (controller.v1, controller.v1beta2) each watches the corresponding version of tfjob.
Also @richardsliu mentioned Ttjob still supports both v1 and v1beta, but I can't find a webhook for conversion. And it looks like we deploy only one controller: https://github.com/kubeflow/manifests/blob/master/tf-training/tf-job-operator/base/deployment.yaml

Still trying to figure out:
- how does tfjob support both v1 and v1beta1
- which pattern should we follow

cc @jlewi

**Comment by jlewi** [comment]
@lluunn I think TFJob predates multi version support so its likely doing something different.

**Comment by jlewi** [comment]
@lluunn Any update on this?

Bump to P0 because it must land in 0.7.

**Comment by richardsliu** [comment]
@lluunn Is this done?

**Comment by lluunn** [comment]
some updates here: https://github.com/kubeflow/kubeflow/issues/3940#issuecomment-533684229

This is somewhat dup with #3940

**Comment by jlewi** [comment]
@lluunn what is the remaining work here?

Looking at 
https://github.com/kubeflow/manifests/blob/756d25501b912768aabd234365f4b8cb6c9439aa/jupyter/notebook-controller/base/deployment.yaml#L10

Looks like we need to
* build a new docker image
* update the manifests in kubeflow/manifests

**Comment by jlewi** [comment]
I built a new image.
gcr.io/kubeflow-images-public/notebook-controller:v20191007-v0.6.0-rc.0-134-g6ddf28cc-dirty-560d95

And sent out PR kubeflow/manifests#443

**Comment by lluunn** [comment]
I updated once: https://github.com/kubeflow/manifests/blob/master/jupyter/notebook-controller/base/kustomization.yaml#L18

**Comment by richardsliu** [comment]
@lluunn @jlewi Can we close this?

**Comment by jlewi** [comment]
@richardsliu We can close once kubeflow/manfests#443 is merged.

**Comment by jlewi** [comment]
kubeflow/manifests#443 has been merged.
