### ISSUE TITLE
.6 RC1 onto freshly-installed K8S cluster fails

### ISSUE THREAD

**Issue by JavaDerek** [kubeflow/kubeflow#3689]
I installed a Kubernetes master and node from scratch yesterday on Ubuntu 18.04.  Today I tried installing the RC 1 release of 0.6 that just came out 6 hours ago.  I built kfctl from source off the 0.6 rc1 tag and attempted to install, all following the instructions at https://www.kubeflow.org/docs/started/getting-started-k8s/#Kubeflow-for-Existing-Clusters---by-Arrikto.  It blew up with the attached errors on the "kfctl apply all -V" command.

[kfctlBlowsUp.txt](https://github.com/kubeflow/kubeflow/files/3404522/kfctlBlowsUp.txt)

Kubernetes version  information is below...

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yanniszark** [comment]
Hi @JavaDerek.
Currently, you need access to a LoadBalancer Service in order to use platform=existing_arrikto.
It seems that you don't have access to that in your cluster and kfctl blows up trying to get the LoadBalancer Service:

```
Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: coordinator Apply failed for existing_arrikto:  (kubeflow.error): Code 500 with message: timed out while waiting to get istio-ingressgateway Service ExternalIP
```

Soon, there will be instructions to bypass this restriction.
If you want to try existing_arrikto, you can test with a GKE cluster using the script provided in the docs.

**Comment by JavaDerek** [comment]
Fair enough.  I'll try that.  In the meantime, do you want me to do a pull request to add the above caveat to the install doc page, or do you want to leave it as-is until you have the workaround instructions?

**Comment by yanniszark** [comment]
@JavaDerek the need for a LoadBalancer is clearly stated inside the docs:
https://www.kubeflow.org/docs/started/getting-started-k8s/#prerequisites

**Comment by jlewi** [comment]
@JavaDerek @yanniszark can we close this issue?

**Comment by jlewi** [comment]
kubeflow/website#977
Preview 
https://deploy-preview-977--competent-brattain-de2d6d.netlify.com/docs/started/getting-started-k8s/

Documents how you can install on an existing cluster without needing a loadbalancer.

I'm going to go ahead and close this because it looks like the issue has been addressed.
