### ISSUE TITLE
ClusterRole's and ClusterRoleBindings should include namespace in the name

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#374]
See #373 

ClusterRole's and ClusterRoleBinding's aren't namespaced scoped. So if we try to create multiple Kubeflow deployments in different namespaces they can interfere.

ClusterRoleBinding's are the bigger problem because we create namespace scoped service accounts, so the bindings for the different deployments are different.

If we include the namespace name in the ClusterRoleBinding this would make the names unique and allow us to better support multiple deployments.

**Comment by zjj2wry** [comment]
serviceaccount is an array. when there are multiple serviceaccount  in clusterrolebindding, we do not know which partition to use.

**Comment by jlewi** [comment]
What I'm suggesting is that we create 1 clusterrolebinding per Kubeflow deployment and make the name unique so that if we have multiple Kubeflow deployments running in different namespaces there is still 1 clusterrolebinding per Kubeflow deployment.

**Comment by zjj2wry** [comment]
kubectl create clusterrole ambassador
kubectl create  clusterrolebinding ambassador --clusterrole=ambassador --sa={ns-1}:ambassador --sa={ns-2}:ambassador
kubectl create rolebinding {ns-1}-ambassador --clusterrole=ambassador --sa={ns-1}:ambassador
kubectl create rolebinding {ns-2}-ambassador --clusterrole=ambassador --sa={ns-2}:ambassador

I think using rolebinding here may be a good approach, because clusterrolebinding is also a cluster-wide resource.
 ```kubectl get rolebinding --all-namespaces | grep ambassador```

**Comment by ankushagarwal** [comment]
I tried using role bindings for ambassador, but it doesn't seem to work because by default ambassador tries to watch for services at the cluster level instead of the namespace level. When we use role binding, we can only give ambassador permissions within a single namespace and that fails.

So we might have to go with @jlewi 's proposal and create a separate clusterolebinding per deployment. eg: `ns1-ambassador`,`ns2-ambassador` where ns1 and ns2 are two kubeflow deployments on the same cluster

**Comment by ankushagarwal** [comment]
Please take a look at https://github.com/kubeflow/kubeflow/pull/408
