### ISSUE TITLE
deploy app frontend: Unhandled Rejection (TypeError): Cannot read property 'cert-manager' of undefined

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#3753]
Got following error when testing on v0.6.0 of new deploy UI.

```
Unhandled Rejection (TypeError): Cannot read property 'cert-manager' of undefined
DeployForm.<anonymous>
src/DeployForm.tsx:379
  376 | 
  377 | // Make copy of this._configSpec before conditional changes.
  378 | const configSpec = JSON.parse(JSON.stringify(this._configSpec));
> 379 | configSpec.defaultApp.componentParams['cert-manager'][0].value = email;
  380 | for (let i = 0, len = configSpec.defaultApp.componentParams['iap-ingress'].length; i < len; i++) {
  381 |   const p = configSpec.defaultApp.componentParams['iap-ingress'][i];
  382 |   if (p.name === 'ipName') {
```

**Comment by kunmingg** [comment]
@prodonjs 
@gabrielwen

**Comment by prodonjs** [comment]
@kunmingg - Did you get this issue from the state in #3599? I expected there were still some issues there but I thought I had seen this one before and addressed it. In any case, can you point me to the 0.6.0 compatible bootstrap endpoint you have so I can test against it?

**Comment by prodonjs** [comment]
Ahh looking at this again I was basing some assumptions on what the old 0.5.0 config file looked like from `app-config.yaml` on master which had already been updated from what's on the v0.5.0 branch. I'm making the appropriate changes now and they'll be in the PR.

**Comment by prodonjs** [comment]
OK, I'm still a bit confused here. I started basing the work to provide valid paths for both v0.5.0 and v0.6.0 deployments from master, where the last change to the click-to-deploy code came from #3045.

However, if I try to use that code and make a request against the existing deploy.kubeflow.cloud endpoint I see `json: cannot unmarshal string into Go struct field AppConfig.packages of type v1alpha1.KsPackage` in the 500 response. That makes sense given that the old deployment service wouldn't understand the new format.

However, in order to support both v0.5.0 and v0.6.0 deployments from the same deployment, do I need to also make sure the code that was in place for C2D in the v0.5.0 branch is incorporated as well, or can the new deployment service handle both simple by indicated the `KfVersion` in the request payload?

**Comment by jlewi** [comment]
@kunmingg Is this fixed? It looks like deploy.kubeflow.cloud supports deploying v0.6 so I'm guessing this has been fixed.
