### ISSUE TITLE
Is build version displayed by Kubeflow on dashboard correct ?

### ISSUE THREAD

**Issue by mmuppidi** [kubeflow/kubeflow#3765]
I just upgraded my Kubeflow to v0.6.1-rc.1, but the dashboard still displays build version 0.5.0. Is there a bug here or did my upgrade not work ?

Here is the command I used to upgrade 

```
${KUBEFLOW_SRC}/scripts/upgrade_kfp.sh 85284312a5c472ccbf9700de4e3ede99b9eb8b51
```

<img width="255" alt="kubeflow-build-version" src="https://user-images.githubusercontent.com/8787305/61979773-caa77880-afc2-11e9-82dc-e4e54ab3297a.png">

**Comment by Bobgy** [comment]
Answering because I just happen to know this.

Hi @mmuppidi, as stated by the script's name `upgrade_kfp.sh` (kfp for kubeflow pipelines), it upgrades only kubeflow pipeline. It doesn't upgrade kubeflow to 0.6. You can find related doc in: https://v0-5.kubeflow.org/docs/pipelines/upgrade/

Upgrade instructions are outdated (no longer work), depending on your needs, you can follow "reinstall kubeflow pipelines" instructions https://master.kubeflow.org/docs/pipelines/upgrade/ to keep existing pipeline data.

**Comment by abhi-g** [comment]
The rc that you deployed from didn't have updated Central Dashboard and hence the wrong version. That said  there is a bug in the version identification and I have filed #3875 for that.
