### ISSUE TITLE
[Discussion] ETL/Data engineering in kubeflow

### ISSUE THREAD

**Issue by bmenn** [kubeflow/kubeflow#382]
What is the vision/roadmap with kubeflow interacting with workflow tools such as Spotify Luigi or Apache Airflow to build machine learning pipelines? Would workflow engines just be another service that kubeflow users would interact with on the kubernetes cluster or something a little more integrated like building Docker containers or serving trained model?

I apologize if this is mentioned somewhere and I missed it.

**Comment by jlewi** [comment]
For ETL, I highly recommend taking a look at [Argo](https://applatix.com/open-source/argo/). We already include a package for deploying Argo as part of Kubeflow and various folks are contributing examples that use Argo for pipelines. (We already use it for CI/CD).

That said the Airflow and K8s community are investing in Airflow and there's no reason why you couldn't deploy Airflow on K8s either as part of Kubeflow or independent of Kubeflow and use Airflow for ETL.

/cc @vicaire

**Comment by bmenn** [comment]
Looking at Argo briefly, it seems well suited for CI/CD but not quite for the type of ML workflows I am looking to run (most of them are quite dynamic), though Argo seems handy for quick prototyping of ML workflows.

I'll follow up with the Airflow community about integration with kubernetes. In the meantime, I'll just deploy Airflow as another service on the cluster.

Thanks for your suggestions. Feel free to close if you want.

**Comment by aronchick** [comment]
Thanks for the feedback! Are there any specific scenarios you can share
that detail why argo is not a fit? We'd love to get smarter about this!

**Comment by bmenn** [comment]
I'll try to put together a contrived example that can demonstrate the what I'm hoping for. It might be a week or so before I get to it though. I'm in the process of building out a new ML platform/pipeline and need something that works sooner rather than later. Really like the direction kubeflow is going, so I'll try to contribute where I can.

I think Argo technically can be made to work given the workflow spec options of loops and conditional execution, but it seems like it might not be intuitive when dealing with hyperparameter searches and warm-start/resuming from checkpoints for model training (creating that example might change my mind as well).

**Comment by aronchick** [comment]
No worries at all! Just love to hear how we can be better :)

**Comment by bhack** [comment]
See also https://github.com/kubeflow/kubeflow/issues/136

**Comment by bmenn** [comment]
@bhack 

I'm keeping on eye on that issue as well. I'll report back over there if I come across anything interesting regarding model management/tracking. Need to build something out for that as well.

**Comment by bmenn** [comment]
@elsonrodriguez 

Would you mind if I extend your work in kubeflow/examples#42 to include an Airflow/Luigi option to provide a little more detail to the discussion here?

**Comment by inc0** [comment]
There is also that https://github.com/kubeflow/kubeflow/issues/151

**Comment by jlewi** [comment]
@bmenn before you integrate Airflow in @elsonrodriguez could you please explain the value you think it adds?

We originally used Airflow in Kubeflow precisely because we thought we'd want to use it for ML pipelines. But operationally I found Airflow to be really difficult compared to Argo. 

So in the context of the example I wouldn't want to include Airflow unless it was clearly doing something that Argo can't do.

**Comment by bmenn** [comment]
@jlewi 

I haven't used Argo yet (will be using @elsonrodriguez's example to learn what it can do), but operationally Argo definitely looks easier to get started than Airflow.

My thought of extending @elsonrodriguez's example was just so others can see what a similar workflow would look like using Airflow on Kubeflow. I would be fine creating a separate standalone example as well (potentially borrowing somethings from the existing example).

Or is your concern that there would be confusion with two examples doing the same thing with different stacks?

**Comment by jlewi** [comment]
Maintaining examples is expensive. So I'd like to minimize redundant solutions.

In this case, its not immediately clear to me what an Airflow + Kubeflow example would be highlighting. I think this is generally useful; but I'm not sure it belongs in Kubeflow at this time.

An Argo workflow is just orchestrating containers. So translating it into Airflow should be straightforward. Especially since there is the [AIrflow on K8s project](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=71013666).

  - In particular I think people who know and love Airflow won't have a problem translating it into Airflow

So to your second point; I'm trying to rally the Kubeflow community behind a couple good examples and core components and avoid unnecessary fragmentation. 

When it comes to a DAG workflow scheduler we already have a lot of momentum with Argo 

  - We use it for CI/CD
  - Its K8s native
  - We have ksonnet packages for deploying it
  - Multiple examples have started using it.

So IMO I'd rather build on that momentum. 

For example, rather than redo Argo workflows in Airflow; I'd like to see us combine Argo with cron to regularly train models for our GitHub issue summarization example kubeflow/examples#40.

This allows us to build an even more complete E2E solution demoing how you build beautiful ML products which I think gets people excited.
