### ISSUE TITLE
Remove Ambassador annotations

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/kubeflow#3833]
/kind feature

**Why you need this feature:**
Since KF v0.6.0, we have istio and ambassador is no longer needed. But the sub UIs of central dashboard still need Ambassador annotations to forward requests. See https://github.com/kubeflow/kubeflow/issues/3828

**Describe the solution you'd like:**
Get rid of ambassador annotations and make sure the UI work.

**Comment by jlewi** [comment]
The ambassador annotations should no longer be needed because we no longer use Ambassador. In the case of IAP we shouldn't even be installing Ambassador which means the Ambassador annotations should be harmless metadata.

I suspect what's happening is that in the case of basic auth we are still installing Ambassador and using it for external auth.

So in the basic auth setting we end up trying to route things via Ambassador and not via ISTIO and that causes problems.

Two potential solutions

1. Remove Ambassador annotations
1. Switch to using Dex for basic auth

We should probably do 2 eventually.

**Comment by jlewi** [comment]
It looks like @kunmingg fixed this in kubeflow/manifests#257 

It looks like the solution was to add an Ambassador annotation to forward all ambassador traffic to the ISTIO gateway.
https://github.com/kubeflow/manifests/blob/master/gcp/basic-auth-ingress/base/istio-mapping-svc.yaml

So I think that is the Ambassador annotation we will eventually want to clean up.

To enable that I think we'd want to stop using Ambassador for basic auth. Which probably means replacing it with Dex.
