### ISSUE TITLE
Kubeflow version displayed on the UI is wrong

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#3875]
/kind bug

**What steps did you take and what happened:**
Deploy Kubeflow from v0.6 branch

**What did you expect to happen:**
I expected the Central Dashboard UI to show Kubeflow Version as 0.6.x, instead it shows v1beta1

**Anything else you would like to add:**

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): Should be v0.6.0 

<img width="1424" alt="Screen Shot 2019-08-12 at 3 04 44 PM" src="https://user-images.githubusercontent.com/11774566/62901866-bb3e6400-bd12-11e9-92fe-06b43ca79ca7.png">

**Comment by abhi-g** [comment]
Central dashboard [version discovery](https://github.com/kubeflow/kubeflow/blob/b0315cb4e95af11eb40257d7d97e294a04678ca4/componnts/centraldashboard/app/k8s_service.ts#L137) code is retrieving this value from some K8s application. Seems like there is a miscommunication or misalignment on the version information. 

/assign @avdaredevil @jlewi

**Comment by jlewi** [comment]
@avdaredevil Has this already been fixed in the image in kubeflow/manifests on v0.6-branch?

**Comment by avdaredevil** [comment]
@kunmingg has this been resolved??

**Comment by jlewi** [comment]
I'm seeing v1beta in the central dashboard when I deployed using the latest kfctl branch and the latest central dashboard image. I think there are two problems

@avdaredevil The centraldashboard code doesn't look correct to me.
https://github.com/kubeflow/kubeflow/blob/b0315cb4e95af11eb40257d7d97e294a04678ca4/components/centraldashboard/app/k8s_service.ts#L137

It looks like it is listing applications and returning the version specified in the first application it finds.

We should be looking for the application named kubeflow (we can issue a get for it rather than listing all applications). (see kubectl command and output below).

The second problem looks like the version set in the application resource is not correct. It looks like we are currently setting the version to v1beta1. We need to fix that.

This needs to be fixed in the manifest
https://github.com/kubeflow/manifests/blob/eab125dd42c08b0e2495b7b2d7a7010ac64d3774/application/application/overlays/application/application.yaml#L16

e.g

```
kubectl -n kubeflow get applications kubeflow -o yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  creationTimestamp: 2019-08-21T13:17:51Z
  generation: 1
  labels:
    app.kubernetes.io/component: kubeflow
    app.kubernetes.io/instance: kubeflow
    app.kubernetes.io/managed-by: kfctl
    app.kubernetes.io/name: kubeflow
    app.kubernetes.io/part-of: kubeflow
    app.kubernetes.io/version: v0.6
  name: kubeflow
  namespace: kubeflow
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: false
    kind: Application
    name: kubeflow
    uid: 13e849fc-c416-11e9-a068-42010a8e006a
  resourceVersion: "10889"
  selfLink: /apis/app.k8s.io/v1beta1/namespaces/kubeflow/applications/kubeflow
  uid: 13e849fc-c416-11e9-a068-42010a8e006a
spec:
  addOwnerRef: true
  componentKinds:
  - group: app.k8s.io
    kind: Application
  descriptor:
    description: application that aggregates all kubeflow applications
    keywords:
    - kubeflow
    links:
    - description: About
      url: https://kubeflow.org
    maintainers:
    - email: jlewi@google.com
      name: Jeremy Lewi
    - email: kam.d.kasravi@intel.com
      name: Kam Kasravi
    owners:
    - email: jlewi@google.com
      name: Jeremy Lewi
    type: kubeflow
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.6
status:
  components:
  - link: /apis/app.k8s.io/v1beta1/namespaces/kubeflow/applications/kubeflow
    name: kubeflow
    status: Ready
  - link: /apis/app.k8s.io/v1beta1/namespaces/kubeflow/applications/centraldashboard
    name: centraldashboard
    status: Ready
  - link: /apis/app.k8s.io/v1beta1/namespaces/kubeflow/applications/jupyter-web-app
    name: jupyter-web-app
    status: Ready
  - link: /apis/app.k8s.io/v1beta1/namespaces/kubeflow/applications/notebook-controller
    name: notebook-controller
    status: Ready
  conditions:
  - lastTransitionTime: 2019-08-21T13:17:57Z
    lastUpdateTime: 2019-08-21T13:17:57Z
    message: all components ready
    reason: ComponentsReady
    status: "True"
    type: Ready
  - lastTransitionTime: 2019-08-21T13:17:57Z
    lastUpdateTime: 2019-08-21T13:17:57Z
    message: No error seen
    reason: NoError
    status: "False"
    type: Error
```

**Comment by jlewi** [comment]
I tried with https://raw.githubusercontent.com/kubeflow/kubeflow/c3199d931b9b82c8717057c7aca883d76bb5e1d5/bootstrap/config/kfctl_gcp_iap.0.6.2rc.yaml

and I'm still seeing v1beta1 in the UI.

It looks like the version in the kubeflow application is fixed; now 0.6.2.
[application.txt](https://github.com/kubeflow/kubeflow/files/3535056/application.txt)

So I think the problem is that the UI is showing the version of the first application returned and not looking at the Kubeflow application.

[centraldashboard.txt](https://github.com/kubeflow/kubeflow/files/3535063/centraldashboard.txt)

@avdaredevil we need to fix the centraldashboard code to look for the kubeflow application and not just use the first application.

However, a quick fix @gabrielwen might be to just bump the version in the Application manifest for the centraldashboard. We should do that anyway because the version should be v0.6.2 not v1beta1.

**Comment by jlewi** [comment]
It also looks like when I'm logged in as the user that deployed Kubeflow it doesn't think I'm the manager and show me the namespace creation UI.

**Comment by abhi-g** [comment]
Could these be because we don't have the central dashboard PRs cherrypicked
into v0.6-branch yet?

**Comment by jlewi** [comment]
Kubeflow kubeflow/kubeflow#3994 uses kubeflow/manifests@1099a06
That shows v0.6.2 as the version in the central dashboard because I had updated all the application CRs to set the version to v0.6.2. We would still need to update the centraldashboard image to correctly look at the Kubeflow application to get the version.

**Comment by abhi-g** [comment]
#3992 is supposed to fix that by looking for Kubeflow application. Does it
not?

**Comment by jlewi** [comment]
@abhi-g #3994 isn't using #3992 (updated centraldahboard yet). I think 
kubeflow/manifests#311 updates the kubeflow/manifests@v0.6-branch to pull in the fixed central dashboard. 

I just lgtm'd kubeflow/manifests#311.
