### ISSUE TITLE
kfctl cannot infer project when not set

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#3923]
/kind bug

**What steps did you take and what happened:**

I am using the latest config from master (removing the dummy value of project/email)
```
kfctl init --config=kfctl_gcp_iap.yaml
kfctl generate all
```

The project field is missing, and hostname treat it as empty string
kf0815-2.endpoints..cloud.goog

It can infer the email though.

gcloud config has both email and project set:

```
$ gcloud config list
[compute]
region = us-central1
zone = us-central1-a
[core]
account = lunkai@google.com
disable_usage_reporting = True
project = kai-test2

Your active configuration is: [default]
```

cc @jlewi

**Comment by jlewi** [comment]
It looks like we have logic to get the Default email
https://github.com/kubeflow/kubeflow/blob/d82aa59103940918a9c8e1ca87ba94f24bec09b2/bootstrap/pkg/kfapp/gcp/gcp.go#L229

We are missing similar logic for project and zone.

Bump to P0 because we should try to fix this in 0.7.X.

This should be a relatively straightforward fix.
Without it users can't deploy in one command e.g.

```
kfctl apply -f https:/.../kfctl_gcp_iap.yaml
```

Because they have to modify the config to set the values.
