### ISSUE TITLE
[CentralDashboard v2] Create end-to-end testing for Releases

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/kubeflow#4015]
## About
We want to have end-to-end verification of health / state status of central-dashboard. This would allow us to make sure the state we expect in CentralDash is exactly what the backends expect

### Context:
- The 2 routes most helpful for this are:
  - `//<host>:<port>/debug` - Lists important state info, and environment data that can be used for quick verifications
  - `//<host>:<port>/api/workgroup/env-info` - Lists metrics, platform data, user info, namespaces (_you'll only get scoped data if your headers are set correctly for MUI_)

### Meta
/area centraldashboard
/area front-end
/priority p1
/kind feature
/assign @avdaredevil @jlewi 
/cc @prodonjs

**Comment by jlewi** [comment]
I think it would be valuable to write a short doc/tech note about how we could do testing for the central dashboard.

When doing the 0.7 release we hit kubeflow/kubeflow#4415. This is an issue where the self registration flow is not working in the case where Kubeflow clusters don't have identity.

**Comment by prodonjs** [comment]
@avdaredevil - I don't think I have the bandwidth to carry it forward, but I put together a rough pass at an E2E test in https://github.com/prodonjs/kubeflow/commit/bca6def173959c2721d1effdbe2e4e91cf41c94f. This was intended to test the IAP-scenario, but it could be easily adapted to handle basic-auth as well and let us have coverage for both registration scenarios.

Maybe we can schedule some time to discuss next week.

**Comment by jlewi** [comment]
@prodonjs @avdaredevil is there anyone that could pick up https://github.com/prodonjs/kubeflow/commit/bca6def173959c2721d1effdbe2e4e91cf41c94f and push it over?

**Comment by prodonjs** [comment]
What's the deadline? I'm on leave for another couple of weeks so I won't be available to carry it through myself.

@avdaredevil - if you have the cycles and need a consult or have questions, I may be able to respond.

**Comment by jlewi** [comment]
Thanks @prodonjs

**Comment by jlewi** [comment]
I looked at https://github.com/prodonjs/kubeflow/commit/bca6def173959c2721d1effdbe2e4e91cf41c94f

I see some javascript to drive the Kubeflow central dashboard.

I think some of the additional work needed is

* Figuring out how to drive this in our E2E tests?
* Figuring out how to get credentials and talk to the KF cluster?
  * I think we will want to access central dashboard over the external accesspoint so that redirects would work
  * This likely means that we would want to use IAP and do programmatic authentication.
* We will need to integrate this into our E2E tests and produce junit files to report success

I would break this up into steps

1. Create a manual test
1. Integrate that test into our CI system

For one I think what we need is a binary that can run the test e.g. something like

```
run_test https://kf-v1-0211-9a2.endpoints.kubeflow-ci-deployment.cloud.goog/
```

And then the binary could just print out success or failure.

/cc @avdaredevil

**Comment by jlewi** [comment]
Some related items

* Old test for jupyter resource
* https://github.com/jlewi/kubeflow/blob/1690703d261d29ccd7e1d5ff154d79064473d9d8/kubeflow/jupyter/tests/jupyter_test.py#L85
   * This is trying to test that notebooks are actually accessible.
* kubeflow/kubeflow#3657 E2E test for Jupyter web app

**Comment by DavidSpek** [comment]
@PatrickXYS Given that the linked PR https://github.com/kubeflow/kfctl/pull/249 was closed, can this issue also be closed?

**Comment by PatrickXYS** [comment]
@DavidSpek It depends, the reason that we close the PR is we haven't heard back from author.

**Comment by DavidSpek** [comment]
@PatrickXYS I thought you added it given https://github.com/kubeflow/kfctl/pull/249#issuecomment-721433640

**Comment by PatrickXYS** [comment]
@DavidSpek I haven't, we can close the issue and revisit afterwards.
