### ISSUE TITLE
Notebooks Manager UI needs support for upgradability

### ISSUE THREAD

**Issue by abhi-g** [kubeflow/kubeflow#4067]
/kind feature

**Why you need this feature:**
Applications Requirement for Notebooks Manager UI to be included in Kubeflow 1.0

**Describe the solution you'd like:**
It should be possible to upgrade the web application for notebooks management to be upgraded via the kfctl upgrade. Please see details on design and requirements for the application in [Upgrade Design Doc](https://bit.ly/2ZWmHJ9)

**Comment by jlewi** [comment]
Are we aware of any work that would prevent the Jupyter Web App from being upgraded with kfctl? Is the only work to actually test it out to verify it works as expected?

/cc @richardsliu

**Comment by jlewi** [comment]
@richardsliu @kimwnasptd What do you think?

**Comment by jlewi** [comment]
Downgrading to P1 because this isn't release blocking upgrades are still alpha.

**Comment by DavidSpek** [comment]
Currently it is possible to upgrade the Jupyter Web App by changing the image of it's deployment. I'm not sure how `kfctl` would play into this, but given that `kfctl` is not being used for the 1.3 release and the many changes to the manifests (see https://github.com/kubeflow/manifests/issues/1735) I don't think this issue is still relevant in it's current form. 

/remove-lifecycle frozen
