### ISSUE TITLE
Profile & Kfam: Continuous building of docker images

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#4079]
Profile & Kfam: Continuous building of docker images

**Comment by jlewi** [comment]
Bump to P0 because this is required for 1.0.

kubeflow/testing#450 - is the uber issue for CD of multiple applications. Once that bug is fixed that should likely include a solution for the profile controller. The only remaining work would then be to verify that it is working as intended.

We currently have a Tekton PipelineRun to build the profile controller image.
https://github.com/kubeflow/testing/tree/master/apps-cd

The next steps are listed in kubeflow/testing#450

**Comment by jlewi** [comment]
kubeflow/manifests#705 auto-update of profile controller - This was merged
kubeflow/manifests#707 PR to update kfam - This is blocked on failing tests.

Lets make sure we have at least one merged PR for kfam before we close this out.

**Comment by jlewi** [comment]
kubeflow/manifests#790 update profile control to 1.0 on 1.0-branch - merged
kubeflow/manifests#793 update kfam control to 1.0 on 1.0-branch - not merged

Just waiting on #793 and then we should be able to close this.

**Comment by jlewi** [comment]
PRs merged.
