### ISSUE TITLE
Notebook external access with ssh

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/kubeflow#4080]
/kind question

**Question:**
Is it possible to ssh in to a Kubeflow Notebook from and external computer? We currently have computers with Jupyter installed that users user Visual Studio to remotely connect to the Jupyter kernel and develop their code. I believe this connection just works through ssh. Would there be a way to replicate this process with notebooks in Kubeflow? Thanks!

**Comment by kaikun213** [comment]
I believe you can connect to the jupyter notebook server via ssh tunneling. E.g.

```
ssh -N -L localhost:8888:localhost:8887 user@remote
```

**Comment by Hrishkesh** [comment]
I am also interested in this feature. @kaikun213 I believe this question is regarding how can u open an ssh connection into the jupyter notebook pod. The solution which you have mentioned is to open jupyter web ui from local using tunneling, but I want to know how we could open port 22 from jupyter pod so that u can connect to the pod terminal using putty/vs code.

**Comment by adrshm91** [comment]
I am also interested in this feature. @kaikun213 I believe this question is regarding how can u open an ssh connection into the jupyter notebook pod. The solution which you have mentioned is to open jupyter web ui from local using tunneling, but I want to know how we could open port 22 from jupyter pod so that u can connect to the pod terminal using putty/vs code.

**Comment by atamahjoubfar** [comment]
Has anyone found a solution for this?

**Comment by peterbarty** [comment]
@atamahjoubfar @adrshm91 it's been a while since your posts but I was able to achieve this via the following steps for a user/password ssh:

1. define a custom jupyterlab container image with a port exposed (e.g. port 22)
2. start your jupyter-lab instance via the Kubeflow UI & connect to it
3. define a user & password to log in with (e.g. user=test, password=XXXXX) on the instance. You can follow the instructions [here](https://gist.github.com/BetterProgramming/149084cb9a84c31e6f635a2988186ae8#file-dockerfile) for this. This could also be in your Dockerfile if you want (& can safely pass the password)
4. port-forward to your notebook's pod's exposed port e.g. `kubectl port-forward pod/notebook-0 -n my-namespace 1234:22` if exposing port 22
5. You can then ssh into localhost (127.0.0.1) via the local port (in this case 1234), e.g. `ssh test@localhost -p 1234`

For VSCode/Pycharm integration you may also need to assign certain permissions to the user you created for compatibility (e.g. write permission to certain directories)

**Comment by thesuperzapper** [comment]
We are discussing how to allow remote SSH access in Notebooks 2.0.

Please follow the issue here and please share any ideas for how to do it safely:

- https://github.com/kubeflow/notebooks/issues/23
