### ISSUE TITLE
Dashboard deployed on eks does not show manage contributors in navigation

### ISSUE THREAD

**Issue by danieldn** [kubeflow/kubeflow#4113]
/kind bug

**What steps did you take and what happened:**
Following documentation on https://www.kubeflow.org/docs/aws/deploy/install-kubeflow/ 

Successfully completed step 5 and proceeded to post installation step of creating user profiles. However, noticed that the dashboard deployed does not match the dashboard shown in docs at https://www.kubeflow.org/docs/other-guides/multi-user-overview/

The dashboard deployed on our cluster shows `build version v1beta1` in the bottom left corner with no manage contributors tab available on the side navigation
![image](https://user-images.githubusercontent.com/11370398/64735984-79821400-d49e-11e9-989e-7bd32e2bc11f.png)

**What did you expect to happen:**
Expected to have the dashboard corresponding to `build version v0.6.2` with the manage contributors tab on the menu available

**Anything else you would like to add:**

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1beta1
- kfctl version: (use `kfctl version`): v0.6.2
- Kubernetes platform: (e.g. `minikube`) AWS EKS
- Kubernetes version: (use `kubectl version`): v1.15.3 (client), v1.13.10-eks-5ac0f1 (server)
- OS (e.g. from `/etc/os-release`): darwin

**Comment by danieldn** [comment]
kubectl describe on the dashboard pod shows me gcr.io/kubeflow-images-public/centraldashboard:v20190823-v0.6.0-rc.0-69-gcb7dab59

**Comment by Jeffwan** [comment]
The version problem is because of this change,
https://github.com/kubeflow/manifests/commit/6dc0c0d10a8060ff748a74da650776da1ba4e3b7#diff-e23ef4b176ec21de1d67c8de4789720d

Actually the master version is `v1beta1` and 0.6-branch is is`v0.6.2`. Since you use master manifest, then you see `v1beta1` there.

**Comment by Jeffwan** [comment]
I cherry-pick https://github.com/kubeflow/manifests/pull/360 to 0.6-branch and once you use 0.6-branch for manifest repo. This issue should be resolved automatically.

**Comment by Jeffwan** [comment]
For `Manage Contributors`, it's invisible because of 

https://github.com/kubeflow/kubeflow/blob/64f4f79ef7d2f1eed1113dce6955437717b94e1b/components/centraldashboard/public/components/main-page.js#L197-L202

https://github.com/kubeflow/kubeflow/blob/64f4f79ef7d2f1eed1113dce6955437717b94e1b/components/centraldashboard/public/components/main-page.pug#L21-L24

Aws deployment is still being considered as `single-user` at this moment and I will make some improvements on profile env to enable this feature. Thank you for reporting,
https://github.com/kubeflow/kubeflow/issues/3437#issuecomment-520966718

**Comment by antimack** [comment]
Not sure it's related since I am installing Kubeflow using kfctl_k8s_istio.0.6.2.yaml, centraldashboardversion image is `v20190823-v0.6.0-rc.0-69-gcb7dab59` in the UI it shows v0.6.2, but we also don't have `Manage Contributors`

**Comment by Jeffwan** [comment]
> Not sure it's related since I am installing Kubeflow using kfctl_k8s_istio.0.6.2.yaml, centraldashboardversion image is `v20190823-v0.6.0-rc.0-69-gcb7dab59` in the UI it shows v0.6.2, but we also don't have `Manage Contributors`

only `multi-user` case will enable `Manage Contributors`. `v20190823-v0.6.0-rc.0-69-gcb7dab59` already has this feature

**Comment by antimack** [comment]
I understand, I do use profiles and it seems multi-user works but “Manage contributors” is not available. Should I create a separate issue?

**Comment by jbottum** [comment]
do we have a path to close this issue in v0.7?

**Comment by Jeffwan** [comment]
@jbottum I am evaluating the gap and I will try to close it before we cut branch

**Comment by Jeffwan** [comment]
@Julianxo This will be supported in 1.0
