### ISSUE TITLE
kubeflow stuck at setup screen.

### ISSUE THREAD

**Issue by Rohithzr** [kubeflow/kubeflow#4126]
/kind bug

**What steps did you take and what happened:**
1. setup microk8s
```
microk8s.status
microk8s is running
addons:
knative: disabled
jaeger: disabled
fluentd: enabled
gpu: enabled
cilium: disabled
storage: enabled
registry: disabled
rbac: disabled
ingress: enabled
dns: enabled
metrics-server: enabled
linkerd: disabled
prometheus: enabled
istio: enabled
dashboard: enabled
```

2. install kubeflow 0.6.2
```
Guide: https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio
```

This led me to the Setup screen where If I enter a name and it does nothing, the env-info  endpoint returns 

```
{"user":"anonymous@kubeflow.org","platform":{"kubeflowVersion":"v0.6.2","provider":"other://","providerName":"other"},"namespaces":[],"isClusterAdmin":true}
```

**What did you expect to happen:**
I expect that when I access the `ingress-gateway` on `istio-system` the central dashboard opens and everything works. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version: v0.6.2-0-g47a0e4c7
- Kubernetes platform:microk8s on ubuntu

**Comment by jlewi** [comment]
@avdaredevil looks like there might be a problem with the self registration flow. Any suggestion on how to debug?

@Rohithzr you might be able to work around this by creating a profile manually via the CLI. There are docs for doings this here
https://v0-6.kubeflow.org/docs/other-guides/multi-user-overview/#manual-profile-creation

**Comment by avdaredevil** [comment]
So the Dashboard seems to be running in non-isolated mode. Registration Flow opens up since namespaces is empty. 

Here's where it's hairy for me:
- The dashboard takes the input and runs a `createBinding` against profile service.
- If this fails an error should surface on the UI (worst case, error is still there in dev-console under the `/workgroup/create` route)
- Did you try reloading? (perhaps the profile creation took time, and dashboard fetched the new list of namespaces before that step completed)

I'd need more data to help further:
- Do you see an error?
- Does the route actually have an error (in dev console)?

**Comment by Rohithzr** [comment]
it does work if you create an profile.

**Comment by jmsking** [comment]
i have create a profile manually, the profile is:

_apiVersion: kubeflow.org/v1alpha1
kind: Profile
metadata:
  name: kubedemo   # replace with the name of profile you want
spec:
  owner:
    kind: User
    name: anonymous@kubeflow.org   # replace with the email of the user_

but when i visit the web ui, there is still a startup page, can you tell me is there other step?
@Rohithzr
