### ISSUE TITLE
installing Kubeflow with platform set to existing_arrikto without Istio and Dex

### ISSUE THREAD

**Issue by antimack** [kubeflow/kubeflow#4158]
Kubeflow version: v0.6.2
Config: https://raw.githubusercontent.com/kubeflow/kubeflow/v0.6.2/bootstrap/config/kfctl_existing_arrikto.0.6.2.yaml

Is there a way to install existing_arrikto on a cluster with Istio and dex already installed? (we are using latest version of Istio with internal ELB and issuing certificates with cert-manager + other tweaks as well as Dex with custom config).

Or is it possible to have multi-user with profiles, managing contributors etc. working with existing_k8s_istio with Istio disabled?

Any help appreciated.

**Comment by yanniszark** [comment]
Hi @antimack! Let me try to answer your questions.

> Is there a way to install existing_arrikto on a cluster with Istio and dex already installed? 

Yes, but it requires some custom setup to wire everything together.
This will become much easier in v0.7 for the existing_arrikto config.
I will give you an update as soon as possible.

> Or is it possible to have multi-user with profiles, managing contributors etc. working with existing_k8s_istio with Istio disabled?

Right now, we rely on Istio RBAC to enforce access control to Notebook Servers.
In addition, we use Istio to serve each application under each own path prefix.
Because of that, I don't think it's straightforward to run Kubeflow without Istio at this moment.

If you have any more questions please follow up here, I'd be happy to help :smile:

**Comment by antimack** [comment]
> This will become much easier in v0.7 for the existing_arrikto config.
I will give you an update as soon as possible. 

that would be awesome!

> Right now, we rely on Istio RBAC to enforce access control to Notebook Servers.
In addition, we use Istio to serve each application under each own path prefix.
Because of that, I don't think it's straightforward to run Kubeflow without Istio at this moment.

no-no :) I meant, if we are using existing_k8s_istio we can disable Istio that is bundled and use our own existing installed, can we have multi-user with profiles, managing contributors etc. working? because I didn't managed to succeed, it seems it doesn't tolerate profiles access to namespaces and "managing contributors" is not available, but that might be UI.

**Comment by antimack** [comment]
@yanniszark hi! any news regarding this after 0.7.0 release, is there a way now to deploy to a cluster with Istio and Dex already installed?

**Comment by LeonardAukea** [comment]
Is this issue resolved?

**Comment by yanniszark** [comment]
You can now install without Istio and Dex by simply removing them from the KfDef.
I believe this can be closed.
/close

**Comment by LeonardAukea** [comment]
Thank you for resolving this Issue!
