### ISSUE TITLE
kfam: bindings roleref contain magic string and not real role

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#4217]
/kind bug

**What did you expect to happen:**
The Binding struct defines a RoleRef.
I expect the RoleRef to contain a K8s role.

**What happened:**
The RoleRef contains a magic string ("view") instead of the real role ("kubeflow-viewer").
That's because the frontend expects a certain value.

**Possible Solutions:**
* Make it clear that those are magic values and not Roles. Maybe add a separate field called type, or description.
* Use the real Role names and fix the UI to fallback to the Role name if it doesn't find the values it expects.

/cc @jlewi @krishnadurai 
/priority p1

**Comment by jlewi** [comment]
@yanniszark "view" was the role

```
kubectl  get clusterrole
NAME                                                                   AGE
admin                                                                  2d
...
edit                                                                   2d
...
view                                                                   2d

```

`kubeflow-viewer` is the new name for the role starting in 0.7.

So is this an issue with backwards compatibility?

**Comment by jlewi** [comment]
@yanniszark Is this about #4167 and the addition in that PR of
components/access-management/kfam/bindings.go 
which is mapping "view" to "kubeflow-viewer"

I think that was just for backwards compatibility because in 0.6 the role names were edit, view, admin and we are changing this in 0.7 to kubeflow-edit, kubeflow-view, and kubeflow-admin.

But the central dashboard was still sending the old names to the KFAM backend so the KFAM backend was doing the mapping from the old role names to the new ones. 

So I think if we update the front end to use the new role names then we can delete the code doing the mapping in bindings.go

**Comment by krishnadurai** [comment]
@jlewi There are 2 ways approach this:
1) ClusterRole names are same the role names shown in the frontend with a 'kubeflow' prefix.
2) Both are different and are mapped by the backend.

I suggest we retain the names 'admin', 'edit' and 'view' at the frontend and at the backend API level too and role-bindings can be mapped - option 2. This would mean that ClusterRole names are not necessarily the same as shown in the frontend.

**Comment by jlewi** [comment]
@krishnadurai  Is option 2 just a temporary solution for backwards compatibility? Would we eventually remove it and surface the actual cluster roles?

What would be the reason long term for introducing a a layer of indirection around the underlying cluster-roles?

In general, I think the principle we are trying to follow with Kubeflow IAM is to reuse RBAC as much as possible. Applying that principle, surfacing actual RBAC role names makes the most sense. One reason for doing this is then its natural for people to switch between using KF tooling (e.g. our UI) and other tooling (e.g. kubectl).

**Comment by krishnadurai** [comment]
> What would be the reason long term for introducing a a layer of indirection around the underlying cluster-roles?

@jlewi I'm fine with keeping the same names in frontend and backend for RBAC rules, with the thought you've mentioned above. This convention of adding the prefix to role names needs to be ensured if we allow users to define their own roles with future releases. I had initially thought of achieving this through mapping so that users wouldn't have to ensure it, given that their names could clash with existing RBAC roles.
But I think we could avoid that in many other ways.
