### ISSUE TITLE
Use Spark from Jupyter

### ISSUE THREAD

**Issue by holdenk** [kubeflow/kubeflow#4306]
/kind feature

**Why you need this feature:**
I'd like to be able to use Spark from the Jupyter notebook in client mode. I used to be able to do this before istio.

**Describe the solution you'd like:**

Spark launches the executors, but then the executors can not connect back to the driver program.

**Anything else you would like to add:**

**Comment by nrchakradhar** [comment]
It's possible to selectively disable istio sidecar injection which might help. It should then be back to without istio.

**Comment by LeonardAukea** [comment]
@nrchakradhar Do you have an example of how this would be done?

**Comment by nrchakradhar** [comment]
@LeonardAukea This [link](https://istio.io/docs/setup/additional-setup/sidecar-injection/) can help. Based on cluster configuration multiple choices mentioned can be utilized.

**Comment by LeonardAukea** [comment]
Could we add the option in the `jupyter-web-app` to give permissions to the server to launch other pods.  it would be very useful to be able to spin up clusters directly from the notebook. maybe one could work eith the `spark-operator` together with katib.

**Comment by szinck1** [comment]
I'm having this exact issue.  Has anyone found a good workaround or solution?

**Comment by krishnadurai** [comment]
We may have to figure out a way in which we are able to allow spark to connect from 'kubeflow' namespace back to the notebook in a profile namespace.
Could we try to get this done by creating a virtual service definition and adding the relevant service to service Istio RBAC roles for spark when we create a profile?

**Comment by szinck1** [comment]
@krishnadurai that's something I can explore. if you have any specific suggestions please let me know and I will test on my installation.

**Comment by szinck1** [comment]
@krishnadurai why do you think the problem is communication from the kubeflow namespace? our notebooks and spark (spark for Kubernetes) are all contained within one namespace. The web app, notebook controller and other parts of Kubeflow are in the kubeflow namespace though.

**Comment by krishnadurai** [comment]
@szinck1 could you please share a notebook with me so that I can take look at an example?

**Comment by szinck1** [comment]
@krishnadurai 
Here is the pyspark config that works outside of Kubeflow.   BTW, I tried disabling istio for the `anonymous` namespace (the Kubeflow profile ns) but after doing that the Jupyter web app can't connect to the pods.

```
import findspark, pyspark
findspark.init()
from pyspark import SparkContext, SparkConf
conf = SparkConf().setAppName('sparktest').setMaster('k8s://https://kubernetes.default.svc:443')
conf.set("spark.kubernetes.namespace", "anonymous")
conf.set("spark.kubernetes.authenticate.driver.oauthToken", "some-token")
conf.set("spark.kubernetes.container.image", "registry/image")
conf.set("spark.kubernetes.allocation.batch.size", "5")
conf.set("spark.kubernetes.executor.instances", "1")
conf.set("spark.driver.bindAddress", "0.0.0.0")
conf.set("spark.driver.host", "jupyter")
conf.set("spark.driver.port", "37371")
conf.set("spark.blockManager.port", "6060")
```

`spark.driver.host` is a service that selects my notebook pod. This is necessary we need a consistent DNS name to connect to the driver.

That code will launch two pods, each with an `executor` container. The` executor` container will not be able to connect back to the driver/jupyter service.  Here's the logs:

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: jupyter/172.21.224.158:37371
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
```

**Comment by szinck1** [comment]
We found a workaround for this. We disabled istio pod injection for the "anonymous" (or any Kubeflow Profile namespace) and added a DestinationRule to permit unencrypted traffic. This is obviously not ideal. Hopefully this can be addressed in an upcoming release.

```
$ kubectl describe ns anonymous
Name:         anonymous
Labels:       istio-injection=disabled
              katib-metricscollector-injection=enabled
Annotations:  owner: anonymous@kubeflow.org
Status:       Active
```

```
$ kubectl get dr -o yaml -n anonymous
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: default
    namespace: anonymous
  spec:
    host: '*.anonymous.svc.cluster.local'
    trafficPolicy:
      tls:
        mode: DISABLE
```

**Comment by szinck1** [comment]
Are there plans to resolve this issue for the 1.0 release?

**Comment by holdenk** [comment]
@szinck1 how do you think we should go about working on this?

**Comment by szinck1** [comment]
@holdenk  We had disable istio pod injection and create the above DR.  @krishnadurai had an initial suspicion of Istio as well.  

I'm not sure how best to engineer a solution... perhaps have an option to disable RBAC on a per namespace basis.

**Comment by prem0912** [comment]
@holdenk and @szinck1  adding  annotations to driver and executor pod configuration as istio sidecar injection as "false" might solve this issue, so we disable only to spark pods instead of disabling  for whole namespace

	  driver:
		labels:
		  version: 2.4.4
		annotations:
		  "sidecar.istio.io/inject": "false"
		serviceAccount: 
	  executor:
		instances: 3
		annotations:
		  "sidecar.istio.io/inject": "false"
		labels:
		  version: 2.4.4

we can add  same annotations if deployed through spark-submit or pyspark as well

**Comment by krishnadurai** [comment]
@prem0912 can you please elaborate on how we could possibly add these annotations through spark-submit or pyspark?

Likewise, do we want users to always pass these annotations through spark-submit for each job because of our namespace level istio-injection setting? Or could we look at alternatives to automate this?

/cc @jlewi @holdenk

**Comment by prem0912** [comment]
@krishnadurai  We can add annotations in spark-submit as 

		`spark-submit --master k8s://https://<<CLUSTER-IP>> --deploy-mode cluster \  
		  --name spark-pi --class <<some-class>> \
	          --conf spark.kubernetes.pyspark.pythonVersion=3 \
		  --conf spark.kubernetes.driver.annotation.sidecar.istio.io/inject=false \
		  --conf spark.kubernetes.executor.annotation.sidecar.istio.io/inject=false \
		  --conf spark.executor.instances=3 --conf spark.kubernetes.namespace=anonymous \
		  --conf spark.kubernetes.container.image=<registry/image>>  \ 
              local:///<<some file name>>` 

User need to pass these annotations for each spark-submit  job, where istio-injection is enabled in namespace level.

**Comment by Felihong** [comment]
+1, is this also somehow related to using `dask-kubernetes` within notebook? 
See https://github.com/dask/dask-kubernetes/issues/197

**Comment by akirillov** [comment]
In order to provide a proper solution, it is important to understand why Spark executors fail to register with the Driver. When an executor pod starts, Istio init container changes `iptables` to reroute traffic to Envoy proxy. And until Envoy proxy is up and running, Spark executor is unable to communicate over the network. This is kind of a race condition between an executor and Envoy proxy.

The quick fix for that is to disable Istio by providing an annotation, as mentioned before. When running from a notebook in the interactive mode as opposed to `spark-submit`, this can be achieved via SparkContext configuration e.g.:
```
import socket
import pyspark
from pyspark.sql import SparkSession

localIpAddress = socket.gethostbyname(socket.gethostname())

conf = pyspark.SparkConf().setAll([
    ('spark.master', 'k8s://https://10.0.0.1:443'),
    ("spark.driver.host", localIpAddress),
    ("spark.kubernetes.namespace", "<namespace>"),
    ("spark.executor.instances", 5),
    ("spark.kubernetes.container.image", "<image>")])

spark = SparkSession.builder.appName("KubeflowSpark").config(conf=conf).getOrCreate()
```

However, the better way to fix the issue and keep everything running on Istio is to introduce a retry in Spark [entrypoint script](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh#L103) and replace this. line:
```
exec /usr/bin/tini -s -- "${CMD[@]}"
```
with something like this:
```
retries=5
while [[ ${retries} -ge 0 ]]
do
  /usr/bin/tini -s -- "${CMD[@]}" && break
  ((retries-=1))
  echo "Failed to start ${SPARK_K8S_CMD}. ${retries} reties left"
  sleep 15
done
```
This will allow Spark Executor to wait for Envoy proxy and once it is up, it will be possible for the executor to connect to the Driver.

**Comment by Jeffwan** [comment]
@akirillov 

Trying to understand if there's cases to use istio here. Based on my understanding, only applications like Spark History Server need istio. For spark applications, how about add annotation
`istio-injection: disabled`.  This doesn't need Spark entrypoint change

**Comment by akirillov** [comment]
@Jeffwan, it depends on the use case. Sometimes due to compliance requirements mutual TLS is a must have. Also, building a custom docker image for Spark doesn't seem to be an issue.

Another option is to disable sidecar injection at the namespace level so all the workloads in a user namespace run without sidecars and users don't have to provide this annotation every time they create SparkContext.

**Comment by Jeffwan** [comment]
@akirillov Yeah. Disable sidecar at the namespace level is kind of hard to do now. We actually raise the same request before, by default, only services with annotation should be injected. But at the beginning, it's in an opposite way. This is not that friendly to batch workload users for sure. 

As Spark doesn't provide official images, changing images is an option.

**Comment by akirillov** [comment]
Hi @Jeffwan, can you please elaborate more on why it is hard to do right now? Is there any security implications? In some deployments, we use our own patched Profile controller which doesn't inject Istio labels while creating user namespaces.

**Comment by yosit** [comment]
here is a snippet of code that would work without touching istio - this is running under a new namespace outside of the kubeflow profile namespace.
Verified on 2.4.5 and 3.0.0 on k8s 1.15

`import os
import socket
from pyspark.sql import SparkSession

os.environ['PYSPARK_PYTHON'] = "/usr/bin/python3"
spark = SparkSession\
    .builder\
    .appName("PythonWordCount")\
    .config("spark.hadoop.fs.s3a.aws.credentials.provider", "com.amazonaws.auth.DefaultAWSCredentialsProviderChain")\
    .master("k8s://https://{ip}:{port}".format(ip=os.environ['KUBERNETES_SERVICE_HOST'], port=os.environ['KUBERNETES_SERVICE_PORT'])) \
    .config("spark.driver.host", str(socket.gethostbyname(socket.gethostname()))) \
    .config("spark.kubernetes.namespace", "pyspark-workers") \
    .config("spark.kubernetes.container.image", "[YOUR WORKER DOCKER IMAGE]") \
    .config("spark.executor.instances", "10") \
    .config("spark.executor.memory", "512m") \
    .config("spark.executor.cores", "1") \
    .getOrCreate()
`

**Comment by Jeffwan** [comment]
@yosit 
namespace not under profile controller management will be fine since istio RBAC rules were not created. 

I think current blocking issue is on the istio policy side. When executor tries to connect back to user, it will be blocked since istio need authorization. We probably can add some policy to bypass check for these two ports. driver port and block manager's port. 

Let me check it and see what configuration we can add there.

**Comment by Hmr-ramzi** [comment]
@Jeffwan Any news about the fix your proposed ?

**Comment by theathibm** [comment]
anymore info on this, seems like connecting back to driver isn't working .   I tried @yosit approach and it kicks off the multiple workers, but they all can't connect back to the driver.

20/09/01 23:05:04 INFO SecurityManager: Changing view acls to: root
20/09/01 23:05:04 INFO SecurityManager: Changing modify acls to: root
20/09/01 23:05:04 INFO SecurityManager: Changing view acls groups to: 
20/09/01 23:05:04 INFO SecurityManager: Changing modify acls groups to: 
20/09/01 23:05:04 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1713)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:64)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:285)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:201)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:65)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:64)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	... 4 more
Caused by: java.io.IOException: Failed to connect to /172.30.37.165:38953
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:245)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:187)
	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:198)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:194)
	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.30.37.165:38953
Caused by: java.net.ConnectException: Connection refused

> here is a snippet of code that would work without touching istio - this is running under a new namespace outside of the kubeflow profile namespace.
> Verified on 2.4.5 and 3.0.0 on k8s 1.15
> 
> ```
> import os
> import socket
> from pyspark.sql import SparkSession
> 
> os.environ['PYSPARK_PYTHON'] = "/usr/bin/python3"
> spark = SparkSession\
>     .builder\
>     .appName("PythonWordCount")\
>     .config("spark.hadoop.fs.s3a.aws.credentials.provider", "com.amazonaws.auth.DefaultAWSCredentialsProviderChain")\
>     .master("k8s://https://{ip}:{port}".format(ip=os.environ['KUBERNETES_SERVICE_HOST'], port=os.environ['KUBERNETES_SERVICE_PORT'])) \
>     .config("spark.driver.host", str(socket.gethostbyname(socket.gethostname()))) \
>     .config("spark.kubernetes.namespace", "pyspark-workers") \
>     .config("spark.kubernetes.container.image", "[YOUR WORKER DOCKER IMAGE]") \
>     .config("spark.executor.instances", "10") \
>     .config("spark.executor.memory", "512m") \
>     .config("spark.executor.cores", "1") \
>     .getOrCreate()
> ```

**Comment by Hmr-ramzi** [comment]
@theathibm, I was able to get a work around to be able to start spark jobs from within jupyter using the fairing component. You will have to have an docker image that has pyspark, You can easily write the code as a function in one of the jupyter notebook cells and than wrap it as a train job using the fairing component. Then, you can start the training job. The difference between the proposed approach and the original one is that the fairing component creates a new pod (without sidecar injection) which itself is the driver and communicates with the kubernetes api to generate the executors unlike the jupyter notebook pod which is restricted by istio to communicate to any of the generated executors (in case it acts as a driver). https://github.com/kubeflow/fairing/blob/master/examples/train_job_api/main.ipynb Here you can find some example on how to use the fairing component to start a train job which can start the spark job

**Comment by yosit** [comment]
@theathibm
you need to add a network policy in your namespace
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}

```

**Comment by reevelau** [comment]
Turn out this is a known issue of istio istio/istio#11130.

By applying a workaround in the issue, I can successfully start a customized spark node image from jupyter notebook. 

The workaround is simply adding a "sleep 20" in the entrypoint.sh of the spark node image. Of course, the workaround could be done more elegantly. But it proves that the node image failed (Connection Refused) because of istio-proxy failed to be ready before spark executor trying to reach the spark driver host.

**Comment by DavidSpek** [comment]
Adding a Spark notebook (already have a PR that needs updating) is something we have in mind, but we'd like to look into how to properly integrate Spark with kubeflow as well. At the moment we have not had time to do this yet.

**Comment by jdonnelly-apixio** [comment]
This works in the spark app entrypoint.sh for the istio not yet ready issue when executors connect. It checks for the port to be open every 1 second for up to 2 minutes.
```bash
  executor)
    shift 1
    # added for jupyter spark + istio proxy. need to wait for the driver port to be accessible
    driver_ip_slash_port=$(echo $SPARK_DRIVER_URL | awk -F '@' '{print $2}' | sed 's/:/\//g')
    while ! timeout 120 bash -c "echo > /dev/tcp/${driver_ip_slash_port}" ; do sleep 1; done
    ...
```

**Comment by mousam-singh** [comment]
I still could not find possible solution for this issue here, is there any workaround to achieve the network connection between spark driver and executors. I am using EMR node as master in client mode from kubeflow notebook, however after creating separate services to expose driver ports I still get connection refused or closed error.
