### ISSUE TITLE
Presubmit shows succeeded, but some test actually failed.

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#436]
Example: #426 
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/426/kubeflow-presubmit/644/

**Comment by lluunn** [comment]
@jlewi @ankushagarwal

**Comment by jlewi** [comment]
@BenTheElder @krzyzacy Any ideas? [gubernator](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_kubeflow/426/kubeflow-presubmit/644/) shows the test as failed but the kubeflow-presubmit status check is reported as green on #426.

**Comment by BenTheElder** [comment]
Only Gubernator and testgrid read those metadata files. I'm going with your pod exited status 0 so Prow couldn't tell anything failed.

**Comment by lluunn** [comment]
https://github.com/kubeflow/tf-operator/blob/master/py/test_runner.py#L232

Exception was handled here

**Comment by jlewi** [comment]
@lluunn We check that there are no test failures here

https://github.com/kubeflow/testing/blob/ce2898e60a33c08ee79b9dfb61ca45db920f8370/py/kubeflow/testing/run_e2e_workflow.py#L274And we use that to 1 set the result in gubernator to failed and also set the exit status to non-zero.Do you know what that isn't working?

The prow job is running [run_e2e_workflow.sh](https://github.com/kubeflow/testing/blob/master/images/run_workflows.sh); so that's the process that needs to exit with non-zero exit code. test_runner.py is just a step in the workflow so causing that step to fail probably isn't sufficient.

I wonder if the problem is the exit code from run_e2e_workflow.py isn't propogating to run_workflow.sh.

**Comment by lluunn** [comment]
run_e2e_workflow determines the failure by the status of argo workflow. https://github.com/kubeflow/testing/blob/ce2898e60a33c08ee79b9dfb61ca45db920f8370/py/kubeflow/testing/run_e2e_workflow.py#L155

However, when some test fails, the workflow exits normally (after upload junit).

**Comment by jlewi** [comment]
@lluunn prow_artifacts.finalize_job checks the junit xml files to see if there are any errors and if there are marks the prow job as failed. It looks like that function should return success so that we can turn it into an exit code.
https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/prow_artifacts.py#L213

**Comment by jlewi** [comment]
@lluunn Ping?
