### ISSUE TITLE
Manage Contributors is case sensitive

### ISSUE THREAD

**Issue by Kyrremann** [kubeflow/kubeflow#4418]
/kind bug

When working with Manage Contributors we noticed that you need to write exactly the same casing as the e-mail is retrieved from our LDAP-server. Meaning that when I try to add a user writing the e-mail with all lower case it fails. Writing the e-mail with capital letter works.

Not working: kyrre.havik.eriksen@nav.no
Working: Kyrre.Havik.Eriksen@nav.no

Both should work.

**Environment:**
- Kubeflow version: v0.6.2
- kfctl version: v0.6.2-0-g47a0e4c7
- Kubernetes platform: on-premise
- Kubernetes version: v1.15.4
- OS: CoreOS

**Comment by yanniszark** [comment]
@Kyrremann keep in mind that the contributor UI will create K8s RBAC RoleBindings,in which the subject is case-sensitive.
So if you authenticate as `Kyrre.Havik.Eriksen@nav.no` but the RBAC RoleBindings mention `kyrre.havik.eriksen@nav.no`, it won't work.
Because of this, I think the validation check we have in place is valid and should not be relaxed.

/close
