### ISSUE TITLE
create namespace failed

### ISSUE THREAD

**Issue by songkane** [kubeflow/kubeflow#4429]
/kind question

**Question:**
the server does not allow this method on the requested resource (post profiles.kubeflow.org)

what should I do , and any logs that I can check?

![image](https://user-images.githubusercontent.com/15307785/67861065-6284a780-fb5a-11e9-84f9-9e30ed32c73c.png)

![image](https://user-images.githubusercontent.com/15307785/67860684-74b21600-fb59-11e9-9a5f-0c1338aeeb8c.png)
![image](https://user-images.githubusercontent.com/15307785/67860717-8abfd680-fb59-11e9-8656-f708f8050ce1.png)

**Comment by srados** [comment]
Hi,
I have the same issue, basically not able to use the UI because of this blocking screen.
After the kubeflow setup using https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/ I was able to log in as admin and see the UI. However, on the next run, UI shows for a second just to be replaced by this screen. I'm also not able to create a namespace.

**Comment by dagondagon666** [comment]
Hi,

I'm using `kfctl_istio_dex.v1.0.0.yaml` and have the same problem after logging in with admin credential for the first time.
