### ISSUE TITLE
NodeSelector spec to jupyter notebooks servers

### ISSUE THREAD

**Issue by taffarel-gaivota** [kubeflow/kubeflow#4433]
/kind feature

**Why you need this feature:**
To spawn notebook servers on specific group of nodes

**Describe the solution you'd like:**
Just being able to select what group of nodes by passing the NodeSelector spec

**Anything else you would like to add:**
If this feature already exists then someone could reference me where is in the documentation.

**Comment by shanidchamal** [comment]
[node feature discovery](https://github.com/kubernetes-sigs/node-feature-discovery) and [nvidia gpu feature discovery](https://github.com/NVIDIA/gpu-feature-discovery) automatically generates labels on hardware features and gpu features respectively. [AMD GPU Kubernetes Node Labeller](https://github.com/RadeonOpenCompute/k8s-device-plugin/tree/master/cmd/k8s-node-labeller) for AMD gpu. since nodes can be manually labelled with kubectl also, it is possible to spawn a notebook targeting nodes with specific features using nodeSelector. Current notebook creation ui doesn't have option to do so. [Enable GPU and TPU](https://www.kubeflow.org/docs/pipelines/sdk/gcp/enable-gpu-and-tpu/) describes the Kubernetes pod spec for pipelines using nodeSelector, gpu and tpu(in GKE). shouldn't it be available for notebook also via ui. ?

**Comment by taffarel-gaivota** [comment]
@shanidchamal thanks for the information. I dont necessary need to set the nodeSelector every time I create a notebook server. I mean to set this config when I install kubeflow or change something in the current setup to make all my new notebook server spawns at specific worker. 

This is will be great in conjuction with https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/aws setting an ASG for gpu type instance and so forth.

**Comment by Jude188** [comment]
This is a feature which we (not the royal, me and the company I work for) would dearly, dearly love too. Our use case is slightly different, however. We have a lot of very old hardware which is pre-AVX. This means that anything which needs Tensorflow will not run on the off-the-shelf Tensorflow container images as they require AVX. 

We do have a few nodes which do have the AVX instruction set and it would be great (really, kind of necessary) to be able to force the notebooks to run on these nodes.

**Comment by prcastro** [comment]
For the GPU use case we have the same need. Being able to add tolerations to certain node taints is also needed in our case. Maybe just add that to the `PodDefault`?

**Comment by tech348712013870132** [comment]
Please also take a look at: #4861
