### ISSUE TITLE
GCP config yaml spec.secrets.secretSource` is configured empty for basic-auth

### ISSUE THREAD

**Issue by sarjeet2013** [kubeflow/kubeflow#4439]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Hitting the following error when running kfctl apply with gcp config 0.7* yaml:
kfctl apply -- -V -f kfctl_gcp_basic_auth.0.7.0.yaml
```
INFO[0036] Creating GCP secrets for basic auth...        filename="gcp/gcp.go:1612"
ERRO[0036] There was a problem getting the password for basic auth; error No secret source provided for secret password  filename="gcp/gcp.go:1555"
INFO[0036] Error is not a KfError; No secret source provided for secret password  filename="apis/kferrors.go:59"
Error:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 520 with message: gcp apply could not create secrets Error cannot create basic auth login secret; No secret source provided for secret password
```

**What did you expect to happen:**
kfctl apply works fine and able to see the pods in running state.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I tried to debug the issue but not able to root cause the issue. The following env are set before kfctl is run.

KUBEFLOW_USERNAME=testuser
KUBEFLOW_PASSWORD=testpassword

Here is the excerpt from yaml:
```
secrets:
  - name: password
    secretSource: {}
```

Looking at the code, the above secretSource should have populated with the hashed password. 

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
0.7.0
- kfctl version: (use `kfctl version`):
kfctl v0.7.0-rc.5-20-g618c77be

- Kubernetes platform: (e.g. `minikube`)
GKE

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.14", GitCommit:"d7951e52ecdf56a1de9e031c553569ec13849a80", GitTreeState:"clean", BuildDate:"2019-10-11T23:17:57Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
I was able to reproduce this behavior using

kubeflow/manifests - v0.7.0-rc.2-16-gd6dad08
kubeflow/kubeflow - v0.4.0-rc.1-802-gd66f8b97

* Running `kfctl apply -v -f kfctl_gcp_basic_auth.yaml succeeded
  * I didn't get the error @sarjeet2013 mentioned above
* However, the secret source in my YAML is empty (see below)
* Running kfctl apply a second time results in the error listed above

```
ERRO[0027] There was a problem getting the password for basic auth; error No secret source provided for secret password  filename="gcp/gcp.go:1555"
INFO[0027] Error is not a KfError; No secret source provided for secret password  filename="apis/kferrors.go:59"
Error:  (kubeflow.error): Code 500 with message: coordinator Apply failed for gcp:  (kubeflow.error): Code 520 with message: gcp apply could not create secrets Error cannot create basic auth login secret; No secret source provided for secret password
```
* Editing the KFDef YAML file to have a secrets stanza like the following fixes things

   ```
   secrets:
   - name: password
     secretSource:
       envSource:
         Name: KUBEFLOW_PASSWORD
   ```

[kfctl_gcp_basic_auth.0.7.0.yaml.txt](https://github.com/kubeflow/kubeflow/files/3793788/kfctl_gcp_basic_auth.0.7.0.yaml.txt)

I see three bugs. 

* When filling in the defaults for basic auth [here](https://github.com/kubeflow/kubeflow/blob/41dd8167ff4171d6acf12822d19c571230cf04ce/bootstrap/pkg/kfapp/gcp/gcp.go#L1960) we store the secret as a hashed literal source

  * This is a bug; the secret should be stored as an environment source

* For EnvSource.Name capitalization is wrong in the json spec it should be `name` not `Name`
  *
https://github.com/kubeflow/kubeflow/blob/41dd8167ff4171d6acf12822d19c571230cf04ce/bootstrap/pkg/apis/apps/kfdef/v1beta1/application_types.go#L99

* ConfigConverters doesn't strip out literal sources [here](https://github.com/kubeflow/kubeflow/blob/41dd8167ff4171d6acf12822d19c571230cf04ce/bootstrap/pkg/apis/apps/configconverters/v1beta1.go#L143)

   * This is a bug; its not related to this issue
 
### Explanation

* We never want to serialize actual secrets into the KFDef spec file. This is because the KFDef file is intended to be stored in git and we don't want secrets in git

* So when we serialize KFDef we only want to allow references to secrets i.e. an ENVSource as opposed to a HashedSource or LiteralSource

* So in gcp.go when backfilling the default secret we should be using an EnvSource not a hashedSource

* Using a HashedSource and not an EnvSource explain why it works the first time you run kfctl apply because the secret is stored in memory

**Comment by sarjeet2013** [comment]
@jlewi 

This works for me. Can use it temporarily until the issue is fixed.

>> Editing the KFDef YAML file to have a secrets stanza like the following fixes things

secrets:
- name: password
  secretSource:
    envSource:
      Name: KUBEFLOW_PASSWORD

**Comment by jlewi** [comment]
I just deployed with basic auth using

kubeflow/kubeflow - v0.7.0-rc.7-3-g8dbde9d8
kubeflow/manifests - v0.7.0-rc.2-19-g317c0d8

Everything work so I'm marking this fixed.
