### ISSUE TITLE
Kubeflow - GKE installer will not allow node-pool API scope changes

### ISSUE THREAD

**Issue by timbuktuu** [kubeflow/kubeflow#4488]
/kind bug

As of KF 0.62, when created on GKE, the Cloud Deployment manager templates default to various default GCP API scopes.   One example is GCS API scopes being read-only, even if the underlying service accounts have the correct GCS permissions.   This blocks basic functionality such as a pipeline or notebook cell wishing to save results to GCS.   While it is possible to change API scopes on powered off [GCE VM's](https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/set-scopes), GKE node pools it seems to have to be destroyed and re-created.

An ideal workflow would allow new API scopes to be changed on a running cluster.

- Kubeflow version: 0.6.2
- kfctl version: 0.6.2
- Kubernetes platform: GKE
- Kubernetes version: 1.12.9-gke.15

**Comment by jlewi** [comment]
I believe this is working as intended and has been the behavior for the longest time. 

The recommended practice with GKE is not to rely on the VM service account to provide GCP credentials to pods because all pods would end up with the same credentials.

The recommended approach is to use workload identity which is now supported in 0.7.0 or to attach a GCP service account by mounting a GCP secret which is supported in 0.6.2

Please see
https://www.kubeflow.org/docs/gke/authentication/

**Comment by NikeNano** [comment]
As I understand this related to the underlaying VM_OAUTH_SCOPES scope @jlewi (but I am still very new and might be wrong)? If such supplying a new sevice account want help since the VM_OAUTH_SCOPES restricts the VM. 

@timbuktuu as I understand you can not change the underlying VM_OAUTH_SCOPES on a running resource in GCP and it is note related to GKE but rather GCE which has this limitation. Instead it needs to be redeployed after changes have been made to ```cluster.jinja```in the gcp_config folder. 

I think read and write would be awesome as default, I am new to Kubeflow and have had a lot of problems with this.

**Comment by NikeNano** [comment]
I would be happy to make a contribution to make it read_and_write if it makes sense?

**Comment by jlewi** [comment]
Appreciate that. I don't think we want the VM service accounts to be read-write by default. We want to have minimal permissions necessary. The primary reason the VM service account needs access to storage is to pull images. So read only permission should be fine.

The recommended way to give individual pods access to GCP APIS is using workload identity.
See
https://www.kubeflow.org/docs/gke/authentication/
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by NikeNano** [comment]
Ahh cool! Learnt something new :)
