### ISSUE TITLE
Improving Security on Kubeflow

### ISSUE THREAD

**Issue by elviraux** [kubeflow/kubeflow#4589]
In the past year we’ve been seeing an increasing demand in Kubeflow security.
This issue aims to cover following topics:

- [ ] Vulnerability image scanning and report #3907 

- [ ] Create a common base image for Kubeflow - possible distroless for operator images. #4590

- [ ] Reduce the size of images

- [ ] Documentation

- [ ] Propose maturity framework for applications going v1.0 with respect to security

- [ ] Remove default passwords and convert them to secrets

**Comment by elviraux** [comment]
@krishnadurai @swiftdiaries @jlewi

**Comment by krishnadurai** [comment]
@jtfogarty we could start tracking the image names and CVEs from this report.

[Kubeflow_images_cves_list.xlsx](https://github.com/kubeflow/kubeflow/files/4069971/Kubeflow_images_cves_list.xlsx)

**Comment by Naveenlbg** [comment]
Hi Team,

I am new to kubeflow, I am trying to install kubeflow in gcp in Kubernetes cluster.
Since in my organization image scan is enabled i have to fix all the vulnerabilities , Is there any kubeflow version I can use without any vulnerabilities?

I am following the guide to install https://www.kubeflow.org/docs/gke/customizing-gke/ 
Is there any timeline when a new version is released without any vulnerabilities.

Thanks & Regards,
Naveen

**Comment by Naveen-Jayaram** [comment]
Hi Team,

I am new to kubeflow, I am trying to install kubeflow in gcp in Kubernetes cluster.
Since in my organization image scan is enabled i have to fix all the vulnerabilities , Is there any kubeflow version I can use without any vulnerabilities?

I am following the guide to install https://www.kubeflow.org/docs/gke/customizing-gke/
Is there any timeline when a new version is released without any vulnerabilities.

Thanks & Regards,
Naveen

**Comment by jlewi** [comment]
@Naveen-Jayaram we are moving most of the Kubeflow docker images to be based on the distroless docker images which should fix many (but possibly not all vulnerabilities) (see kubeflow/community#321).

Can you open up specific issues about individual images? That will help us track and fix.

**Comment by jlewi** [comment]
@elviraux What is the status of this issue? Can we close it in favor of the other issues?
