### ISSUE TITLE
Kubeflow v0.7.0 kfctl show is not working; make show a beta/alpha command

### ISSUE THREAD

**Issue by md-shabbir** [kubeflow/kubeflow#4592]
/kind bug

**What steps did you take and what happened:**

Ran following commands to generate and see kubeflow application
```
$ kfctl build -V -f kfctl_k8s_istio.0.7.1.yaml
$ kfctl show
Error: couldn't load KfApp:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file: config file must be the URI of a KfDef spec
Usage:
  kfctl show [all(=default)|k8s|platform] [flags]

Flags:
  -h, --help      help for show
  -V, --verbose   verbose output default is false

couldn't load KfApp:  (kubeflow.error): Code 400 with message: Error creating KfApp from config file: config file must be the URI of a KfDef spec
```
Command ```kfctl show``` is failing.

**What did you expect to happen:**

```kfctl show``` should create yaml manifests of kubeflow application.

**Environment:**

- Kubeflow version: 0.7.0
- kfctl version: 0.7.0
- Kubernetes version: v1.15.3
- OS: Ubuntu 18.04.3 LTS (Bionic Beaver)

**Comment by jlewi** [comment]
@gabrielwen @kkasravi was show ever implemented? Should we remove the command?

**Comment by kkasravi** [comment]
It exists in coordinator which then tries to call any platform implementing Show - but none do.
So yes

**Comment by jlewi** [comment]
Bump to P0 because I think we need to figure out what we are doing for 1.0.

It seems like show may not be completely working/implemented.
Supporting show is not not critical for 1.0 

So here are my suggestions

1. Guard show with some sort of "beta" or "alpha" flag so the syntax would be

    ```
    kfctl beta show ...
    ```
    
    * So its clear the command is in beta and not fully supported.

    * How is this to support with our existing CLI tools?

1. Remove the show command for now.

I think it would be advantageous to introduce an `alpha` or `beta` sub command so we can introduce and experiment with new commands.

**Comment by jlewi** [comment]
I think we still need to cut an RC with #201 in it. Once we've cut the RC we can close this issue.

**Comment by richardsliu** [comment]
Verified in latest RC.
/close
