### ISSUE TITLE
How to update notebook container to privileged mode

### ISSUE THREAD

**Issue by Felihong** [kubeflow/kubeflow#4666]
/kind question

**Question:**
How to update the container `securityContext` to `privileged` in a running pod. 
I would like to use `gcsFUSE` to mount files from existing gcs bucket. For this, as many people already mentioned, I have to ensure that my notebook container runs in a privileged mode. 

**What I tried**
I tried to patch the following contents to the existing `notebook Statefulset`:
```
securityContext: 
   privileged: true
   capabilities:
    - add: SYS_ADMIN
```
which returns a message of `statefulset.apps/notebook-test patched`. However nothing was updated, the statefulset remains the same and the container was also not upgraded to privileged mode. 

I also failed to modify the pod directly as the relevant field is no longer possible to be updated. 

**Environment**
Kubeflow 0.7 hosted in GKE 

I have been struggling with this issue for a long time, it would be very appreciated if someone could finally point me out how to manage this. Thanks in advance! ☺️

**Comment by yanniszark** [comment]
Hi @Felihong!
Your changes do go through but the reason it seems like it doesn't change is because the notebook controller reconciles it immediately and restores it to the previous value.

To work around this, you could temporarily disable the notebook controller with:
```bash
kubectl scale deployment --replicas 0 -n kubeflow notebook-controller
```

However, we would like to find a way to allow using gcsFUSE with a normal, non-privileged user.
In stricter environments, normal users cannot be running privileged containers.

cc @jlewi since this concerns GCS.

**Comment by Felihong** [comment]
Hey @yanniszark , thanks a lot for your suggestion! 
I modified the statefulset after the notebook controller is scaled to 0, all changes can be now stored and fuse works well, thanks for pointing out. 

I also noticed that once I re-scaled the deployment, the modified contents are restored to the previous version, however without a controller, users are unable to spawn a new server so this seems for now, a temporal solution as you already mentioned. 

Still glad to finally find out why, and I'm very looking forward to the further progress on this.

**Comment by jlewi** [comment]
Can we mark this issue fixed?

**Comment by yanniszark** [comment]
@jlewi I don't think we can, there is currently no way to create a privileged Notebook Pod.
In order to resolve the issue, we need to find a good way to support @Felihong 's use-case, which is using `gcsFUSE`.

This can happen by:
* Allowing the user to specify a privileged securityContext for the Notebook. I believe that the Notebook Controller supports setting the securityContext. @lluunn does that hold? If yes, then this is a matter of exposing it through the UI.
* Finding a way to use `gcsFUSE` in a non-privileged way.

**Comment by Felihong** [comment]
Hi @yanniszark , not quite sure what you mean by notebook object? 
I tried to patch the modification via `PodDefault`, which doesn't seem to change anything.
```
API Version:  kubeflow.org/v1alpha1
Kind: PodDefault
Spec:
  Desc:  set privileged mode
  Security Context:
    Privileged:  true
    Capabilities:
      - add: SYS_ADMIN
  Selector:
    Match Labels:
      Run-As-Privileged:  true
```
Does podDefault only support fields like `environments` etc. ?

**Comment by kunmingg** [comment]
Hi Feihong,

The notebook statefulset is owned by a notebook CR:
https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller

You can view them by 
`kubectl get Notebook <your_notebook_name> -n <your_namespace> -o yaml`
The `spec` inside Notebook CR defines the `spec` of the statefulset.

You can add `securityContext` to the Notebook `spec` by
`kubectl edit Notebook <your_notebook_name> -n <your_namespace>`,

and the change will be applied to statefulset automatically.

(Need to undo the `--replicas 0` change so controller can resume)

**Comment by Felihong** [comment]
Hey @kunmingg , thanks for pointing out! 

I edited the notebook object directly and it works fine. Is there any possibility to configure the security context before notebook creation?
Anyhow it will be nice if users can be allowed to specify a privileged container mode before launching the notebook in the upcoming release :)

**Comment by jlewi** [comment]
I think @kunmingg 's suggestion of creating the notebook resource via the CLI is the right way to go.

I'm not sure its worth exposing in the UI. I guess it depends on how common setting the security context is. For complete control you can just use the API & CLI

/cc @kimwnasptd

**Comment by h4gen** [comment]
Hi @jlewi, @yanniszark . I share @Felihong's opinion that this is totally worth it, to expose to the user in the UI. 

I think mounting buckets is a really powerful feature for a lot of different scenarios. To enable the responsible Data Scientist to create a resource which is capable to do so, looks like a no-brainer to me. 

To ask an administrator to manipulate notebook resources seems to add a lot of unnecessary manual overhead and DS are not able to create this state themselves. Even if they could do so via CLI it would not really fit the competence of a typical DS. 

Another way would be the general manipulation via `PodDefault` but this would assume that the `notebook-controller` does not supress those settings.

**Comment by tvkpz** [comment]
Hi @kunmingg @Felihong 

I am new to Kubeflow. I am trying to start a docker daemon inside one of the notebook servers to be able to create other docker images. Although the daemon says it started when I do docker start, I cannot run any docker command as it throws a msg daemon is not started. 

I found out I need to run docker with --privileged flag for the notebook server to be able to run docker inside it. I have a few other notebook servers running in my cluster. Can you help list out the steps I need to take for stopping the notebook controller, changes I need in the SecurityContext and what is the instruction for restarting the notebook controller so that the work in the other notebook servers are not lost (disrupted is ok). Thanks!

**Comment by Felihong** [comment]
Hi @tvkpz , 

you could temporally disable the notebook controller by
```
kubectl scale deployment --replicas 0 -n kubeflow notebook-controller-deployment
```
And injecting the following snippet into the yaml file to let container run in privileged mode:
```
securityContext: 
   privileged: true
   capabilities:
    - add: SYS_ADMIN
```

Hope this would be helpful to you.

**Comment by tvkpz** [comment]
@Felihong I am not able to save the changes to the yaml file. I keep getting the message 
```
error: notebooks.kubeflow.org "nbs-1" is invalid
```
when I try to edit the notebook object directly using 
```
kubectl edit Notebook nbs-1 -n test-workspace
```
although I can see the notebook details in the above workspace when I do
```
kubectl get notebooks nbs-1 -n test-workspace -o yaml
```
Any advice?

**Comment by summerisc** [comment]
I am also seeing `mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first` error when try to fuse mount inside the container. 
![Screen Shot 2021-03-19 at 9 10 23 PM](https://user-images.githubusercontent.com/21230663/111854790-86838d00-88f7-11eb-8bdf-d47927161fa8.png)
already patched securityContext to the notebook, not sure if there is anything missing for me. Any insights are greatly appreciated!

**Comment by RichardPinter** [comment]
Any news on this? Would be great if we get inject custom security context with PodDefaults. For some reason this now work. I really don't want to go and play with golang, but if I had to I might just do it.
