### ISSUE TITLE
Log out option in Kubeflow multi-user mode.

### ISSUE THREAD

**Issue by vaskokj** [kubeflow/kubeflow#4702]
/kind feature

**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]

After installing Kubeflow through this guide (https://www.kubeflow.org/docs/started/k8s/kfctl-existing-arrikto/), I cannot for the life of me figure out where a simple "Logout" button is. The only workaround I have been able to come up with is to simply reset my browsers cache.  

Am I missing it? Or is there not a logout?

**Comment by yanniszark** [comment]
This is something we need as well and I have been experimenting with the implementation, so I'll take this one.
/assign @yanniszark

**Comment by jlewi** [comment]
@yanniszark What would it mean to logout? Do you mean clearing the Dex/IAP cookies?

IAP has a URL users can go to to clear their cookie.
https://cloud.google.com/iap/docs/special-urls-and-headers-howto


I would assume you need to be "logged in" in order to access all KF resources.

**Comment by yanniszark** [comment]
>What would it mean to logout? Do you mean clearing the Dex/IAP cookies?

For dex, we navigate to `/logout`, which is a special authservice path.
The authservice clears the user sessions and unsets the cookie.

For IAP, I see that you need to go to `/_gcp_iap/clear_login_cookie`.
I suspect it does something similar behind the scenes.

The pattern seems to be that you logout by going to a special logout URL.
Because of that, it seems a good idea to make this part of the CentralDashboard configuration (eg via an environment variable).
That way, each platform can define the URL that works for them.

**Comment by aychang95** [comment]
Is there a scheduled log out timer? I'm using the istio/dex Kubeflow build and am extracting the `authservice_session` cookie/token for authenticating requests for my seldon endpoints.

It seems like the value changes after every logout/login due to the clearing of cookies. Is there an easy way to make the cookies constant?

**Comment by yanniszark** [comment]
Hi @lomori, support for this feature was merged in https://github.com/kubeflow/kubeflow/pull/5174
