### ISSUE TITLE
Jupyter UI shows error while waiting for pod to bind PVC

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4705]
/kind bug

**What steps did you take and what happened:**
Created a Notebook Server using Rook/Ceph as the storage layer.

Pod created but the UI shows a red X in the status.  

![Screen Shot 2020-01-30 at 2 20 05 PM](https://user-images.githubusercontent.com/6708730/73487270-43213480-436c-11ea-8bf9-a91892cfa9d6.png)

**What did you expect to happen:**
Pod to start without issue

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard):
- kfctl version:  v1.0-rc.1-0-g963c787
- Kubernetes platform: v1.15.7
- Kubernetes version: v1.15.7
- OS (e.g. from `/etc/os-release`): NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by jtfogarty** [comment]
The pod eventually starts and the status turns green

**Comment by yanniszark** [comment]
@jtfogarty is this still an issue?
I suspect this is because the Rook (Ceph) provisioner is taking some time to provision the Persistent Volume, so in the meantime you get this message.

**Comment by jlewi** [comment]
Downgrading to P1 because this doesn't seem like its release blocking.

**Comment by jtfogarty** [comment]
@yanniszark Yes, this is still an issue

**Comment by jlewi** [comment]
I observed the same behavior on GCP using the default storage class (not ROK).

Bump back to P0; I think this is going to confuse a lot of people.

@fediazgon @kimwnasptd Is this related to the changes in the UI to surface events? Is there an easy way to show something less confusing to users?

**Comment by fediazgon** [comment]
Yes, it is related to [this change](https://github.com/kubeflow/kubeflow/pull/4214/files#diff-d575d8cda5f10ed63f52ac8e7a65b733R328). Right now the UI shows that status when the event matches the following predicate `eventType == 'Warning' and eventReason in ["FailedCreate", "FailedScheduling"]`.

One solution would be to limit the events that are shown by looking at the event's description. @kimwnasptd WDYT?

**Comment by jlewi** [comment]
@fediazgon thanks. What if we just returned STATUS_WAITING rather than STATUS_ERROR
https://github.com/kubeflow/kubeflow/pull/4214/files#diff-d575d8cda5f10ed63f52ac8e7a65b733R329

I guess the downside is that we might get stuck in waiting mode even for permanent errors. But that seems preferable to always showing an error.

**Comment by kimwnasptd** [comment]
I'm also in favor of @fediazgon 's proposal. I think returning STATUS_WAITING will take us back from where we started when we would show the spinner even if the underlying Pod would fail to be created.

Looking at the description of the events seems a little dirty and in the future we might bump into another event that we hadn't anticipated and need to extend the description pattern matching.

But given the current API I think its our only option if we want to be able to treat specific Warning Type Events as non warning/error ones.

**Comment by fediazgon** [comment]
I think we can do both. We can be explicit about the error events that we are expecting and, if we find any unknown error event we just return STATUS_WAITING but we still show the message in the UI.

I tried to replicate the behaviour in GCP using the default storage class, with the changes in https://github.com/kubeflow/kubeflow/pull/4729, now it shows like this:

![Screenshot 2020-02-05 at 13 51 41](https://user-images.githubusercontent.com/12219405/73843649-4fe7d180-481f-11ea-9e38-ce248549cdbb.png)

But it will still display "Insufficient X" or "error looking up service account" as STATUS_ERROR.

**Comment by jlewi** [comment]
*  Will we be able to do a good job distinguishing permanent from temporary errors?
*  Don't we ultimately need to surface events to the user so they can remedy the situation? So rather than trying to classify events as warnings or errors; shouldn't we focus on them?

If Kubernetes is classifying it as a warning and not an error, should we be treating it as an error? 

Here's my failed pod
[jlewi-0.pod.txt](https://github.com/kubeflow/kubeflow/files/4159468/jlewi-0.pod.txt)

In this case the event is 

```
  Warning  FailedScheduling        18m (x2 over 18m)  default-scheduler                                             pod has unbound 
immediate PersistentVolumeClaims (repeated 2 times)
```

I'm using a default storage class so this will get provisioned automatically. However, if a user attaches an existing PVC or deletes a PVC wouldn't they get similar events? How would you distinguish between a PVC that will eventually get bound and a PVC that will never get bound?

Similarly, in the case of FailedScheduling if a POD doesn't get scheduled because of CPU that might be permanent or if a user has autoscaling enabled they might just need to wait for autoscaling to kick in.

Trying to correctly classify errors based on the message seems like we could end up playing wack a mole.

Would a better medium (i.e. post 1.0) solution be to provide an improved UI to see all events for a notebook?

Going back to the original issue #3673 the goal was to surface errors to the user so they could figure out to fix it. So I think we need to surface the events to the user.

I think right now we accomplish that because if they hover over the spinner they see the message as @jtfogarty shows in his screenshot.

So I think if we showed the waiting icon with the same pop instead of an error we achieve the same goal without confusing users.

**Comment by fediazgon** [comment]
> Trying to correctly classify errors based on the message seems like we could end up playing wack a mole.
> 
> Would a better medium (i.e. post 1.0) solution be to provide an improved UI to see all events for a notebook?

Sounds fine to me. Let's keep it simple then.

**Comment by jlewi** [comment]
Confirmed this is working on master now
https://github.com/kubeflow/manifests/tree/830e1a0

![unbound_claim](https://user-images.githubusercontent.com/777219/73882705-62f6a380-4817-11ea-9f8e-6d4a3a20ca06.png)


Will LGTM the cherry pick into the 1.0 branch.

**Comment by jlewi** [comment]
https://github.com/kubeflow/manifests/pull/868

Just need to wait for it land in auto-deployed cluster so I can verify on 1.0.

**Comment by jlewi** [comment]
v1
https://github.com/kubeflow/manifests/tree/7abafe2


Looks good
![v1_unbound_claim](https://user-images.githubusercontent.com/777219/73889480-a4da1680-4824-11ea-998f-30ea1a0bb596.png)
