### ISSUE TITLE
[auth] application_secret exposed in configmap

### ISSUE THREAD

**Issue by Oblynx** [kubeflow/kubeflow#4855]
/kind bug

**What steps did you take and what happened:**

I applied the default `kfctl_istio_dex.yaml` configuration and realized that the OIDC client secret, used by the `authservice-0` pod to retrieve the id_token from my OIDC provider, is stored in a configmap and not in a secret. Specifically in `istio-system/oidc-authservice-parameters`.

**What did you expect to happen:**

To store the client secret in a secret. I'm integrating kubeflow on-prem with an external OIDC provider.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): v1.0.0
- kfctl version: (use `kfctl version`): v1.0-0-g94c35cf
- Kubernetes platform: (e.g. `minikube`): vanilla (openstack magnum)
- Kubernetes version: (use `kubectl version`): v1.15.3
- OS (e.g. from `/etc/os-release`): Fedora 29.20181126.0 (Atomic Host)

**Comment by yanniszark** [comment]
Thanks for opening up an issue.
This is because of a Dex limitation.
It doesn't support getting the app secret from an environment variable or a file, so it is included inside its configmap. (https://github.com/dexidp/dex/issues/1099)
However, I can see there was a recent improvement on that front: https://github.com/dexidp/dex/pull/1664

I see two ways for resolving this issue:
1. Use environment variables if Dex allows it now (https://github.com/dexidp/dex/pull/1664).
2. Use an init container to render the Dex configuration.

**Comment by jbottum** [comment]
@Oblynx Hi Konstantinos - We have not found a resource to work on this in the Kubeflow 1.1 timeframe.   What is your priority for this enhancement?

**Comment by Oblynx** [comment]
Hi, thanks for checking in!
Leaking the OIDC secret could help malicious tenants compromise the deployment. For small scale deployments with select users this isn't a big concern, but we are considering a production deployment by late September where mitigation will be necessary.
