### ISSUE TITLE
How is google/cloud-sdk:alpine built

### ISSUE THREAD

**Issue by jtfogarty** [kubeflow/kubeflow#4887]
/kind question

**Question:**
I'm looking for information on how this image is built.  Can it be converted to distroless? 

Reference issue is [Convert Container image to distroless #4590](https://github.com/kubeflow/kubeflow/issues/4590)

**Comment by jtfogarty** [comment]
@ankushagarwal 
@jlewi 
@krishnadurai

**Comment by jlewi** [comment]
We don't manage this image. I have no information on how its built.

Where is this image being used in Kubeflow?

**Comment by jtfogarty** [comment]
It is in 
[components/ingress-setup-image/Dockerfile](https://github.com/kubeflow/kubeflow/blob/master/components/ingress-setup-image/Dockerfile)

**Comment by jlewi** [comment]
Ah. That gets used to run this script
https://github.com/kubeflow/manifests/blob/bba06d9ca63caa800c9bf97f9a93b62ec671e747/gcp/iap-ingress/base/config-map.yaml#L48

That is probably the right image to use for that script because we are running gcloud so we should use one of the official gcloud images.

It looks like there is a public repo for that image here:
https://github.com/GoogleCloudPlatform/cloud-sdk-docker

If there are issues with that docker image you could file images in that repo to try to get them fixed in the upstream repo.

Alternatively we could rewrite the bash script in go and switch to a distroless image.
