### ISSUE TITLE
How to access to Pipeline API with Dex Auth on

### ISSUE THREAD

**Issue by dagondagon666** [kubeflow/kubeflow#4912]
/kind question

**Question:**

I deployed Kubeflow with kfctl_istio_dex.v1.0.1.yaml. I'm trying to access the Pipeline API but I'm blocked with the Dex Authentication. I'm wondering where could I get the token to authorize my request?

Connected Issue here since I'm not sure which repo does this question belong to:
https://github.com/kubeflow/pipelines/issues/3426

**Comment by Bobgy** [comment]
If you want to access the endpoint from outside of the cluster, you might need change in kfp client similar to https://github.com/kubeflow/pipelines/pull/2679. You need to know how to authenticate http requests to the dex endpoint.

If you want to access the endpoint from inside the cluster, kfp api server has in-cluster hostname like `ml-pipeline.kubeflow.cluster.local:8888` (without auth protection if you didn't enable istio sidecar).

@Ark-kun can we use the same approach in https://github.com/kubeflow/pipelines/pull/3976 to allow generic authentication configuration to kfp client?

cc @maganaluis

**Comment by dagondagon666** [comment]
Where could I get the cookie? 
TBH I would prefer using the generic authentication but using username + password just seems a bit weird to me...

**Comment by Bobgy** [comment]
Hi @dagondagon666 ! I'm not an expert on tech details for these, just pointing to efforts that could be related. 

Do you know how a normal https request to that endpoint should be authenticated?
I didn't mean the generic authentication was username + password, just guess generic auth module might be able to handle dex with some configurations.

**Comment by maganaluis** [comment]
@Bobgy This could work when using the client outside the cluster or given that you provide the host when running from a POD. This makes sense that way Dex will set the identity headers, I will test it out and post back on Slack.

**Comment by dagondagon666** [comment]
@Bobgy Right now I actually set `pipeline` to skip auth. I think this is what was suggested as walk around for either pipeline or kfserving.

**Comment by Bobgy** [comment]
> @Bobgy Right now I actually set `pipeline` to skip auth. I think this is what was suggested as walk around for either pipeline or kfserving.

Did you set public `/pipeline` endpoint to skip auth? I hope you are not doing that, that's really a security risk.

**Comment by shawnzhu** [comment]
I'm trying to access pipeline API from Kubeflow v1.0.2 with [`kfdef_istio_dex.v1.0.2.yaml`](https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.2.yaml) via the `istio-ingressgateway.istio-system.svc`. I extracted the cookie session entry `authservice_session` after successfully authentication via dex from web UI.

```Python
>>> import kfp
>>> import os
>>> kfp.__version__
'1.0.0'
>>> host = 'xxxxxxx.us-east.containers.appdomain.cloud'
>>> client = kfp.Client(host=host, existing_token=os.environ['AUTHSERVICE_SESSION'])
>>> client.list_experiments()
...
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xxxxxxx.us-east.containers.appdomain.cloud', port=443): Max retries exceeded with url: https://xxxxxxx.us-east.containers.appdomain.cloud/dex/auth/github?req=ia4isgbc2d63vtd3wdiv5hagb (Caused by ResponseError('too many redirects'))
```
However, the request went through via a special header `X-Auth-Token`:

```SHELL
curl -I -H "X-Auth-Token: $AUTHSERVICE_SESSION" "https://xxxxxxx.us-east.containers.appdomain.cloud/pipeline/"
HTTP/1.1 200 OK
Date: Wed, 29 Jul 2020 01:47:31 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
x-powered-by: Express
x-envoy-upstream-service-time: 2
```

## Conclusion

If using the argument `existing_token` which will be sent via request header `Authorization`, it must let this header go through in kubeflow deployment with dex. Based on this PR (https://github.com/arrikto/oidc-authservice/pull/25), it needs to upgrade the image `gcr.io/arrikto/kubeflow/oidc-authservice` and replace `X-Auth-Token` with `Authorization` from envoyfilter.

It might bring break change since I've seen the special header `X-Auth-Token` has been used in jupter-webapp (see https://github.com/kubeflow/kubeflow/blob/dcaeee742984533a2aff34bb28e14ea5aa9ae74a/components/jupyter-web-app/frontend/src/app/uis/rok/services/rok.service.ts#L46)

comments are welcome!

**Comment by maganaluis** [comment]
> authservice_session

@shawnzhu We are using the cookies parameter and passing the authservice_session cookie, we're letting the OIDC service setup the correct headers. What would be the benefit of using existing_token in this case?

**Comment by shawnzhu** [comment]
> We are using the cookies parameter and passing the `authservice_session` cookie

That's what I used as well so far but just for getting it working. Technically a secure cookie should not be shared with another process besides browser, it will bring manual effort to copy such sensitive info into a notebook for KFP client.

> What would be the benefit of using `existing_token` in this case?

The key difference here is the value of `existing_token` will be sent via a request header `Authorization` (more specific) instead of cookie (depends on implementation specific cookie name), which is encouraged by the OIDC-authservice + dex path for api clients. see https://github.com/arrikto/oidc-authservice/pull/25

**Comment by maganaluis** [comment]
@shawnzhu Makes sense, how are you getting the token into the env variable ```AUTHSERVICE_SESSION```? In our case we configured Dex to use an internal OpenID authentication service. I've been looking for a way for users to execute Kubeflow pipelines notebooks locally without additional service accounts, which use to get those cookies.

**Comment by shawnzhu** [comment]
> how are you getting the token into the env variable `AUTHSERVICE_SESSION`? 

don't what env variable `AUTHSERVICE_SESSION` is for. If you're talking about where to get an existing token for the argument `existing_token` of `kfp.Client()`, based on https://github.com/arrikto/oidc-authservice/pull/25 it should be the value of cookie entry `authservice_session`.

> I've been looking for a way for users to execute Kubeflow pipelines notebooks locally without additional service accounts, which we use to get those cookies.

A token for `kfp.Client()` will be from a service account (e.g., `client_id` + `client_secret` from the path for GCP deployment) or a human account (e.g., using `cookies` now). What I want to do is sticking with `existing_token` instead of `cookies` to clarify the semantic, then looking for enhancement to the repo `arrikto/oidc-authservice` on how to create a session for a service account instead of re-using human account's cookie.

**Comment by maganaluis** [comment]
> > how are you getting the token into the env variable `AUTHSERVICE_SESSION`?
> 
> don't what env variable `AUTHSERVICE_SESSION` is for. If you're talking about where to get an existing token for the argument `existing_token` of `kfp.Client()`, based on [arrikto/oidc-authservice#25](https://github.com/arrikto/oidc-authservice/pull/25) it should be the value of cookie entry `authservice_session`.
> 
> > I've been looking for a way for users to execute Kubeflow pipelines notebooks locally without additional service accounts, which we use to get those cookies.
> 
> A token for `kfp.Client()` will be from a service account (e.g., `client_id` + `client_secret` from the path for GCP deployment) or a human account (e.g., using `cookies` now). What I want to do is sticking with `existing_token` instead of `cookies` to clarify the semantic, then looking for enhancement to the repo `arrikto/oidc-authservice` on how to create a session for a service account instead of re-using human account's cookie.

@shawnzhu We are leveraging the Dex API to create an Service Account https://github.com/dexidp/dex/blob/master/Documentation/api.md perhaps adding and enhancement to the OIDC is the better approach here, but I'm not entirely familiar with it.

**Comment by Bobgy** [comment]
I think you found your solution, is that right?

**Comment by tomalbrecht** [comment]
I am looking for the same solution. Can someone point me to it? As @Bobgy explained [here](https://github.com/kubeflow/kubeflow/issues/4912#issuecomment-652184977) skipping the authentication is apparently not a good solution. But what is the preferred solution to authenticate kfp cli to run with on OnPremise with istio/dex?

**Comment by HassanOuda** [comment]
@maganaluis Hi Luis, can you explain a little bit on how you did this approach? Thanks

**Comment by thesuperzapper** [comment]
Because this issue seems to come up on Google for Kubeflow Pipelines SDK auth issues, I want to point people toward the upstream docs on how to do this.

Specifically, you can find the information and code examples on the ["Connect the Pipelines SDK to Kubeflow Pipelines"](https://www.kubeflow.org/docs/components/pipelines/v1/sdk/connect-api/) page under the `"Full Kubeflow (from outside cluster)"` heading.

My only other tip is that you should catch errors when calling methods like `kfp.Client.list_experiments()` to handle the case that your session lasts long enough for your cookie to expire (and re-auth in that case).
