### ISSUE TITLE
Open Data Hub & Kubeflow relationship

### ISSUE THREAD

**Issue by vpavlin** [kubeflow/kubeflow#4916]
/kind question

Hi all,

As some of you already know we are working on getting Kubeflow running on OpenShift - Red Hat’s enterprise Kubernetes distribution. We had successfully deployed KF 0.7 and will be looking more closely at 1.0 soon.

Up until now we were also developing a reference architecture AI platform for OpenShift called Open Data Hub (ODH). It was based on Ansible Operator SDK and it integrated selected AI/ML and Data Engineering tools - similar to what Kubeflow does. Since our engagement in Kubeflow community we pondered an idea how can we bring these two projects closer together and we formulated a plan to “rebase ODH on top of Kubeflow” a couple of weeks ago.

That essentially means we will reuse Kubeflow deployment tools (kfctl, KF operator, Kustomize) and port our Open Data Hub components and tooling to be compatible with them - see this work in progress here: https://github.com/opendatahub-io/odh-manifests.

With that, we are planning on keeping the “brand” Open Data Hub and the Open Data Hub operator, but build it on top of Kubeflow operator. We also plan to propose our changes to Kubeflow, but in case some would not be accepted, we need a place where they can live.

For that we will add the Open Data Hub operator into [OpenShift Community Operators catalog](https://github.com/operator-framework/community-operators/tree/master/community-operators). At the beginning it will be basically a repackaged Kubeflow operator, but it might divert over time with our focus on OpenShift and integration of other Red Hat projects and products.

Any thoughts/feedback from the KF community?

@jlewi @animeshsingh @pdmack

**Comment by animeshsingh** [comment]
Thanks @vpavlin - excited about OpenDataHub rebase on top of Kubeflow Operator. A step in right direction!

Only concern is the duplication of code which will happen because of this, and usual sync issues between the core Kubeflow Operator and OpenDataHub Operator. Would it make sense to create a "specialized" KFDef for OpenDataHub, and we work together to ensure any changes needed to be accommodated for OpenDataHub are treated at a priority? This will also give the Kubeflow community a straightforward way to extend and upgrade to OpenDataHub, if there are interested in additional components (Kafka, Hive, Hue, Superset...) and/or features.

**Comment by jlewi** [comment]
This seems great to me. 

> We also plan to propose our changes to Kubeflow, but in case some would not be accepted, we need a place where they can live.

I think having your own "brand" and downstream clones makes a lot of sense. I generally think anyone providing an oppinionated, supported distribution will want to go this route. Even when changes will be upstreamed they may not be upstreamed at the pace an OEM needs.

I think we should try to figure out what we need to do in the upstream repo to make this better 
supported.

Some things that come to mind

* How should we organize/structure the config, to make it easy for people to add their oppinions, customizations on top of that?
* How can we enable providers to provide early signals that upstream changes will break downstream clones?

Furthermore, I think it will become more important to define the patterns/architecture that make it easy for people to add in additional applications. The two areas that some to mind are

* Networking - in particular what applications need to do in order to be accessible to users
* Multi-user - What applications need to do in order to fit into the multi-user pattern we are developing

**Comment by vpavlin** [comment]
This is great to hear!

Yeah, all the items are very valid.

We at least came up with a draft of a roadmap for Open Data Hub

Slides: https://gitlab.com/opendatahub/opendatahub-community/-/wikis/uploads/39b75e0eee79a059fffabbf0f38d77cf/ODH_Roadmap__draft_.pdf
Recording:  https://bluejeans.com/222067203

In general, we have community meetings and all the info can be found here: https://gitlab.com/opendatahub/opendatahub-community/-/wikis/Open-Data-Hub-Community-Meeting-Agenda

To your points

* organizations/structure - we are basically leveraging the ability to specify multiple repositories in KFDef right now, so that gives us enough flexibility to extend KF manifests (at least for now)
* signals - we'd be happy to present (regularly?) updates to our roadmap at KF community meetings if that helps. We are also planning to work on CI for KF and ODH on OpenShift, so if we can later plug into the Github PR bots, at least as "recommendation" if not a "blocker"

For the additional applications - definitely interesting topic as well, since the multitenancy model we have used in ODH so far is different than KF, so we'll definitely need to dig into how to bring those together.

@jlewi Is there anything you'd like to see me do with this issue? Share this issue on kf-discuss? Keep it open? Close it? I am not sure if there is any clear next steps for this - I mainly wanted to let you know what is going on on our side.

**Comment by jlewi** [comment]
Nothing on my end

**Comment by jlewi** [comment]
Thanks @vpavlin for the heads up.
