### ISSUE TITLE
Istio: Deploy with CNI plugin to avoid NET_RAW and NET_ADMIN capabilities

### ISSUE THREAD

**Issue by saschagrunert** [kubeflow/kubeflow#4941]
/kind feature

**Why you need this feature:**
I would like to avoid having those two capabilities in my cluster default Pod Security Policy (PSP).

**Describe the solution you'd like:**
If we deploy Istio with the [CNI plugin](https://istio.io/docs/setup/additional-setup/cni/), then we will not have a need for the `NET_RAW` and `NET_ADMIN` capabilities any more.

**Anything else you would like to add:**
Do you think this would be easily possible? Do you have any concerns about that?

**Comment by jlewi** [comment]
Which platform/KFDef are you installing ISTIO on?

While Kubeflow is providing an ISTIO install for convenience you should be able to install ISTIO yourself on your cluster and configure it how you want.

On GCP for example we are moving in the direction of using ASM to install and manage ISTIO rather than using a Kubeflow provided install and config.
