### ISSUE TITLE
GKE Deploy fails in Australia as no NVIDIA GPUs available unless we modify cluster.jinja

### ISSUE THREAD

**Issue by snowlover173** [kubeflow/kubeflow#4947]
/kind bug

**What steps did you take and what happened:**
Deployed Kubeflow 0.7, 1.0.0 and 1.0.1 , using the documentation for deploying Kubeflow with cli on GCP.
It failed with an error NVIDIA GPUs not available.
In gcp_config/cluster-kubeflow.yaml changed "gpu-pool-max-nodes" from 10 to 0 and it ran.

**What did you expect to happen:**
no error 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7, 1.0.0, 1.0.1
- kfctl version: accordingly
- Kubernetes platform: GCP
- Kubernetes version: 1.14
- OS (e.g. from `/etc/os-release`):

**Comment by jlewi** [comment]
Which zone did you try to use?

**Comment by jlewi** [comment]
I'm closing this as obsolete because with 1.1 we are switching to blueprints which will no longer use
deployment manager.
https://github.com/kubeflow/gcp-blueprints/tree/master/kubeflow

Blueprints use Cloud Config Connector to configure your GKE clusters and you can configure settings like node autoprovisioning using tools like kustomize to generate appropriate YAML specs.
