### ISSUE TITLE
Extend Tensorboard Controller to Support PVCs

### ISSUE THREAD

**Issue by kandrio98** [kubeflow/kubeflow#5039]
/kind feature

Currently, the Tensorboard controller does not fully support arbitrary PVCs being mounted to pods running the Tensorboard server. In fact, it can only support PVCs named [tb-volume](https://github.com/kubeflow/kubeflow/blob/4bf2d4131a5aebe0f1b53d36dd94031f88426c0b/components/tensorboard-controller/controllers/tensorboard_controller.go#L156-L164).

I would like to extend the Tensorboard controller so that it fully supports any PVC created by the user in the namespace of the Tensorboard object applied. This is actually a part of my [Google Summer of Code project](https://summerofcode.withgoogle.com/projects/#4660815581413376) for building a Tensorboard UI that also supports PVCs.

My proposition would be to extend the Tensorboard controller so that it obtains the name of the PVC by the `spec.logspath` field of the Tensorboard CR applied by the user. In detail, if a user wants to mount a PVC to a pod running the Tensorboard server, then the value of `spec.logspath` should follow the format: `pvc://{pvc-name}/{local-path}` (similar to what `kfserving` uses in its `InferenceService` CRDs). This way, I will be able to extend the code of the controller so that it creates a deployment that mounts the desired PVC to the pod running the Tensorboard server. 
The extended controller will also be backwards compatible.

cc @jlewi @kimwnasptd @elikatsis

**Comment by kandrio98** [comment]
I have extended the Tensorboard Controller so that it supports PVCs, as described above. 

Also, there is another problem, which is related to this [kubernetes issue](https://github.com/kubernetes/kubernetes/issues/26567). More specifically,  If we use a `ReadWriteOnce` PVC as a logdir for Tensorboard Server and the PVC is already mounted by another running pod P, then the Tensorboard Server pod will not always be scheduled on the same node as P. As a result, the Tensorboard Server pod gets blocked since multi-node access is prohibited on ReadWriteOnce volumes.

I think it is really important that PVCs with ReadWriteOnce access mode are fully supported, because ReadWriteOnce volumes are the most widely used volumes out there.

In order to fix the problem, I propose that `nodeAffinity` should be added to the `spec.template.spec.affinity` field of the Tensorboard Server deployment so that both pods are scheduled on the same node.

**Comment by jlewi** [comment]
> In order to fix the problem, I propose that nodeAffinity should be added to the spec.template.spec.affinity field of the Tensorboard Server deployment so that both pods are scheduled on the same node.

This feels like a bit of a brittle solution. My interpretation of `ReadWriteOnce` is that it should only be mounted on a single pod at a time. Trying to work around that seems like a brittle solution. 

Its not clear to me why supporting `ReadWriteOnce` is important. In general, the recommendation is to write event files to an appropriate objectstore (GCS, S3, HDFS, etc...). In which case you avoid issues with PVs altogether and can easily read from multiple pods.

If people really want to use PVs then it seems reasonable to require that either

1. They use a ReadWriteMany PVC in order to be able to mount it simultaneously on multiple pods
1. Live with the restrictions that a ReadWriteOnce pod supports

**Comment by kandrio98** [comment]
> Its not clear to me why supporting ReadWriteOnce is important. In general, the recommendation is to write event files to an appropriate objectstore (GCS, S3, HDFS, etc...). In which case you avoid issues with PVs altogether and can easily read from multiple pods.

Yes, supporting object stores is an option for storing/retrieving event files, but I think that PVCs provide an easier/more intuitive workflow for the end user. More specifically, users might prefer using PVCs instead of object stores because:
1) Object stores add complexity since they require a service to be configured/available in the cluster. 
2) In terms of ease of use, it is a lot simpler for users to just store their logs on a directory than pushing/pulling them to/from a service by making API calls or using libraries in their code.

Let's also not forget that users are already using PVCs, and mostly `ReadWriteOnce` ones, for storing their data and working with Notebooks and Pipelines. 

> My interpretation of ReadWriteOnce is that it should only be mounted on a single pod at a time. Trying to work around that seems like a brittle solution.

I think there might be a misunderstanding here. `ReadWriteOnce`  PVCs can be mounted by a single **node** at a time ([see docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)), not by a single **pod** at a time. This holds for GKE as well ([see docs](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#access_modes)). That said, mounting the same `ReadWriteOnce` PVC on multiple **pods** on the same **node** is actually a supported (and necessary for quite a few use cases) feature.

Now, the problem arises when pods, running on different nodes, try to access the same `ReadWriteOnce` volume. More specifically, If we use a `ReadWriteOnce` PVC as an event file storage for Tensorboard server and the PVC is already mounted by another running pod (e.g. the Notebook server) then the Tensorboard server will not always be scheduled on the same node as that pod ([kubernetes/kubernetes#26567](https://github.com/kubernetes/kubernetes/issues/26567)). As a result, the Tensorboard server pod gets blocked. So, we need to specify _preference_ that the `scheduler` should assign the Tensorboard server pod to the node that has mounted the `ReadWriteOnce` volume. And my proposed solution would be to use `nodeAffinity` for that task.

**Comment by jlewi** [comment]
> I think there might be a misunderstanding here. ReadWriteOnce PVCs can be mounted by a single node at a time (see docs), not by a single pod at a time.

I understand that. But in order to make this work you are suddenly forcing a bunch of pods to be scheduled on the same node which will likely lead to unexpected failures. e.g. suppose I start a TB pod and that is the first to schedule a PVC. TB doesn't really need GPUs so it gets scheduled on a node with no GPUs. Now I schedule a jupyter pod which requests the PVC and a GPU. So now you have conflicting scheduling constraints; you want to schedule on a different node with GPU but also schedule on the same node with the PVC.

> Yes, supporting object stores is an option for storing/retrieving event files, but I think that PVCs provide an easier/more intuitive workflow for the end user.

Managing disks is not what I would consider the recommended path for Cloud. In Cloud storing your data on GCS or S3 is recommended because

* Its elastic
* Cost effective
* Much more durable

PVCs are primarily used when dealing with legacy applications that don't speak object store. TensorBoard is not such an application. TensorBoard and TensorFlow can read/write to S3 and GCS directly.

Jupyter is a legacy application. The notebook gets stored on PVC because Jupyter doesn't know how to read/write GCS.

Looking at the TBSpec

https://github.com/kubeflow/kubeflow/blob/101c77a37c64791ce2b3e5a65c96622906202645/components/tensorboard-controller/api/v1alpha1/tensorboard_types.go#L27

The only field is logspath. This seems insufficient. 

* How would the user specify resource requirements?
* How would the user attach secrets?
* How would the user specify the version of TB to run?

It looks like a lot of this stuff is being hard coded
https://github.com/kubeflow/kubeflow/pull/5069/files

Compare this to the notebook resource: https://github.com/kubeflow/kubeflow/blob/101c77a37c64791ce2b3e5a65c96622906202645/components/notebook-controller/api/v1/notebook_types.go#L27
which contains a PodTemplateSpec.

See my comment here: https://github.com/kubeflow/kubeflow/issues/3578#issuecomment-653824466

Should we resolve that first?

**Comment by kandrio98** [comment]
Currently, the Tensorboard Controller provides very basic functionalities for PVCs. My proposition aimed at making the use of RWO PVCs a little easier for users. That said, the extra scheduling functionalities that I proposed could become optional. 

More specifically, we could add an enviromental variable, say `RWO_PVC_SCHEDULING`, to the Tensorboard CR Controller. This variable will be set to `false` by default. If a user wants Tensorboard Servers to be scheduled on the same node as a `RWO` `PVC` log storage, then the cluster admin could set `RWO_PVC_SCHEDULING` to `true`.

@jlewi what are  your thoughts on that?

**Comment by jlewi** [comment]
@kandrio98 See my comment https://github.com/kubeflow/kubeflow/issues/3578#issuecomment-655724933

Would that help us in terms of making progress to a long term goal of having a solid story for web apps? Or would it end up just end up being removed later?

If its just going to be removed later in favor of something more general (e.g. a pod template spec) is it still worth doing?

**Comment by kandrio98** [comment]
First of all, I really agree with your thoughts on creating a solid story for managing our stateful web apps in a cohesive way.

> Would that help us in terms of making progress to a long term goal of having a solid story for web apps? Or would it end up just end up being removed later?

I believe that this added scheduling functionality (even if optional) would be useful, currently and in the future. It would make it easier for users to use the Tensorboard web-app in the case that their event files are stored in a RWO PVC, regardless of the Custom Resource that we are using.

Also, since the implementation of this UX feature is part of my [GSoC proposal](https://summerofcode.withgoogle.com/projects/#4660815581413376), I have written the necessary code.

@jlewi what do you propose?
