### ISSUE TITLE
Many users - one namespace

### ISSUE THREAD

**Issue by AldusLorde** [kubeflow/kubeflow#5071]
/kind question

**Question:**
Hi) Is it possible to create several users in one namespace?

**Comment by yanniszark** [comment]
Hi @AldusLorde!
Yes it is possible to share a namespace with multiple users.
To do this via the UI, follow: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-through-the-kubeflow-ui
Does this answer your question?

/area multi-user

**Comment by AldusLorde** [comment]
@yanniszark thank you for the response. Kubeflow still asks me to create a namespace for a new user

**Comment by munagekar** [comment]
@AldusLorde Currently Kubeflow needs an owner namespace/profile for every user. This is a part of kubeflow's self-service. 

- A user can be an owner for several namespaces
- Every user must be the owner of at least one namespace
- A single namespace can have multiple contributors but just one owner

**Comment by SpontaneousDuck** [comment]
Is there any documentation on creating a new second namespace for a user? I could not find how to make a new namespace beyond the default created at first sign-in

**Comment by munagekar** [comment]
@SpontaneousDuck Namespace creation and deletion is handled by the profile controller. To create a new profile apart from the default one, you need to apply the manifest using kubectl. 
https://github.com/kubeflow/kubeflow/issues/4999#issue-613092391 
The comments on this issue show creation of a profile and adding other contributors.

**Comment by SpontaneousDuck** [comment]
Ahhh, so each namespace is a user then you just add multiple people to it. Thanks for the clarification! Does that also work if you are using LDAP/AD for authentication? Can you make users on top of the ones that are authenticated through that?

**Comment by munagekar** [comment]
@SpontaneousDuck Yes, each Profile must have one owner and you can add multiple users as contributors. I have not tested this LDAP/AD for authentication.

**Comment by jl-massey** [comment]
@SpontaneousDuck 
It works on our work cluster, and it uses LDAP Dex authentication.  The only trouble we came across is that our user email/id includes digits that are filtered when the rbac rolebinding is created.  When the rolebinding was named, it created a conflict if someone had a similar id (differing only by the digits).

Apparently this is been fixed in KF1.1?  If it's broken you can still create the rolebindings manually (without GUI) to get around the naming 'feature'.  There's another problem with the UI for managing the namespace, also, in that it doesn't seem to like it when you're the owner of more than one namespace.  it always shows me as contributor for the first one I am the owner of, and owner of the second.   It means I can only add contributors to the one I'm still owner of (unless you use kubectl to add contributors).
