### ISSUE TITLE
Kubeflow 1.2 Release planning, owner, and timeline

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5150]
/kind process

Opening this bug to begin tracking Kubeflow 1.2. We will need to identify an owner(s) who will drive the release including

* Figuring out the major deliverables
* Figuring out the timeline
* Coordinating delivery with working groups and project owners

**Comment by PatrickXYS** [comment]
To track AWS 1.2 change, we send an issue here: #5178

**Comment by Jeffwan** [comment]
@jlewi Do you have a target release date? Trying to can see if we can help. We have Kubecon, Reinvent from Nov and if it's before Nov, that would be great

**Comment by swiftdiaries** [comment]
I can help drive the 1.2 release. Could we schedule a call sometime this week to go over the release engineering workflow?
We can open it up so that anyone who wants to join in and help out can attend as well.

I'm not sure how much I can help out with planning features and driving them to completion.

@Jeffwan I think it makes sense to cut a release pre-Kubecon help with announcements

**Comment by Jeffwan** [comment]
@swiftdiaries  Cool. Agree. We can scope 1.2 release items. This time I think we may not have big stories like multi-user KFP which are time consuming and don't have to wait for 3 months. With wishlist, we can sync with component owners.

**Comment by jlewi** [comment]
@swiftdiaries Can we discuss at the community meeting? Please take a look at the release guide
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

**Comment by swiftdiaries** [comment]
Yes that'll work 👍🏾

**Comment by Jeffwan** [comment]
Kubeflow 1.2 Release planning, owner, and timeline have been finalized. For 1.2 release details, let's track in https://github.com/kubeflow/kubeflow/issues/5371 

Let's close this issue.
