### ISSUE TITLE
Custom Jupyter workspace bind point

### ISSUE THREAD

**Issue by SpontaneousDuck** [kubeflow/kubeflow#5172]
/kind feature

**Why you need this feature:**
I am creating my own containers for the Jupyter workspaces in Kubeflow. I am setting some configuration in `/home/jovyan` since that is the user's home dir. (.bashrc config, etc.) When Kubeflow created the container, the persistent workspace overwrites this. I currently solve this by copying the files I need in there on container start but then my main workspace for Jupyter still has all these files in it.

**Describe the solution you'd like:**
I would like the greyed-out option for the bind point of the main workspace pvc mount point to be usable and set where you want the workspace to mount in the container.

Thanks for all the great work!

**Comment by DavidSpek** [comment]
Wouldn't it be possible to solve this by selecting `Do not use Persistent Storage for User's home` and then adding a Data Volume with the mount path you would like to use?

**Comment by SpontaneousDuck** [comment]
Hmm, yes it just might! You just don't get the automatic naming of that storage to match the container's name though.

**Comment by DavidSpek** [comment]
Is it not possible to set the .bashrc config, etc in the image directly rather than having them load on container start?

**Comment by SpontaneousDuck** [comment]
If I do set it in the image, then it is over-written when Kubernetes mounts the Persistent storage to the User's home. If I want to place things in the user's home directory, it would be useful to be able to bind the default folder for Kubeflow to a different folder than the user's home.

**Comment by DavidSpek** [comment]
Isn’t it possible to set the default .bashrc in a location other than the home directory? In regards to placing other files in the user’s home directory, maybe it is an option to copy them from another directory to the home directory after starting the container. Or have a pre-made PV with the data in it for each user that they can mount. It’s difficult to think of a workable solution without the Dockerfile and use case.

**Comment by SpontaneousDuck** [comment]
I do currently copy the files in with a startup script. That is how I am getting around it. I just know must of the Jupyter images I have seen out there bind the workspace to `/workspace` or some custom folder to avoid this. It would be nice to at least have the option in Kubeflow to change which folder is used! Not a  super high priority problem that needs an immediate fix but this would definitely be a QOL improvement for me using it.

**Comment by Jeffwan** [comment]
Current jupyter notebook provides workspace volume and data volume. Can you use datavolume instead?

**Comment by SpontaneousDuck** [comment]
It would except for the workspace volume will still overwrite the user's home folder

**Comment by DavidSpek** [comment]
@SpontaneousDuck Do I understand correctly, that you want to place files in a directory (any directory for that matter, but in your case the user's home directory) and also want to be able to a mount a PVC to that same directory? If that is the case, you will indeed overwrite the files when mounting the PVC, but this is unavoidable to my knowledge. If you need to place files in the container image they cannot be in a directory which you would later like to mount a PVC to. 

Regarding having the option in Kubeflow to change which folder is used. You have the option what folders you want to use. There is not difference between a workspace volume and data volume to my knowledge, other than having the option to chose the mounting directory for data volumes. I think the feature you are actually looking for is setting the default notebook directory, so users are automatically using the PVC for their workspace. You can set the default notebook directory using `--notebook-dir="some-dir"`. Otherwise, I believe the only option os using a startup script, as you are already doing.

**Comment by SpontaneousDuck** [comment]
The only thing I saw that needed to be done was to allow the workspace directory to be able to be configured, either through the user interface or the deployment config. I did create my own Jupyter notebook container then mondified the Kubeflow deployment config to set this contianer as default as well as configure the default setting for it. It would be great if I could set the default workspace mounting dir here I guess.
