### ISSUE TITLE
API calls on centraldashboard become slow with a large number of profiles

### ISSUE THREAD

**Issue by zachomedia** [kubeflow/kubeflow#5190]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We started seeing some slow startup time when a user loads the Kubeflow dashboard, and after some tracing tracked down a slow call to /api/workgroup/env-info.

After some investigation, it led us to the kfam service where obtaining role bindings takes 3-6 seconds:

```
GET /kfam/v1/bindings?user=$USER ReadBinding 6.064392368s
```

**What did you expect to happen:**

The call succeed quickly and not slow down with increased profile counts

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

We have approximately 123 profiles in our environment for our users. The speed of the call seems to have slowed down as the profile count increased.

**Environment:**

- Kubeflow version: (version number can be found at the bottom left corner of the Kubeflow dashboard): 1.0.1
- kfctl version: (use `kfctl version`): 1.0.1
- Kubernetes platform: (e.g. `minikube`) AKS
- Kubernetes version: (use `kubectl version`): 1.15.10
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by sylus** [comment]
This is a pretty big deal for us and would expect this would be reproducible by numerous other orgs.

**Comment by Jeffwan** [comment]
@zachomedia @sylus Could you share how many profiles do you have in that cluster? Since it makes call to Kube-apiserver. Any performance issue on master instance may increase latency. Do you have way to know the `6s` trace? I am curious which part contribute more.  active request like `List` to APIServer won't be efficient, I agree we probably need to add some cache and user won't see user immediately but I think this should be acceptable. An option to control cache policy will give some flexibility.

**Comment by zachomedia** [comment]
@Jeffwan We currently have 122 profiles in the cluster. I will see if we can get a way to break down the trace more and get a breakdown on the 6s response time.

**Comment by Jeffwan** [comment]
@zachomedia  I will mark this as part of 1.2 improvement. I think we did tuning on jupternotebook on profile controller but not on UI yet. Might be some tuning to do on some components to improve performance

**Comment by sylus** [comment]
Would this tuning done on the profile controller be applicable to jupyter notebook? If so we could take a look and try to help also. Keen to move this forward.

**Comment by derekwyatt** [comment]
I'm seeing the same thing.  This is exacerbated when a lot of people are trying to use the system simultaneously.  Profiles sometimes can't get created, lots of timeouts and so forth.  We currently have 120 profiles but started seeing this problem around 80 or so.  We're looking into it now to see if there's a bandage we can put on it with some caching but if there are better options that anyone has come up with, I'd love to hear them because I'm just getting familiar with the code and will probably make a few missteps without some guidance.

**Comment by yanniszark** [comment]
@derekwyatt a PR is in-review: https://github.com/kubeflow/kubeflow/pull/5202
You can help by building an image from the PR's code and testing if it fixes your issue.

**Comment by sylus** [comment]
I can say we are using the P.R. to great effect we also re-wrote the Jupyter API's into golang for the Jupyter Web App and now everything appears to be blazing fast :D 

https://github.com/StatCan/jupyter-apis

**Comment by yanniszark** [comment]
> I can say we are using the P.R. to great effect we also re-wrote the Jupyter API's into golang for the Jupyter Web App and now everything appears to be blazing fast :D

@sylus that's great to hear. If you don't mind, what lead you to recreate the Jupyter APIs in Golang? Were you experiencing performance issues? If yes, with how many users?

**Comment by sylus** [comment]
@yanniszark our issue was this one for why we had to redo the APIs :) :

https://github.com/kubeflow/kubeflow/issues/5201

**Comment by derekwyatt** [comment]
Preliminary results on testing #5202 are good for us as well.  We're going to stress it next week with actual humans but our automated stresses are showing quite positive results.

**Comment by zachomedia** [comment]
Just want to unstale this issue as we are still running a custom version with the patch.

**Comment by ca-scribner** [comment]
I believe this is fixed by #5673, although I have not confirmed it personally
