### ISSUE TITLE
[notebook controller] Integration with prometheus operator

### ISSUE THREAD

**Issue by MartinForReal** [kubeflow/kubeflow#5216]
/kind feature

**Why you need this feature:**
I need to monitor the usage of notebook instance by leveraging existing monitoring infrastructure. Such as Prometheus operator.

**Describe the solution you'd like:**
Jupyter lab has provided Prometheus metrics in its API design. https://github.com/jupyter/notebook/issues/3682
we can collect these metrics and get useful information such as last login time, response time and etc.

**Anything else you would like to add:**
none

**Comment by LuChengTHU** [comment]
How's it going?

**Comment by blairdrummond** [comment]
@DavidSpek if you're able to re-open the issue, I am making a little progress.

I have been working upstream on jupyter on the `/metrics` endpoint, and working on the prometheus operator integration. I think I have the label selection working, only tricky bit is implementing the rewrite rules in the service-monitor. Because of the `base_url`, the metrics are on `/notebook/$namespace/$server/metrics`, and so need to use some magic to scrape from there instead of plain ol' `/metrics`. I am following this as a guide:

https://github.com/prometheus-operator/kube-prometheus/pull/16#issuecomment-424318647

**Comment by blairdrummond** [comment]
Once I get this ironed out, I'll PR in a ServiceMonitor spec which should implement this.

**Comment by DavidSpek** [comment]
/reopen 

@blairdrummond Would your work also be applicable to https://github.com/kubeflow/pipelines/pull/4422? I think having a Prometheus instance (or one per component) and a central grafana instance for the standard Kubeflow deployment would be a nice addition. Arrikto has some other dashboards that integrate Grafana metrics as well, which could then possibly tie into this as well.

**Comment by blairdrummond** [comment]
Hmm, kubeflow/pipelines#4422 seems more complex. That's more about using the regular pod metrics but subsetting down to a specific label that indicates the pipeline?...

That sounds super cool and totally doable, but might be a while before I tackle it... I will take a look but no promises yet ;-)

**Comment by DavidSpek** [comment]
I'm also planning on looking into it once the deployment method for 1.3 becomes more clear to me. I was planning to use the Prometheus operator along with the grafana operator which would hopefully make things a bit easier to manage. @blairdrummond are you using the Grafana operator as well?

**Comment by DavidSpek** [comment]
This is still an ongoing effort
