### ISSUE TITLE
Kubeflow CLI

### ISSUE THREAD

**Issue by wbuchwalter** [kubeflow/kubeflow#522]
It would be great if data scientists (and others) could leverage the benefits of Kubernetes + Kubeflow without having to learn about Kubernetes internals (kubectl and such) and ksonnet.

By having a clean domain-specific CLI, we could make kubeflow much more accessible to non-k8s people.
For example, at high level such a CLI could allow at a minimum a user to do things like:
```
kf run <job-config>
kf logs <job>
kf status <job>
kf monitor <job> (tensorboard) 
kf get-model <job>
...
```

I will work on proposal with @inc0, but any ideas/feedback welcome before that.

**Comment by inc0** [comment]
I was thinking about something like that:

``
kf model train <<model name>> --version 1 --source <<relative path to python dir with code>> --base-image <<image we support with most typical deps or user-supported img>> --distributed --nodes 3 --config <<optional config if you want more control>>
``

This tool would tarball code dir and save it somewhere (S3? Google storage? PV? We can have running operator that will have this storage config setup), then spawn X jobs with auto-configured typical setup (unless user decides otherwise), pull code and run.

We could also spawn tensorboard for this job etc.

At the end it could save trained model somewhere for future use. We could prepare set of env variables and ask users to set them for tf.Saver and whatnot so, assuming they'd do it, experience would be really streamlined between running thing locally and on distributed.

After model is trained you could run
``
ks model serve <<model_name>> --version 1 --nodes 3
``
This would mount/download trained model and run tf servers + load balance svc (Envoy?)

**Comment by inc0** [comment]
If we could achieve ^ it would be awesome if we could address similar use-cases with jupyter plugin to make it buttony-clicky:) https://github.com/kubeflow/community/issues/44

**Comment by jlewi** [comment]
- I think there should be a high correlation between a CLI and an API/client library so that when users want to script the functionality they don't need to either
   - reimplement the CLI
   -. shell out

The implication of the above is that designing the CLI is really designing a higher level API ontop of our core APIs.

I believe the TFJobs UI already has an APIServer behind it that powers it. So evolving that API and making it first class might be a good way to go.

- Ideally client libraries would be thing (e.g. auto-generated from openswagger API Spec) so that we could support a variety of language bindings.

- The CLI could then be a simple wrapper around one of the autogenerated client libraries..

**Comment by inc0** [comment]
There will be a bit more to client if we want to do things like "upload code from local". While I agree 90% of usability will be API-based, there is 10% that either need access to local resources (upload code) or is just wrapper around kubectl commands (get job pods and run kubectl logs on them).

**Comment by kkasravi** [comment]
I have a `kf` CLI proposal that i'll be submitting this week for feedback under community. I agree with @jlewi that we should leverage something like [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) or client-gen rather than doing any CLI that includes all of these args. If we were to create a CRD that represents what's required for a kf-operator to manage a "KubeFlow" resource it would at least need to include the following
```
type KubeFlow struct {
  metav1.TypeMeta 
  metav1.ObjectMeta 
  Spec KubeFlowSpec 
  Status KubeFlowStatus
}

type KubeFlowSpec struct {
  User RoleBinding 
  Volumes []Volume 
  ServiceAccounts []ServiceAccount
}
```
It would likely need additional info like PodSecurityContext for volume mounts and as @inc0 notes above possibly details related to tensorflow master, parameter servers and workers.

Then the `kf` CLI would internally call `ks generate ...` which would include kubeflow/core/kubeflow.libsonnet and in that we define the KubeFlow CR - where parts are populated from params like we do for nfs and others.

**Comment by gaocegege** [comment]
> If we were to create a CRD that represents what's required for a kf-operator to manage a "KubeFlow" resource it would at least need to include the following

I am not sure if I understand the meaning of kf-operator. If we want to manage all operators for different frameworks I think maybe we could maintain a kubeflow-controller-manager instead of an operator.

**Comment by jlewi** [comment]
I think we should draw a distinction between

- Deploying/Managing Kubeflow
- Performing tasks using Kubeflow

I think the original intent of this proposal was about the latter; e.g. uploading submitting jobs once Kubeflow is deployed.

@kkasravi  For Deploying/Managing Kubeflow PTAL #105 

I think the reasons for separating the two are

- Different people will be performing these tasks
   - Sysadmins/secops will likely be the ones deploying and managing Kubeflow 
   - ML researchers/datascientists will be the ones actually running jobs

**Comment by inc0** [comment]
Exactly @jlewi this is about "day 2". We use ksonnet today to deploy kubeflow, but kubeflow itself is tf-operator and jupyterhub that doesn't really talk to each other. I was thinking of having overarching compontent that would bind these two + other frameworks and provide API endpoint for various CLI calls.

@kkasravi as I said before, I think 90% can be autogenerated, but some logic will have to be included in client too. Not a big deal tho.

**Comment by inc0** [comment]
> I am not sure if I understand the meaning of kf-operator. If we want to manage all operators for different frameworks I think maybe we could maintain a kubeflow-controller-manager which is similar to kube-controller-manager, instead of an operator.

I think we run into nomenclature problem. Operator in way I understand it is a piece of code that would provide endpoint to APIs and handle CRDs. Like rook operator can handle crd Cluster but also provide endpoint to CLI tools to manage these clusters, so it's kind of both.

We can call it controller-manager too, but let's agree on one:)

**Comment by kkasravi** [comment]
@jlewi @gaocegege @inc0 great points and relevant to the scope of control. 

One approach would be to look at what resources are created at `ks generate ...`. 
This analysis could breakdown resources created for each distinct `ks generate ...` phase
and would list clusterrolebindings, rolebindings, PVs, namespace and other resources required to deploy vs resources required to run tasks or workflows. With this approach the type of controller/operator used would be more clear and would determine each resource's metadata.ownerReferences. This would be important in state transitions, recovery, cleanup. 

Note that the subjects referenced under current rolebindings (ambassador, jupyter-role) probably needs some review.

**Comment by inc0** [comment]
Does ksonnet allow this kind of introspection? I mean "check state of existing resource X and make decisions based on this". Ksonnet is powerful templating language, but I'd be very careful with putting too much logic in it...

**Comment by raddaoui** [comment]
I saw this late. We created already a kubeflow CLI which does almost what @wbuchwalter described.
kf train <job-config>
kf logs <job>
kf monitor <job> (tensorboard) 
kf deploy <job>
kf clean <job>
kf help.
Still the deploy and monitor piece are being worked out at the moment but currently It reads code from local file system for training and supports also s3 datasets for now (others are on the way).
it just behaves as a wrapper for kubectl and ksonnet (different commands have different ksonnet prototypes deployed in the back)
I will be happy to demo this and push code to an experimental folder in kubeflow.

**Comment by inc0** [comment]
cool stuff @raddaoui . I'm more in favor of having running service exposing API tho, offers more flexibility and extensibility. Is it part of your e2e demo?

**Comment by cwbeitel** [comment]
Here's an example of what I'm using (from the data scientist user perspective), https://github.com/cwbeitel/examples/blob/enhance/enhance/py/launcher.py, see also these [notebooks](https://github.com/cwbeitel/examples/tree/enhance/enhance/doc) and [tests](https://github.com/cwbeitel/examples/blob/enhance/enhance/py/launcher_test.py) for how this is being used.

Looks like this would fit into the above in place of `kf train` as an extensible `kf run` where perhaps there could be a --kf_usr_dir that pointed to dir having an \_\_init\_\_.py that registered any Job or TFJob objects that should be available via `kf run ...`, e.g. `kf add usr_dir /home/jovyan/my_app`, `kf run datagen ...`, `kf run trainer ...`, `kf run inference`.

Also included with this is a particular approach to building a base container with job dependencies and shipping user code via NFS. While this particular approach might not be the one we want to use I think it would be really valuable to have a command line tool that abstracted this process away.

The idea here is not just a CLI but a mini python framework for expressing jobs and registering those with a CLI that at least in my case accelerated development.

**Comment by inc0** [comment]
I made an attempt :) https://github.com/kubeflow/community/pull/52

**Comment by kkasravi** [comment]
@raddaoui and I are from the same company so we'll review our proposals tomorrow and hopefully submit one based on our review

**Comment by raddaoui** [comment]
@inc0 no this is a separate project we have been working on besides the e2e.
The CLI is written in a very easy way to extend it. you just add a command and a function to handle it in the library. I think kubeflow API is a great idea but I feel like creating a second layer of abstraction would make it difficult to debug issues when they arise and you would still need to develop a CLI for it too.
I will work with @kkasravi to put a proposal out there and possibly demo it soon to the community.
