### ISSUE TITLE
ResourceQuotaSpec is removed in profile when "kind" is "User"

### ISSUE THREAD

**Issue by qiaqiatic** [kubeflow/kubeflow#5319]
/kind question

Hi I am trying to create profile from Kfam API with below json
```
{
   "metadata":{
      "name":"firstname-lastname-test1"
   },
   "spec":{
      "owner":{
         "kind":"User",
         "name":"firstname.lastname.test1@mycompany.com"
      },
      "resourceQuotaSpec":{
         "hard":{
            "cpu":"10",
            "memory": "20Gi",
            "pods":"1"
         }
      }
   }
}
```
it ends up with below object in K8s, one can see that `resourceQuotaSpec` is omitted.

```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  creationTimestamp: "2020-09-23T05:39:00Z"
  finalizers:
  - profile-finalizer
  generation: 2
  name: firstname-lastname-test1
  resourceVersion: "48530898"
  selfLink: /apis/kubeflow.org/v1/profiles/firstname-lastname-test1
  uid: 6f23e6ec-c5c4-4fe1-90d9-0a7913035427
spec:
  owner:
    kind: User
    name: firstname.lastname.test1@mycompany.com
  resourceQuotaSpec: {}
```

but when I changed to "kind" to lower case "user" as below

```
{
   "metadata":{
      "name":"firstname-lastname-test2"
   },
   "spec":{
      "owner":{
         "kind":"user",
         "name":"firstname.lastname.test2@mycompany.com"
      },
      "resourceQuotaSpec":{
         "hard":{
            "cpu":"10",
            "memory": "20Gi",
            "pods":"1"
         }
      }
   }
}
```

the object is created in k8s as below, `resourceQuotaSpec` is correctly presented in the object store

```
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  creationTimestamp: "2020-09-23T05:39:38Z"
  generation: 1
  name: firstname-lastname-test2
  resourceVersion: "48531234"
  selfLink: /apis/kubeflow.org/v1/profiles/firstname-lastname-test2
  uid: 270f49a8-76f2-4d1d-942d-599e2cdebe2c
spec:
  owner:
    kind: user
    name: firstname.lastname.test2@mycompany.com
  resourcequotaspec:
    hard:
      cpu: "10"
      memory: 20Gi
      pods: "1"
```

wonder what is making the `resourceQuotaSpec` gone in my first case?

**Question:**
[You can ask any question about this project.]

**Comment by jzhoucliqr** [comment]
kfam is using a pretty old version of profile-controller api: github.com/kubeflow/kubeflow/components/profile-controller v0.0.0-20191008230951-321c1d3313b6. 

which have this:  	                ResourceQuotaSpec v1.ResourceQuotaSpec `json:"resourcequotaspec,omitempty"`
But latest profile CRD has:   ResourceQuotaSpec v1.ResourceQuotaSpec `json:"resourceQuotaSpec,omitempty"`
Notice that json tag is different now. 

When you create from kfam api with kind:User, the profile CR is reconciled successfully by the profile-controller, which will remove resourcequotaspec as it's a unknown field, then you see that resourceQuotaSpec is empty. 

when create with kind:user, profile-controller reconcile error out because 'user' is not valid kind, so the CR was left as it is, that's why you still see the field resourcequotaspec which is actually not correct.

probably need to update  profile-controller to latest in kfam go.mod
