### ISSUE TITLE
minikf kubelet service doesn't restart on VM reboot

### ISSUE THREAD

**Issue by noushi** [kubeflow/kubeflow#5348]
/kind bug

**What steps did you take and what happened:**
`minikf` gets kubelet service running upon initial vagrant creation, but a `vagrant reload` has the kubelet service not started on boot.

**What did you expect to happen:**
it should have started.

**Anything else you would like to add:**
fix is simply to enable the kubelet systemd unit like this:
```
systemctl enable kubelet
```

The permanent solution is to insert this command during the vagrant box creation (packer), but I couldn't find the repo for minikf.

**Environment:**

minikf box: arrikto/minikf     (virtualbox, 20200305.1.0)

**Comment by dimara** [comment]
@noushi We don't start the kubelet separately, by design. We expect our provisioning process to start everything, because it takes care of lots of things and ensures everything is in place before starting the kubelet. It also provides feedback to the user as it does so.

On Vagrant, to avoid having all pods started right after reboot and practically have an unresponsive landing page due to a huge load, we leave the kubelet service disabled and let the provisioning script start it explicitly.

That said, in later versions of MiniKF that are available on GCP, since there is no landing page there, and we have bigger VMs, we do start the provisioning process automatically.

**Comment by noushi** [comment]
I see. 
Thank you @dimara .
