### ISSUE TITLE
user create  selected dir (like nfs) as notebook pv 

### ISSUE THREAD

**Issue by liuweibin6566396837** [kubeflow/kubeflow#5409]
/kind feature

**Why you need this feature:**
When use rancher.io/local-path, pv and pvc automatic builed in /local-path-provisioner path. If users have large amount of data put to pv, they need copy data from node to node, as notebook server will be built in automatic node.
More, mutiple users have theire own notebook server, if they want to use the same dataset, the only way is cooy  dataset frome pv to pv.

**Describe the solution you'd like:**
create nfs pv by user

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DavidSpek** [comment]
@liuweibin6566396837 It sounds like you need to deploy some sort of storage provisioner on your cluster. Since you are using rancher, longhorn might be a good fit and it is very easy to setup. If you have large datasets that multiple people need to access, and no storage solution other than local-path, it sounds like your cluster nodes are not setup with storage duties in mind. If you have an existing NFS server, you can use the NFS-Client provisioner to access it through PVCs in the cluster https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

**Comment by DavidSpek** [comment]
Closing this issue as deploying storage solutions are out of the scope of Kubeflow.
/close
