### ISSUE TITLE
Where should notebooks code live

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#5418]
Opening this issue as a follow on to discussion in kubeflow/community#454 and at the community meeting.

Notebooks code is currently in kubeflow/kubeflow
https://github.com/kubeflow/kubeflow/tree/master/components/jupyter-web-app

kubeflow/kubeflow has historically been a catchall and historically as projects have matured they have moved out of kubeflow/kubeflow into project specific repositories.

Now that we have formed working groups we would like working groups to take responsibility for managing their repositories to deal with kubeflow/testing#737.

So going forward rather than creating new repositories in Kubeflow when WGs need a new repo we would like them to create this repo in a GitHub org they own/administer so they can bear responsibility for administering the repo and managing access control.

@kubeflow/wg-notebook-leads WDYT? It looks like you already have a GitHub org https://github.com/kubeflow-kale which is where Kale lives. So what's blocking from creating repos there for notebook controller/notebook images etc...?

Can we rename the GitHub org? I think "Kubeflow <Foo>" naming is boring. Given the aspirations of the WG regarding the datascientist experience; "kubeflow-kale" and "kubeflow-notebooks" seem a bit limiting.

**Comment by cvenets** [comment]
@jlewi as I mentioned live during the last community meeting, we do not want to move the notebooks code outside of the Kubeflow organization, since we do not think this is the right path forward.

Currently, all WGs have their code inside the Kubeflow org. By moving the notebooks code out of the Kubeflow org, we will be treating the Notebooks WG completely differently from any other WG, and we believe this is a very bad signal, giving us a significant handicap going forward. The end users are not really familiar with the current shift in the project, thus it is only natural for them to treat external repos differently than internal. A repo sitting under `kubeflow/` looks much more recommended by the community, than a repo sitting on its own, outside the organization.

We are completely open to move the code outside of `kubeflow/kubeflow` since this is what we are trying to solve here, but this would mean that Google needs to create a repository for us to use, like `kubeflow/notebooks`, or whatever other name we decide is relevant.

This shouldn't be a big hassle for Google, compared to the value it would provide to the community and the end users.  I think notebooks is a pretty significant component to justify the creation of a repo. I see 42 repositories currently under `kubeflow` and some of them have not been updated since April, May, or June. If the management burden of a repo is significant, I would propose to first try to clean up some repos from the org, so that we can host a new one for Notebooks.

cc: @Bobgy @animeshsingh @jbottum @kimwnasptd

**Comment by thesuperzapper** [comment]
I raised a proposal to establish a "Working Group Led" GitHub org: https://github.com/kubeflow/community/issues/456

**Comment by jlewi** [comment]
@cvenets I hear you and I think you raise good points. 

> treating the Notebooks WG completely differently from any other WG,

We are treating all WGs equally. Per kubeflow/testing#737 all WGs need to take responsibility for their engprod resources which includes GitHub repositories.

As of right now, we haven't set a fixed timeline. Instead the approach we've taken is we will leave things as they are and when WGs hit the limits of what they can do today we will ask them to take ownership as part of enabling new features. 

Unfortunately notebooks will likely hit that sooner than other WGs.

> This shouldn't be a big hassle for Google

I don't speak for Google but I have a different perspective. Yes in isolation this looks trivial but this is only one of many such tasks; so we have a case of death by a 1000 cuts. Off the top of my head hears a list of the oneoff toil that have just recently been directed at a very small set of Googlers

* Manually retag docker images
* Enable GitHub support for docker images
* Cleanup calendar events

Furthermore, there is a high opportunity cost to doing this. Time spent on this toil takes a way from much higher impact tasks like defining what it means for an application to be Kubeflow Native. 

At the last community meeting folks were on the one hand asking for more high level direction from Google and simultaneously creating toil that take cycles away from those very problems. 

In kubeflow/community#456 @thesuperzapper has proven that the @kubeflow/wg-notebook-leads are easily capable of taking on the toil of setting up and administering their own GitHub org. So while doing so may have some downsides I think freeing up cycles to focus on the more impactful issues is worth it.

>  The end users are not really familiar with the current shift in the project, thus it is only natural for them to treat external repos differently than internal. 

Can we fix this? Could you write a blog post (or find some other way) explaining the vision for notebooks, who's behind it, and why people should have confidence that the project will succeed?

> A repo sitting under kubeflow/ looks much more recommended by the community, than a repo sitting on its own, outside the organization.

This is a bug and one of the primary things I have been trying to address with working groups. In order for people to have confidence in a project they need to know someone is accountable. The source of that confidence should be faith in the individuals and organizations behind a project. The whole point of working groups is to clarify which individuals and organizations are accountable for which projects.

@kubeflow/google-admins might be willing to create another repo for you and continue to extend engprod resources to the notebooks wg. My personal oppinion though is that those cycles could be better invested elsewhere and the community would be better served if @kubeflow/wg-notebook-leads enabled that by taking ownership.

**Comment by Bobgy** [comment]
Reopen
