### ISSUE TITLE
Need Stack Config for On-Prem Vanilla K8S

### ISSUE THREAD

**Issue by perdurabo93** [kubeflow/kubeflow#5459]
/kind feature

**Why you need this feature:**
I need the ability to install kubeflow on an existing on-prem vanilla Kubernetes instance behind a corp firewall

**Describe the solution you'd like:**
I need a stack config kfctl/kustomize yaml that supports:
- Custom local Docker repo (this appears alpha, but does not support ImagePullSecrets)
- Predefined/existing ImagePullSecret applied on the namespace and/or ServiceAccount level
- ClusterRoles with custom podsecuritypolicies
- Ingress instead of VirtualService

**Anything else you would like to add:**
Right now trying to install is a nightmare as I must render everything into a single explicit manifest like so:

kfctl build -V -d -f kfctl_k8s_istio.v1.2.0.yaml > kubeflow_manifest_.v1.2.0.yaml

And then manually edit the manifest to compensate for all my requirements, then apply the omnibus manifest, hoping theres no errors.

**Comment by DavidSpek** [comment]
@perdurabo93 Release 1.3 will contain a large refactoring of the manifests. I think it would be best to revisit this after the upcoming release. 

/cc @kubeflow/wg-deployment-leads

**Comment by PatrickXYS** [comment]
Who will be working on On-prem K8s deployment? I don't think we have a clear person responsible for this. 

Maybe @jtfogarty know about it? Will you help maintain on-prem stuff including deployment, manifests, etc?

**Comment by mameshini** [comment]
We do not have one person responsible for on-prem, but discussions are happening within Kubeflow on-prem SIG.  I can only confirm that kfctl based approach does not provide configuration options that are sufficient to address the requirements for on-prem deployments.  Our current approach for AgileStacks distribution is to customize, package, and deploy upstream Kubeflow 1.2 manifests using AgileStacks Hub CLI tool.  We are no longer using kfctl due to regressions in kfctl 1.2 compared to previous versions.  We will be able to provide updates for Release 1.3 manifests to make manifests more compatible with on-prem deployment requirements.  There is need for more control of Docker registry, ingress, labels, storage, ClusterRoles.

**Comment by DavidSpek** [comment]
I am deploying on-prem with kfctl, but don’t have these specific restrictions. I haven’t been involved with the on-prem meetings, but might be able to help out here or there.
