### ISSUE TITLE
Kubeflow Multiuser Isolation: Read-only access

### ISSUE THREAD

**Issue by kd303** [kubeflow/kubeflow#5510]
/kind question

**Question:**
[You can ask any question about this project.]

We are trying to create a separate namespace where the different runs can be submitted, I understand from the documentation currently that pipelines have restrictions about namespaces, however our use-case is the runs where this is happening we want to allocate the GPU resources in that namespace, so users can submit their jobs to a queue and we deploy these jobs from a queue as and when the resources are available. 

My Questions are:
1. What is the way we can ensure the users have read-only access to above namespace? Is this possible? so that they are able to view their runs, status of it, logs and metrics generated
2. At the sametime they should not be able to create resources in that specific namespaces - for example Notebook servers, running other pipelines or deploy a kf-serving model
3. Managing above scenario via contributors is not great as it will allow the access of all resource in the common namespace..

We are trying to ensure we utilize the GPUs in best possible manner and resources are not stuck to a specific team/individual.. 

Please provide any updates/link or direction using which we can solve this.

**Comment by yanniszark** [comment]
@kd303 I think this issue is better suited for https://github.com/kubeflow/pipelines/.
The mechanism for partitioning resources (e.g., GPUs) between namespaces is called `ResourceQuotas`.
https://kubernetes.io/docs/concepts/policy/resource-quotas/

If I understand correctly, your policy is the following:
- Single shared namespace with all GPUs (so other user namespaces should have 0 quotas).
- Users should have access to submit pipeline runs and then view runs, logs, etc.

Then the way to do that would be to:
- Add a resource quota of 0 GPUs for user namespace, so that they can't get any GPUs.
- In the shared namespace, give users access to view and create pipelines. In newer releases of Pipelines, you can do this by giving users the necessary RBAC permissions (https://github.com/kubeflow/pipelines/issues/3513#issuecomment-721784849). In older ones, you can use the contributor UI.

**Comment by PatrickGhosn** [comment]
> @kd303 I think this issue is better suited for https://github.com/kubeflow/pipelines/.
> The mechanism for partitioning resources (e.g., GPUs) between namespaces is called `ResourceQuotas`.
> https://kubernetes.io/docs/concepts/policy/resource-quotas/
> 
> If I understand correctly, your policy is the following:
> 
> * Single shared namespace with all GPUs (so other user namespaces should have 0 quotas).
> * Users should have access to submit pipeline runs and then view runs, logs, etc.
> 
> Then the way to do that would be to:
> 
> * Add a resource quota of 0 GPUs for user namespace, so that they can't get any GPUs.
> * In the shared namespace, give users access to view and create pipelines. In newer releases of Pipelines, you can do this by giving users the necessary RBAC permissions ([kubeflow/pipelines#3513 (comment)](https://github.com/kubeflow/pipelines/issues/3513#issuecomment-721784849)). In older ones, you can use the contributor UI.

I applied the clusterroles and the bound them to my namespace, but I'm still getting RBAC. Any idea why?

**Comment by yanniszark** [comment]
@kd303 @PatrickGhosn please open this issue in https://github.com/kubeflow/pipelines/, as it is the place where you'll get the help you need. Closing this issue.
/close

**Comment by kd303** [comment]
@yanniszark - I have opened the [issue # 5006](https://github.com/kubeflow/pipelines/issues/5006) I don't believe the contributors can be added as readonly from the contributor UI, This is just not about the pipeline but almost every object that we can think of. thanks for the pointers though.
