### ISSUE TITLE
[AWS] Incorporate AWS hosted kubeflow notebook image in kubeflow/kubeflow

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/kubeflow#5546]
/kind feature

**Why you need this feature:**
We (AWS EKS team) have built our hosted kubeflow notebook image as derived from this [Dockerfile](https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile) since 1.0.

Given community folks have been asking for the Dockefile for our hosted image and want to build a customized image on top of our image, we want to move the Dockerfile to kubeflow/kubeflow repo for reference.

/cc @kubeflow/wg-notebooks-leads

**Comment by kimwnasptd** [comment]
@PatrickXYS what extra functionality do these images provide over the vanilla experience of the existing Notebook images? If these features are generic enough, then we could incorporate them to our Kubeflow Notebooks images. 

I'd like to avoid making this repository act as a central place for different organizations to host their specialized crafted Dockerfiles, because this can quickly blow up.

This repo should only provide a list of base images, that any other org can just fork and extended to their specific use cases. At the same time, if you feel certain functionality is missing from the current base images, I'd love to work with you to incorporate it in the base images, so we can maintain the shortest list possible.
What do you think?

**Comment by PatrickXYS** [comment]
@kimwnasptd Thanks for your feedback, our notebook image is derived from original one, and add some AWS related functionalities. 

I agree that things would blow up if kubeflow/kubeflow becomes a central point for all the cloud-providers to host ad-hoc Dockerfiles.

I'll figure out with another way to move forward

**Comment by DavidSpek** [comment]
@kimwnasptd @PatrickXYS I agree that this repository shouldn't be the central place for cloud providers or other organizations to host they Dockerfiles. However, seeing as the current Dockerfiles already contain some basic GCP, AWS and Azure stuff, I'm interested in seeing the Dockerfiles and what AWS related functionalities are added. Seeing as there are 5 packages that are install for Google, if it is a question of a few (small) packages being added for AWS I don't see that as something that will initiate this repository blowing up.
