### ISSUE TITLE
Workspace Mount Path hardcoded

### ISSUE THREAD

**Issue by muthurajr** [kubeflow/kubeflow#5547]
Seems like Workspace Mount point is hard coded and not using the value specified in the Spawner Config.

https://github.com/kubeflow/kubeflow/blob/89b13955b910d7320ffba6b03ed26ad4d1b56582/components/crud-web-apps/jupyter/backend/apps/rok/routes/post.py#L51

**Comment by kimwnasptd** [comment]
I agree that the mount point of the workspace volume should be respected by the backend, and defaulted to `/home/jovyan` since in Kubeflow we've made the assumption that a user `jovyan` will be running inside the notebook.

But @muthurajr what exactly is your use case? Are you deploying a custom Notebook, that doesn't extend Kubeflow's Notebook images, which defines a differently named user?

**Comment by muthurajr** [comment]
I'm trying to install theia ide with jupyter server proxy which adds and expects files in the home directory. During installation, configuration files are created at the home directory (/home/jovyan). In Kubeflow spawner_ui config, option is available to change the mount path of the persistent volume (/home/jovyan to /home/jovyan/mnt/) which is not working as the value is hard coded here.

Rather the modifying things on the installation and other configurations, if we can make the Spawner config used it would be great.

**Comment by DavidSpek** [comment]
I believe this is actually a bug as it should respect the setting in the config. I don't think this will be fixed in time for 1.3 though as the feature cut is the 23rd.
