### ISSUE TITLE
Is Kubeflow Open Source or Not

### ISSUE THREAD

**Issue by ReggieCarey** [kubeflow/kubeflow#5667]
/kind question

**Question:**
[You can ask any question about this project.]
The Kubeflow project touts itself as an open source effort. It advertises channels on Slack for the community to use.  However, it seems that Microsoft, Google, and other proprietary orgs, limit who can use the publicly advertised slack channels (limited to internal Microsoft and Google staff).  Further, it appears that these vendors have a choke hold on Kubeflow utility outside of their proprietary environments and they've constrained the product direction via internal steering groups at these large companies with little or no public feedback.

This would be fine if these vendors were interested in supporting a viable solution outside of their proprietary platforms but that does not seem to be the case.

I truly appreciate the efforts of the organizations that made Kubeflow possible, but either decide to be proprietary or decide to be open source.

It seems like there is some collusion (either intentional or not) amongst the cloud vendors to make Kubeflow a technology only viable on their platforms.

So, is Kubeflow open source in name only?  Am I way off base in my assessment?

**Comment by DavidSpek** [comment]
@ReggieCarey Kubeflow most definitely is open-source. You can install it on whatever Kubernetes cluster you like. I personally run it on an on-premises cluster as well. Regarding Slack, there was an issue how the invites are handled but this is being worked on. Anybody is allowd (and encouraged) to join. Regarding the internal steering groups, there is currently a Project Steering Group that consists of only Googles. However, the discussion has been started regarding creating a community-elected Technical Steering Committee https://github.com/kubeflow/community/issues/495. I consider myself fairly active within Kubeflow and I don't work for any tech company, so public feedback is most definitely acted upon. 
It's a bit late where I am so excuse my rather brief answer. Maybe @castrojo or @thesuperzapper can fill in the gaps of my answer.

**Comment by castrojo** [comment]
Hello Reginald! I saw your previous issue trying to join the slack and can see how you might come to this conclusion. 

The slack invite domain list isn't intentional. Generally speaking Slack is designed for internal use at a company, OSS collaboration not so much so many of it's features need to be worked around for it to work for OSS projects. One of those is sending someone an invite who might not be part of "your organization". See this ticket for more details in case you haven't seen it yet: https://github.com/kubeflow/community/issues/473

Recently there's been issues filed in the community repo around governance, specifically the ones marked as proposals: https://github.com/kubeflow/community/issues

I am new to the project myself but there are actionable items here that we're working on to add more transparency and community processes to the project, and I totally understand how a broken slack inviter might be giving off the totally wrong vibe. As for the cloud vendory stuff, there's a group of us working on kubeflow onprem as part of a SIG. [Here's the google group](https://groups.google.com/g/kubeflow-sig-onprem) if you wanna check it out and drop by a meeting we'd be happy to show you some of the onprem work! 

https://github.com/kubeflow/community/blob/master/psg/ROADMAP.md might of interest as well. 

I hope this helps clear some things up, pardon our dust, etc. 😄

**Comment by jbottum** [comment]
@ReggieCarey Welcome and thanks for your question! Kubeflow is open source.  You can contribute to it.   One of the best ways is to join a Working Group Meeting.    Kubeflow's release process has matured.   In 1.3, we have asked the Working Groups to complete their code contributions, and then the distribution/platform groups (AWS, GCP, Azure, IBM, MiniKF/Arrikto) will test and document it for their environments.   Support is provided in a variety of ways (Slack, opening GitHub issues, Kubeflow-discuss, questions at Community meetings or via a commercial agreement with a vendor).   As shown in the annual User Survey results, Kubeflow is a growing community and we measure and respond to user input.    Many users are also contributors (especially with code and documentation), and we look forward to working with you.

**Comment by jbottum** [comment]
@ReggieCarey just wanted to see if we could close this issue.

**Comment by ReggieCarey** [comment]
Please close
