### ISSUE TITLE
Notebook CRD Quantity Validation

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/kubeflow#5722]
/kind bug

**What steps did you take and what happened:**

1. Initial manifests for the Notebook CRD didn't validate resource quantity field (CPU, Mem) to be string or int.
2. A client used a different value (JWA https://github.com/kubeflow/kubeflow/issues/5641)
3. New manifests (from kubebuilder) validate resource quantity field (CPU, Mem) to be string or int.
4. Existing clients / resources break.

Some questions about this situation:

- **Q:** Why does quantity need to be string or int?
   **A:** Quantity is string or int, because that's what Kubernetes validates as well, so it's the schema that kubebuilder generates. 

- **Q:** How does Kubernetes allow users to write fractional numbers in PodTemplates?
   **A:** Kubernetes mutates the field before persisting it! If we create a Pod/Deployment with CPU 0.1, we will see that it's persisted as 100m. We could mimic this behavior with a MutatingWebhook.

- **Q:** How did it work so far if the value is wrong?
   **A:** The deserializer in Go can actually handle fractional numbers. It's Kubernetes convention that this field must be int or string. See: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/#Quantity

**What did you expect to happen:**

To be able to use generated validation schemas from kubebuilder.

**Anything else you would like to add:**

For now, let's use the old CRD. I can think of several ways for solving this in the future:
- Support fractional values in quantity by using a MutatingWebhook, same as Kubernetes.
- Enforce validation, migrate clients and create script to migrate existing resources in a cluster.
- Relax validation to allow fractional values, since Go deserializes them correctly.

**Comment by YousefRabi** [comment]
Getting this error on the kubeflow deployment bash ./pull-upstream step:

fetching package /apps/jupyter/notebook-controller/upstream from https://github.com/kubeflow/manifests to apps/jupyter/notebook-controller/upstream
failed to set "kustomize_manifests_path" automatically in package "apps/jupyter/notebook-controller/upstream" with error: /home/yousofrabi/gcp-blueprints/kubeflow/apps/jupyter/notebook-controller/upstream/crd/patches/old_crd.yaml: wrong Node Kind for  expected: MappingNode was SequenceNode: value: {- # Use the old CRD because of the quantity validation issue:

**Comment by edi-bice-by** [comment]
@YousefRabi see https://github.com/kubeflow/gcp-blueprints/issues/294#issuecomment-889559605
