### ISSUE TITLE
What is the best way to restrict external users to inference/Knative access only in Kubeflow GCP /w IAP?

### ISSUE THREAD

**Issue by crmne** [kubeflow/kubeflow#5769]
/kind question

**Question:**
We have clients that will use our APIs that are behind KFServing and/or Knative running in a Kubeflow cluster. e.g. https://api.client.platform.freshflow.ai

We are using Kubeflow 1.2 on GCP with the default blueprints which also enables IAP.

_What is the best way to restrict external users to inference/Knative access only in Kubeflow GCP /w IAP?_ We don't want to give our clients access to the Kubeflow UI and we don't want to give them a company email address using Google Workspace either.

Thanks!

**Comment by Bobgy** [comment]
/cc @yanniszark 
I think with our current design,

The short term workaround is that you can set up another ingress just for them and configure authz based on your requirements.

Long term solution is probably that each kubeflow component should implement subject access review based authz, so that we can set permission in granularity per application.

**Comment by crmne** [comment]
Thank you for your answer @Bobgy. Are there any plans to do this?

**Comment by Bobgy** [comment]
Cc @kubeflow/wg-serving-leads

**Comment by crmne** [comment]
Hi there,

is there any progress on this? How can I help?
