### ISSUE TITLE
Fast local storage for caching the training dataset

### ISSUE THREAD

**Issue by atamahjoubfar** [kubeflow/kubeflow#5778]
/kind question

**Question:**
What is the best approach for using the local storage, e.g., NVMe solid-state drives of the GPU nodes for caching the training datasets?

In many on-premise deployments, a high-performance distributed file system is not available. However, the GPU nodes usually have local solid-state drives, which are fast. To my understanding, Kubernetes does not support dynamic volume provisioning of the [local storage](https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/#limitations-of-ga), and it cannot be used as the shared storage of Kubeflow. Is there a way to use these local disks at least as temporary storage in Kubeflow?

**Comment by DavidSpek** [comment]
@atamahjoubfar You could use Rook with Ceph and use the local disks as far as I know, but what you are describing sounds more like Arrikto's Rok storage solution. For this you would need an Object Storage solution as well, which I believe could be done nicely with TrueNAS and its built in MinIO service for on-premises deployments. For more information about Rok you should contact @jbottum as he works for Arrikto.

**Comment by jbottum** [comment]
@atamahjoubfar thanks for your question.    We (Arrikto) definitely agree with your architectural assessment on the benefits of local NVMe disks.  For the last few years, we have committed a large team of specialists to optimize the performance, cost, and operations of Kubeflow's ML workflows on local NVMe.   As you evaluate support options for Kubeflow, data management and storage classes, please feel free to reach out for a briefing and a hands-on tutorial / demo.   In the meantime, this link provides a good place to learn a little more on Arrikto Rok, https://www.arrikto.com/rok-data-management/

**Comment by blairdrummond** [comment]
@atamahjoubfar  I am working on a solution for this as well, and one thing I've noticed is that http-based object storage (like MinIO or S3 equivalents) seems to struggle with the "randomly access many small files" problem. I don't have a good solution yet, but am looking at a kind of architecture (S3/MinIO -> Redis -> GPU) where something "bulk loads" Redis from S3, and then the GPU can reach out to Redis over a binary protocol and access small files randomly and keep up performance.

Part of the reason we're looking at this is because we're trying to use the PyTorch operator and leveraging vanilla Kubeflow, but just something to keep in mind if you have the "Many small files; random access" problem. (There may be folks here with better suggestions)

**Comment by DavidSpek** [comment]
@atamahjoubfar Some other solutions that might be interesting for you:

https://www.alluxio.io

https://piraeus.io
