### ISSUE TITLE
Propagate annotations from notebook to pod

### ISSUE THREAD

**Issue by mradha-beat** [kubeflow/kubeflow#5807]
/kind question

**Question:**
Is there a way to define pod annotations inside the `notebook` resource manifest so that the notebook spawns pods with the right annotation? 

**Use case**: we use pod annotations under `metadata.annotation` for the AWS role required to access data sources. Right now, we are adding this annotation to the created pod after initializing the notebook, however this needs to be done every time the pod is restarted by editing the live manifest. A cleaner solution would be to specify in the `notebook` manifest which annotations we want to add to the created pods.

**Comment by kimwnasptd** [comment]
Hi @mradha-beat 

Unfortunately right now the [Notebook's spec](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/api/v1/notebook_types.go#L27) only allows us to configure the Spec of the underlying Pod.

Being a able to modify the Annotation is a use case that makes sense to have but since the Notebooks CRD is migrated to `v1` we are not able to further extend the Spec of the CR at this point.

We are discussing about starting an effort to introduce a new CRD for managing our IDEs/Notebooks and this case would definitely make sense to include.

**Comment by mradha-beat** [comment]
Thanks for the explanation! :) We'll find a different way.

**Comment by DavidSpek** [comment]
@mradha-beat Not sure if it is useful for your specific use-case but with pod-defaults (a.k.a. admission-webhook) you can add annotations to pods. 

https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook

https://github.com/kubeflow/kubeflow/blob/ebc0c4f073397537412694f9f255dbb3fbdf2043/components/admission-webhook/pkg/apis/settings/v1alpha1/poddefault_types.go#L58
