### ISSUE TITLE
Multi-user isolation dex authentication

### ISSUE THREAD

**Issue by Dimiftb** [kubeflow/kubeflow#5833]
Hi, 

I've got a question regarding the automatic profile creation for Kubeflow dashboard whenever a user logs in for the first time mentioned here: https://v0-7.kubeflow.org/docs/other-guides/multi-user-overview/#automatic-creation-of-profiles 

I've installed Kubeflow following the v1.3 release: https://github.com/kubeflow/manifests#installation

If I create the user namespace manually, then everything works as expected: 
<img width="873" alt="image" src="https://user-images.githubusercontent.com/26279721/114324942-18606d80-9b25-11eb-8cc3-8590c13348cc.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/26279721/114325138-72156780-9b26-11eb-8c56-360316026acf.png">

However, if I don't create the user namespace manually in advance when I log in with the static user dex credentials automatic profile(namespace) creation doesn't get triggered and Kubeflow just shows 'No namespaces': 

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/26279721/114324968-4ba2fc80-9b25-11eb-9b28-f74f7934141b.png">

Is that the expected behaviour? How can I enable the automatic profile creation functionality? I'd like to have multi-user isolation as mentioned here: https://v0-7.kubeflow.org/docs/other-guides/multi-user-overview/#automatic-creation-of-profiles without having to create a profile manually for each user. 

As far as I understand the easiest way to achieve that would be to add static user credentials to dex for each user, so they can log in and then automatic profile creation is triggered allowing them to create their profile and namespace.

I appreciate your help!

**Comment by DavidSpek** [comment]
@Dimiftb This is because the authentication flow is disabled by default as a security measure. You can find the customization you need to enable this [here](https://github.com/kubeflow-onprem/ArgoFlow/tree/master/kubeflow/notebooks/central-dashboard). I think you might find it easier to deploy and maintain your Kubeflow installation if you use Argo CD for the deployment. The [README](https://github.com/kubeflow-onprem/ArgoFlow/blob/master/README.md) of that repository has detailed instructions for this. It's issue like this and the certificate for the ingress-gateway that I have solved for users in this deployment so they can get started easily.

**Comment by Dimiftb** [comment]
Hi @DavidSpek, 

I'll look into it. Thank you very much. Closing this now.
