### ISSUE TITLE
Publish 1.3 images in gcr

### ISSUE THREAD

**Issue by Adithimurthi** [kubeflow/kubeflow#5851]
Publish 1.3 images in gcr as well like previous releases as companies yet to adapt public ecr.

also, when can we expect 1.3 stable release

**Comment by DavidSpek** [comment]
Sadly, the images will not be pushed to GCR for all of the components. Release 1.3 is now stable. I can recommend [deploying it with Argo CD](https://github.com/argoflow/argoflow) so that you can more easily add your customizations or change the image registry to a personal one. It also allows for easily upgrading each component of Kubeflow rather than needing to wait for a release (which doesn't make much sense given the loose coupling of the components) and prevents configuration drift over time making the deployment easier to maintain.

**Comment by jbottum** [comment]
@Adithimurthi Note if you need a custom configuration i.e. ecr-only, you might also check with one of the vendors that provide supported Kubeflow distributions.    Have you found a solution ?  can we close this issue?

**Comment by Adithimurthi** [comment]
Yes, it should be fine

**Comment by DavidSpek** [comment]
This is also related to https://github.com/kubeflow/kubeflow/issues/5922
