### ISSUE TITLE
Sidebar links with namespace parameters

### ISSUE THREAD

**Issue by toshi-k** [kubeflow/kubeflow#5863]
/kind feature

**Why you need this feature:**
I would like to add own apps on sidebar menu.
Though we can add any items by editting below config map, it is impossible to change links based on namespaces.
https://github.com/kubeflow/kubeflow/blob/v1.3-branch/components/centraldashboard/manifests/base/configmap.yaml

**Describe the solution you'd like:**
Defining the menu as below, the full URL should be https://gateway/myapp1/workspace1/ (when namespace=workspace1) or https://gateway/myapp1/workspace2/ (when namespace=workspace2).
```
        {
          "type": "item",
          "link": "/pipeline/#/artifacts",
          "text": "Artifacts",
          "icon": "editor:bubble-chart"
        },
        {
          "type": "item",
          "link": "/pipeline/#/executions",
          "text": "Executions",
          "icon": "av:play-arrow"
        },
        {
          "type": "item",
          "link": "/myapp1/{namespace}/",
          "text": "MyApp1",
          "icon": "icon"
        },
        {
          "type": "item",
          "link": "/myapp2/{namespace}/",
          "text": "MyApp2",
          "icon": "icon"
        },
```

**Anything else you would like to add:**
Reload the page automatically when the namespace is changed from the top toolbar.

**Comment by DavidSpek** [comment]
@karlschriek I believe this is similar to what you mentioned regarding namespaces MLFlow.

**Comment by toshi-k** [comment]
@DavidSpek That's right. Some applications like ML Flow are not ready for namespaces. I think the easiest way would be deploying such app in each namespace and control traffic by URL.

**Comment by kimwnasptd** [comment]
@toshi-k I'd like to ask some more questions to further understand what's required for MLFlow to work as part of Kubeflow, as well as to see if the current mechanism of the CentralDashboard could satisfy this.

> Some applications like ML Flow are not ready for namespaces. I think the easiest way would be deploying such app in each namespace and control traffic by URL.

So IIUC, the MLFlow components currently don't have a mechanism for K8s Namespace isolation, so the solution you are proposing is to launch the MLFlow components/apps' yamls [Pods, Services, PVCs etc] and a VirtualService to each namespace in order to:
1. expose each app instance, via the VirtualService, for each Namespace
2. ensure the context stored in the MLFlow app's Pod [backed by PVCs?] on each Namespace will only hold the context for that namespace.
 
@toshi-k does my explanation accurately describe what you had in mind?

**Comment by toshi-k** [comment]
That's right. My proposal is creating app for each Namespace (with sidecar injection) and just switching the traffic by URL prefix. This idea is almost the same with traffic control of kubeflow notebook.

This is an instant way to offer customization to cluster admin adding third party apps. MLFlow is just an example and other ML friendly tools (like Grafana, Prometheus etc) can be added with the multi tenancy.

If I understand correctly, current CentralDashboard can't realize this idea. Although the menu link should be like below, the URL can't contain namespace as a path parameter.
https://gateway/myapp1/{namespace}/

**Comment by karlschriek** [comment]
We have been wanting to implement exactly that for quite some time. We
weren't able to do with the previously used Istio version (filtering on
namespace couldn't be implemented without difficulty), but should be fairly
straightforward to implement now. In addition to MLflow server per
namespace one would also need separate backend DB and object storage
configurations. We use S3 and RDS for this, so we just inject an
appropriate IAM role / SQL creds per namespace.

**Comment by kimwnasptd** [comment]
@karlschriek thank you for providing more context!

@toshi-k @karlschriek in that case we can already support running multiple instances of MLflow. In 1.3 the CentralDashboard is injecting the selected Namespace in the links via the `ns={selected-namespace}` query parameter https://github.com/kubeflow/kubeflow/pull/5513.

So, since you will be creating a VirtualService for each MLflow server per namespace, you can use the [queryParams](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest) match rule in each VirtualService. This way the vsvc in a namespace will be accepting traffic only if a request has the `ns={namespace-the-vsvc-is-deployed-in}` query param, which the dashboard already adds in its links.

<details><summary>Example dashboard link</summary>

![Screenshot from 2021-05-24 19-04-09](https://user-images.githubusercontent.com/11134742/119375337-5d9ac200-bcc3-11eb-8128-2a89728d3549.png)

</details>

**Comment by toshi-k** [comment]
@karlschriek Thank you for information ! I gonna take a look about it, but I still need the universal way which can be used for any third party apps.

@kimwnasptd Good point ! I actually tried queryParams at first, but it didn't solve the issue. The biggest issue is when the app is not complete SPA. Thanks to #5513, `ns={namespace-the-vsvc-is-deployed-in}` is added to URL for the first access, but it vanishes when we move to another page in the app. The user can't access the app anymore without  query parameter.

After some trials, I concluded that path parameter is the most stable way to access third party app through kubeflow dashboard. Cluster admin can add any application (for each namespace) by my approach.

**Comment by kimwnasptd** [comment]
> ns={namespace-the-vsvc-is-deployed-in} is added to URL for the first access, but it vanishes when we move to another page in the app. The user can't access the app anymore without query parameter.

Indeed, this can be an issue since each app can change the URL in the iframe, or even not include this query param at all in the requests it makes.

@toshi-k thank you for the detailed explanation! We are on the same page. Indeed having dynamic paths for namespaces seems like a very clean way to have this functionality. I'll go on with reviewing your opened PR https://github.com/kubeflow/kubeflow/pull/5871.

**Comment by jbottum** [comment]
@toshi-k I am a Kubeflow Community Product Manager and interested in this effort.    Do you have some end-users that will deploy this in the near term?

**Comment by DavidSpek** [comment]
@jbottum @jtfogarty said some people at his work were asking about MLFlow. I'll be looking into Grafana integration in the near future for [ArgoFlow](https://github.com/argoflow).

**Comment by toshi-k** [comment]
@jbottum I'll use this feature by myself. I'm a kind of K8S cluster admin, and deploy ML tools for my co-workers (data scientists). They sometimes ask me to add some tools which are not included in original kubeflow. So, I'm trying to integrate external apps with kubeflow.

**Comment by toshi-k** [comment]
Resolved ! #5871

**Comment by nrchakradhar** [comment]
@toshi-k How can we change the links during deployment OR after deployment. Is there something to update in a config-map or somewhere else?

**Comment by toshi-k** [comment]
@nrchakradhar You can change after deployment.
`kubectl edit cm centraldashboard-links-config -n kubeflow`
