### ISSUE TITLE
Tensorboard server connection problems

### ISSUE THREAD

**Issue by zulissi** [kubeflow/kubeflow#5900]
Thanks for the new tensorboard server; it looks really helpful! Two issues I've noticed from using it with kubeflow1.3 (installed through argoflow):

1) The tensorboard service only binds to localhost resulting in "upstream connect error or disconnect/reset before headers. reset reason: connection failure". I think this is because the container spec is missing a `--bind_all` here:
https://github.com/kubeflow/kubeflow/blob/52b724b3221685042415cb927d4c225b28657d17/components/tensorboard-controller/controllers/tensorboard_controller.go#L249

This already exists in kubeflow/pipelines tensorboard server:
https://github.com/kubeflow/pipelines/blob/master/backend/src/crd/controller/viewer/reconciler/reconciler.go#L193

2) The routing of the tensorboard server conflicts with the notebook server routing. Making a tensorboard and notebook server in the UI with the same name, then connecting to the tensorboard server will route to the notebook server and display a 404 from the notebook server.

**Comment by DavidSpek** [comment]
This problem was caused the [kubeflow istio cluster roles](https://github.com/kubeflow/manifests/blob/master/common/istio-1-9-0/kubeflow-istio-resources/base/cluster-roles.yaml) manifest not being deployed. Strangely enough not having this manifest deployed did not result in other obvious errors. Deploying this manifest solved the problem.

/close

**Comment by DavidSpek** [comment]
/reopen

This issue was solved because Istio was fixing the configuration somehow, which it needed the above mentioned roles for. However, with [Istio 1.10 Envoy is configured to send traffic to the application on eth0 rather than lo](https://istio.io/latest/news/releases/1.10.x/announcing-1.10/), which breaks the tensorboard instances.
Running `istioctl experimental precheck` yield the following output:

```bash
Error [IST0143] (Pod gpu-tensorboard-587df6c577-ml7td.kubeflow-user) Port 6006 is exposed in a Service but listens on localhost. It will not be exposed to other pods.
```

Also related: https://github.com/kubeflow/kubeflow/issues/5921


/cc @kubeflow/wg-notebooks-leads

**Comment by kimwnasptd** [comment]
Thanks for reporting the issue @zulissi.

I'd like to ask some questions to ensure we've understood what exactly the problem is.

> The tensorboard service only binds to localhost resulting in "upstream connect error or disconnect/reset before headers. reset reason: connection failure"

As @DavidSpek noted above, in Istio 1.10 the Envoy proxy will **not** forward traffic from the Pod's `eth0`  to `lo` https://istio.io/latest/blog/2021/upcoming-networking-changes. But this assumes that you've upgraded your Istio installation to 1.10, and not 1.9 which is what the manifests for 1.3 provide https://github.com/kubeflow/manifests#istio. Could you verify that this is the case? If not we might need to investigate more.

> The routing of the tensorboard server conflicts with the notebook server routing. Making a tensorboard and notebook server in the UI with the same name, then connecting to the tensorboard server will route to the notebook server and display a 404 from the notebook server.

Could you elaborate a little bit more? The VirtualService of the Tensorboard CR will have a prefix `/tensorboard/<namespace>/<name>/` [[code](https://github.com/kubeflow/kubeflow/blob/52b724b3221685042415cb927d4c225b28657d17/components/tensorboard-controller/controllers/tensorboard_controller.go#L295)] while the Notebook's prefix should be `/notebook/<namespace>/<name>/` [[code](https://github.com/kubeflow/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L405)]. Could you provide me some steps to reproduce your issue?

**Comment by DavidSpek** [comment]
@kimwnasptd The problem with the pod not binding to all interface is also apparent if the [kubeflow istio cluster roles](https://github.com/kubeflow/manifests/blob/master/common/istio-1-9-0/kubeflow-istio-resources/base/cluster-roles.yaml) are not deployed. This is also the only problem I experienced when these were not deployed. So the issue is not strictly speaking only relevant for Istio 1.10.
Could you please take a look at https://github.com/kubeflow/kubeflow/pull/5925, which adds the `--bind_all` flag to the controller, which at least solves this problem for the time being.

**Comment by yanniszark** [comment]
@zulissi the error you are seeing makes sense if you are indeed using Istio 1.10 with new changes in sidecar networking. Do you confirm that you are using Istio 1.10?

@DavidSpek I think we all agree that the changes in Istio 1.10 would break the tensorboard controller. However, I don't understand how this could happen if one had not deployed the Istio cluster roles. Can you provide a step-by-step description of how this happens?

In the Istio 1.10 case, a step-by-step description would be something like this:
1. Tensorboard Pod starts and serves on port X on localhost.
2. User navigates to Tensorboard UI with browser and clicks connect on the specific tensorboard.
3. The Tensorboard Pod's Istio sidecar intercepts the request on port X.
4. Because Istio 1.10 does not proxy exposed ports to localhost anymore, the request fails.

What would be the step-by-step description for the scenario you are describing?

**Comment by zulissi** [comment]
In my case:
* I was using argoflow with istio 1.9 and without the istio cluster roles as @DavidSpek mentioned.
* I had turned off istio for some namespaces since it interfered with some services like dask clusters. I know this isn't the expected use case, but notebook servers still work fine with istio off.
* When this is the case, navigating to /tensorboard/<namespace>/<name>/ would send traffic to a notebook server with the same name, but I now understand this is because istio was off. 
* Enabling istio and implementing the cluster role bindings fixed the problems for me and tensorboards acted as expected.

Notebook servers are expected to bind on all interfaces (eg https://www.kubeflow.org/docs/components/notebooks/custom-notebook/), so it seems reasonable to expect that tensorboard server also binds on all interfaces.  This would also allow things to work if istio happens to be disabled on a namespace.

**Comment by DavidSpek** [comment]
@yanniszark I'm not sure what those cluster roles are used for, but deploying them solved the problem. I don't have the the sidecar logs handy as I've since deployed the cluster roles and am now using Istio 1.10, but I guess the steps could be seen as follows:

1. Tensorboard Pod starts and serves on port X on localhost.
2. User navigates to Tensorboard UI with browser and clicks connect on the specific tensorboard.
3. The connection fails with no healthy upstream. 

This error is also seen when Istio 1.9 is enabled for user namespaces and the cluster roles are not deployed. As @zulissi just mentioned, the tensorboard instance should bind to all interfaces to avoid such problems, just like every web app or notebook server that is deployed from the code in this repository.

**Comment by kimwnasptd** [comment]
Since the `--bind_all` flag is not the root of this issue I created an umbrella one to keep track of that effort there https://github.com/kubeflow/kubeflow/issues/5938. @DavidSpek lets review your PR https://github.com/kubeflow/kubeflow/pull/5925 as part of that issue.
