### ISSUE TITLE
[Discussion] Ksonnet prototypes for other operators

### ISSUE THREAD

**Issue by jose5918** [kubeflow/kubeflow#592]
There should be a way for users of other frameworks to use different operators and install them from the main kubeflow repo.

Would this involve adding an operator to kubeflow core or something in the operator's repo?

@ewilderj @jlewi @carmark

**Comment by jlewi** [comment]
I think we should have a single Kubeflow ksonnet registry; so any new packages should be added inside the kubeflow/kubeflow repository.

There's an open issue #106 to figure out how we should divide things into ksonnet packages.

I suggest defaulting to putting new prototypes in the existing core package. Mainly because this is less work for users because its a single ks command to install that package.

**Comment by jlewi** [comment]
Don't honestly know. I think we'll have to see how things evolve and figure out what make sense.
