### ISSUE TITLE
Update  Istio usage page on Kubeflow.org

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#6018]
This page is out of date, https://www.kubeflow.org/docs/external-add-ons/istio/istio-in-kubeflow/

@kubeflow/wg-notebooks-leads is this page part of centralize services and therefore part of notebooks ?   Could we please have someone help to update this page ?

**Comment by nitishkrishna** [comment]
This page specifically is out of date: https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually
Since it talks about `ServiceRole` and `ServiceRoleBinding` objects which are deprecated with Istio 1.6+ and have been replaced in Kubeflow 1.3 here: https://github.com/kubeflow/kubeflow/commit/40fae6a36e029fdae1aa920ec10ec79f47a9a5cd
