### ISSUE TITLE
Why are there internalization definitions for other apps in each web app?

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6023]
/kind question

**Question:**
I see that after the internalization PR https://github.com/kubeflow/kubeflow/pull/5880 the language json files for each app [Jupyter, Volumes, TensorBoards] include sections for the other web apps and not just for their own.

I.e.
https://github.com/kubeflow/kubeflow/blob/36e8528ebefd4ac7c1e37d9c1fbd36cf35db8943/components/crud-web-apps/jupyter/frontend/src/assets/i18n/en.json#L187
https://github.com/kubeflow/kubeflow/blob/36e8528ebefd4ac7c1e37d9c1fbd36cf35db8943/components/crud-web-apps/tensorboards/frontend/src/assets/i18n/en.json#L2
https://github.com/kubeflow/kubeflow/blob/36e8528ebefd4ac7c1e37d9c1fbd36cf35db8943/components/crud-web-apps/volumes/frontend/src/assets/i18n/en.json#L159

@wg102 @DavidSpek @thesuperzapper what was the rational behind this decision?

**Comment by wg102** [comment]
It was an attempt to keep the common code in sync. Jupyter, Volumes and Tensorboards all have their own text, but they also use the common code. If someone modified Jupyter-common, then Tensorboard and Volume would be 'out of date', even worse if they removed or added a string then there would be not translation.

However, since all three apps use the same common code, and that adding a label in said common code would need to be done to every i18n json file, it might have been wiser to have only one `en.json` and one `fr.json`,  in one location, such as the common  library and when generating the code, it would copy it in each of the apps..
