### ISSUE TITLE
Extend Notebooks Controller to expose idleness for Jupyter

### ISSUE THREAD

**Issue by athamark** [kubeflow/kubeflow#6270]
/kind feature

Hello, @kimwnasptd and I have worked on an iteration of the Notebooks Controller that extends its functionality to expose information about idleness for Jupyter Notebooks.

This information indicates the last time that each Jupyter Notebook Server performed any computations.

This also affects how culling is implemented, since it will now use the idleness information to decide if a Jupyter Notebook should be culled.

I'd like to push this effort as part of the 1.5 release, if there's still time.

**Comment by kimwnasptd** [comment]
@athamark thanks for starting this issue! Since this will be a more advanced feature, for which we could also get more feedback from users, let's create a slightly more formal proposal for this feature.

We've started an effort on having some basic proposals in Manifests https://github.com/kubeflow/manifests/pull/2100. We can follow this approach here as well.

I can help with writing the proposal, to describe the  changes, upgrade instructions etc. It will be easier to evaluate this in a PR rather than providing all this information in a GH issue
