### ISSUE TITLE
centraldashboard: Migrate from Polymer to Angular

### ISSUE THREAD

**Issue by haoxins** [kubeflow/kubeflow#6332]
/kind feature

After the discussion with the maintainers, see #6238 
I think we have reached an agreement that we should migrate from **Polymer** to **Angular**.

So that I create this issue to track the progression.

cc @kimwnasptd

**Comment by thesuperzapper** [comment]
@haoxins do want to contribute this work?

If so, we should do a bit of a design doc for the main parts like:
- UI Mockups 
   - consider how we want to differ from the existing UI
   - for example, we can improve the "collaborators" page a lot
- Config Structure 
    - modularity of sidebar, to make it easier for integrating non-kubeflow apps
    - user-customizable colors/branding
- Overview of Authentication / Authorization    
   - how namespaces are managed, 
   - how auth is propagated to the wrapped/iframed services

**Comment by haoxins** [comment]
> @haoxins do want to contribute this work?

yeah, sure~

**Comment by kimwnasptd** [comment]
This looks awesome! 🎉 

@thesuperzapper has done a great job at exposing current functionality, as well as areas to improve. For the first step I would propose to reduce the requirements and focus the effort on migrating the **existing functionalities** over to the Angular framework.

We can of course discuss future improvements in parallel, like user-customizable colors/branding or improving the collaborators page, but let's not block this effort on them.

A [proposal](https://github.com/kubeflow/kubeflow/tree/master/components/proposals) would be a good first step to help us bootstrap this work. Adding some more context to Mathew's items above with some pointers on things we should expose in the proposal:
* How namespaces are populated in the dropdown https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/api_workgroup.ts https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/public/components/namespace-selector.js
* Make it easier to integrate with non-kubeflow apps https://github.com/kubeflow/kubeflow/pull/5995 https://github.com/kubeflow/kubeflow/pull/5871
* how auth is propagated to the wrapped/iframed services https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/public/library.js

I'm also OK if the first iteration would not include the contributors page, just so that we can start have a base codebase and iterate on. 

@haoxins feel free to also join our biweekly meetings to discuss live questions you might have as well :-)

**Comment by sanjshres** [comment]
@haoxins @kimwnasptd @thesuperzapper Hi i am a react developer, willing to any learn any new things. I would love to contribute, how can i get involved?
