### ISSUE TITLE
[Feature Request] Require a flag to install/include a package that has not passed tests against the version of Kubeflow you are installing

### ISSUE THREAD

**Issue by aronchick** [kubeflow/kubeflow#637]

**Comment by jlewi** [comment]
I'm guessing the intent of this issue is that we will have multiple packages in our ksonnet registry at varying degrees of maturity.

If users want to use components in an "alpha" state we shouldn't prevent them from doing so but we should require them to take some explicit action so that they understand they are using alpha features.

I think this is similar to what K8s does. In GKE for example, users have to explicitly set a flag to enable alpha features when creating their clusters.

One idea would be to have two registries; one for stable components and one for incubating components.
