### ISSUE TITLE
1.5rc1 jupyter GPU support and poddefaults support is broken

### ISSUE THREAD

**Issue by juliusvonkohout** [kubeflow/kubeflow#6382]
/kind bug

@kimwnasptd there are serious regressions with Jupyter (Notebook is the wrong word) in 1.5.rc1

1. By default the number of GPUs is empty instead of  None and the launch button is greyed out. In 1.4 It said "None" and you were able to launch a notebook directly. 
![image](https://user-images.githubusercontent.com/45896133/156181155-0c41c588-f2b7-4b92-8662-157746c141b2.png)

2. Even if you select 1 GPU, you cannot select any vendor
![image](https://user-images.githubusercontent.com/45896133/156181580-364c62cb-005b-4829-9aaa-76a0433825c6.png)

3. You cannot set default configurations, they are all deselected by default
``` 
configurations:
    # List of labels to be selected, these are the labels from PodDefaults
    # value:
    #   - add-gcp-secret
    #   - default-editor
    value: ["access-ml-pipeline"]
    readOnly: false
```
![image](https://user-images.githubusercontent.com/45896133/156181761-578e0230-d7a6-466b-bd62-aad744b7ea7b.png)
4. the notebook controller does crazy things in forbidden namespaces as kube-system
```
2022-03-01T14:08:50.378Z	ERROR	controllers.Notebook	unable to fetch Notebook	{"notebook": "kube-system/istio-cni-node-854fq.16d83d225eab3a57", "error": "Notebook.kubeflow.org \"istio-cni-node-854fq.16d83d225eab3a57\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/kubeflow/kubeflow/components/notebook-controller/controllers.(*NotebookReconciler).Reconcile
	/workspace/notebook-controller/controllers/notebook_controller.go:125
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
2022-03-01T14:08:50.378Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "notebook", "request": "kube-system/istio-cni-node-854fq.16d83d225eab3a57"}
2022-03-01T14:08:50.378Z	ERROR	controllers.Notebook	unable to fetch Notebook	{"notebook": "kube-system/istio-cni-node-854fq.16d83d22686acdbe", "error": "Notebook.kubeflow.org \"istio-cni-node-854fq.16d83d22686acdbe\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/kubeflow/kubeflow/components/notebook-controller/controllers.(*NotebookReconciler).Reconcile
	/workspace/notebook-controller/controllers/notebook_controller.go:125
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:216
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

- Kubeflow version: 1.5rc1

**Comment by kimwnasptd** [comment]
> 1. By default the number of GPUs is empty instead of None and the launch button is greyed out. In 1.4 It said "None" and you were able to launch a notebook directly

> 2. Even if you select 1 GPU, you cannot select any vendor

Hmm, I can't seem to reproduce this. I'm using the rc.1 and the GPU selection is working as expected. I also tried to modify the different parts, like `num` and `vendor` and the default values were picked up normally from the form.

@juliusvonkohout could you share the ConfigMap that is mounted to your app, for the form defaults? It should be `jupyter-web-app-config-<suffix>`

> 3. You cannot set default configurations, they are all deselected by default

I can't reproduce this either, from the manifests of the rc.1.

@juliusvonkohout my best bet right now is that the ConfigMap you are using is malformed. In all the cases I've seen until now where the `LAUNCH` button would remain greyed out, or the form behaved differently, would be because the JS could not correctly parse the ConfigMap.

But let's make sure, and if that's the case I think it's good time to improve the logging of the app to make it more clear that it couldn't parse the ConfigMap.

**Comment by kimwnasptd** [comment]
Regarding the Notebook Controller issue wrt Events, the root cause was this change in my PR https://github.com/kubeflow/kubeflow/commit/9a9cce8482633b425426003a9d9c78aefd6a7513#diff-a436986c5e93996f9035eee6798d064ab8659957e8443eb44b3a4d3db289bde4L686.

### How to reproduce

Delete any K8s Event in any namespace

### Root cause
I mistakenly thought that by removing the `DeleteFunc`, then no [`controller-runtime.Events`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/event) would be transformed into Requests by [EventHandlers](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/handler#EventHandler) and passed to `Reconcile()`. But this is not the case:

https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/
> If you do not register a Predicate method for a particular type, events of that type will not be filtered.

So what happens is:
1. A K8s Event gets deleted, either manually by user or K8s deletes it after the configured time
2. Since there's no `DeleteFunc` the K8s Event will not be filtered, to check if it belongs to a Notebook, so it will be transformed to a Request for the `Reconcile()` function
3. The code path will continue from https://github.com/kubeflow/kubeflow/blob/v1.5.0-rc.1/components/notebook-controller/controllers/notebook_controller.go#L118, since `!apierrs.IsNotFound(getEventErr)` will be `false`
4. The controller will think that this reconciliation request is for a Notebook and try to get the notebook with the Event's name
5. No such Notebook exists, so the controller reports an error

### Solution

Add the `DeleteFunc` back, so that we don't trigger the `Reconcile()` for non-notebook Events.

The above still means that we'll be seeing such error logs, but only when an Event for a Notebook is deleted. Right now we can't do too much about this, since we are using the same queue/controller for both Notebooks and Events.

@juliusvonkohout could you review/test the PR, since you've also bump into this?

**Comment by kimwnasptd** [comment]
@juliusvonkohout regarding the web app's form issue, do you see any logs in the browser's dev tools? You wrote above that you checked for frontend logs, but I just wanted to make sure. For chrome you can check them with `Ctrl + Shift + I`, we care for the `Console` tab.

Also:
1. Are you also using the rc.1 image for the web app as well? 
2. Can you double check that the ConfigMap mounted in the app is the expected one, and not maybe one from an older/different installation?

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout could you review/test the PR, since you've also bump into this?

Can you provide me an image to test? Or am i missing something?

"Solution

Add the DeleteFunc back, so that we don't trigger the Reconcile() for non-notebook Events.

The above still means that we'll be seeing such error logs, but only when an Event for a Notebook is deleted. Right now we can't do too much about this, since we are using the same queue/controller for both Notebooks and Events."

I think that is the right thing to do.

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout regarding the web app's form issue, do you see any logs in the browser's dev tools? You wrote above that you checked for frontend logs, but I just wanted to make sure. For chrome you can check them with `Ctrl + Shift + I`, we care for the `Console` tab.
> 

You are right, there is something wrong 
![image](https://user-images.githubusercontent.com/45896133/156583293-05c71ed5-99ef-457f-832b-a9d83613eac3.png)

> Also:
> 
>     1. Are you also using the rc.1 image for the web app as well?

I am mirroring public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.5.0-rc.1
[jupyter-web-app-deployment.yaml.txt](https://github.com/kubeflow/kubeflow/files/8178508/jupyter-web-app-deployment.yaml.txt)

> 
>     2. Can you double check that the ConfigMap mounted in the app is the expected one, and not maybe one from an older/different installation?

I extracted it directly from the cluster.
