### ISSUE TITLE
Expose istio dashboards

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#644]
We are integrated with istio for TF Serving. #464 
The dashboards should have proper routing (ambassador) setup so it's accessible through ingress.
Dashboards include Grafana, Prometheus, and maybe service graph.
https://istio.io/docs/tasks/telemetry/

**Comment by lluunn** [comment]
I am having problem exposing grafana through our ingress + ambassador.

After added the annotation, the routing seems to work, but I can only see:
{{alert.title}}

![screenshot from 2018-04-17 15-58-28](https://user-images.githubusercontent.com/32310205/38903112-45814be6-4258-11e8-8d7b-910e42de3b68.png)

If I add path /dashboard/db/istio-dashboard, it will get redirected to
https://dev.kubeflow.org/d/1/istio-dashboard? and result in 404.

tried things like rewrite, path_rewrite, can't get it to work.

So I ended up making it a LB type service: http://35.184.78.40:3000/d/1/istio-dashboard?refresh=5s&orgId=1

**Comment by jlewi** [comment]
So ingress should be preferred over type LB.

We need a way to secure the dashboards. So at a minimum it needs to be an ingress with IAP turned on.

What happens if you connect over `kubectl port-forward`?

This is most likely an issue with Grafana not being to work behind a reverse proxy because it can't properly tell that its URL is not rooted at https://dev.kubeflow.org so it ends up computing incorrect paths for any other URLs it needs to set.

If kubectl port-forward works then you should look at chrome developer console and compare with and without the reverse proxy to figure out what URL it ends up using and which one it should be using.

**Comment by lluunn** [comment]
Thank you, found this http://docs.grafana.org/installation/behind_proxy/#examples-with-sub-path-ex-http-foo-bar-com-grafana

**Comment by lluunn** [comment]
https://dev.kubeflow.org/grafana/
https://dev.kubeflow.org/grafana/d/1/istio-dashboard?refresh=5s&orgId=1
Working now.
Will document it in https://github.com/kubeflow/kubeflow/issues/496
