### ISSUE TITLE
How to unit test Python function-based components

### ISSUE THREAD

**Issue by suned** [kubeflow/kubeflow#6642]
/kind question

**Question:**
I'm following the instructions for writing [Python function-based components](https://www.kubeflow.org/docs/components/pipelines/sdk-v2/python-function-components/), but it seems to me that the limitations on function based components (imports must be local, helper functions must be defined inside function) make them very difficult to unit test.

Examples of issues I've run into: 

- many of my components use cloud provider client libraries that I would like to mock/patch during tests using the standard python patterns. This is tricky when the imports are inside a function.
- I often want to test that my component function raises certain exceptions under certain conditions. If the exception type is defined inside the function, the usual patterns are hard to use (`pytest.raises` or `unittest.TestCase.assertRaises`)
- Its often very useful to unit test helper functions in isolation from the main component, but that can't really be done at all

Are there any best practices/guidelines for testing Python function-based components. Should I not use them if I want to write these types of tests?

**Comment by fbraza** [comment]
Hello @suned 

I agree with your point. We face the same issue in my company.
We have a lot of helpers functions defined inside the component functions.

What we are doing now is to have our own library where we will put all the helpers there. This allows us to unit / int test these functions independently. 

Our take on kubeflow is that we should have very light components instead of huge chunk of code with inner functions as helpers.

I do not know if you have room for refactoring or if this approach would fit your use case.

Good luck

Cheers
