### ISSUE TITLE
Document versioning policy

### ISSUE THREAD

**Issue by annajung** [kubeflow/kubeflow#6900]
As part of the CNCF application process, [the versioning policy has been identified](https://github.com/kubeflow/community/issues/594) as one of the required documents to support the transition. After reviewing the current documentation for the Notebook WG, it's been recognized that documentation around the versioning and release process needs to be created.

As part of the transition effort, a [high-level versioning process](https://github.com/kubeflow/community/pull/597) has been documented. However, it would also be helpful to document the WG-specific process in this repo for Notebook users similar to other WGs (ex. [Katib release process](https://github.com/kubeflow/katib/tree/master/docs/release#release-process))

**Comment by kimwnasptd** [comment]
Thanks for creating this issue! For Notebooks WG we've been following the [Kubeflow release versioning](https://github.com/kubeflow/community/blob/master/releases/handbook.md#release-candidate-rc), since the code is in the `kubeflow/kubeflow` repo and we didn't want to complicate things with weird branch names and tags.

A file to describe this and add pointers to the release handbook would be OK IMO for now
