### ISSUE TITLE
create a list of Notebook features in Kubeflow 1.7

### ISSUE THREAD

**Issue by jbottum** [kubeflow/kubeflow#6932]
/kind feature

**Why you need this feature:**
We need a list of features in 1.7 for the blog post and powerpoint presentation

**Describe the solution you'd like:**
The Notebook WG Team will provide a list of features and highlight breaking changes and top features.

@kimwnasptd

**Comment by kimwnasptd** [comment]
As I mentioned in the release team meeting one of the themes that we targeted with @orfeas-k and @elenzio9 was to work on how we expose information in the web apps. In KF 1.7 users will get:
1. Sorting/filtering support in all the main tables of the apps
2. Details pages for each notebook and volume
    * Users will also be able to navigate from one detail page to the other, by clicking object links (i.e. clicking on a mounted volume of a notebook will take you to the details page of that volume)
    * There will be logs, events, yaml info for each of these objects

Next steps for this effort will be to start working on allowing users to edit the objects themselves, now that we have such pages https://github.com/kubeflow/kubeflow/issues/6707#issuecomment-1342591206.

**Comment by kimwnasptd** [comment]
We also put a lot of effort with @apo-ger in this release to rework the GH Actions.

Now we are at the point where the actions:
1. Build the images in each PR, of the affected components
2. Deploy the manifests of the components
3. Use the images that we just built in the deployed manifests

This means that in this release we are always testing that images can be deployed in each PR. Next steps here are to actually have more powerful integration tests, that will be using the deployed images. This is good because we are getting very close to testing in an environment similar to the final deployed stack

**Comment by kimwnasptd** [comment]
Then another great effort in this release was from @surajkota where he put cycles and extended the whole TensorBoard stack we have, both the CRD and the web app, to allow use of PodDefaults (links above).

This will help us re-use the same mechanisms throughout the PodDefaults mechanism across the stack. And PodDefaults themselves got a boost in this release by supporting more use-cases (links above)

**Comment by kimwnasptd** [comment]
Lastly, I think we should definitely highlight the effort for ppc64le support that @lehrig organized in https://github.com/kubeflow/kubeflow/issues/6684

It's really great to see efforts that will help Kubeflow getting more adoption in other platforms!

**Comment by lehrig** [comment]
> Lastly, I think we should definitely highlight the effort for ppc64le support that @lehrig organized in #6684
> 
> It's really great to see efforts that will help Kubeflow getting more adoption in other platforms!

Maybe something like this?

Enabled multi-arch builds for main Kubeflow components and KServe, adding ppc64le as supported processor architecture. See Phase 1 of #6684.
