### ISSUE TITLE
Support dynamic logout URLs in CentralDashboard

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/kubeflow#6940]
/kind bug

We just merged for KF 1.7 RC0 the update on AuthService https://github.com/kubeflow/manifests/pull/2150. But in this commit the logout URL is `/authservice/logout`, instead of `/logout`. But since we can't hardcode this value, since not everyone might be using AuthService, we'll need to have a dynamic mechanism for learning this URL.

I'd propose to
1. have a new ENV Var `LOGOUT_URL` in the Deployment of the app
2. The backend will add this for the `/api/workgroup/env-info` route handler https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/app/api_workgroup.ts
3. The frontend will dynamically use this value from the backend

This way users can configure the app based on the authentication service that they use in a dynamic way

**Comment by kimwnasptd** [comment]
There's already an in-flight PR that tries to fix the logout behaviour https://github.com/kubeflow/kubeflow/pull/6609

We can try to fix the issue in that or create a separate one. This fix is something we'd like to track for the KF 1.7 release cc @DomFleischmann

**Comment by DomFleischmann** [comment]
Thank you for the heads up @kimwnasptd , yes I believe this is something we want to get fixed for this release.

**Comment by orfeas-k** [comment]
I sent the PR for this [here](https://github.com/kubeflow/kubeflow/pull/6945). 

For documentation, I followed [this](https://polymer-library.polymer-project.org/3.0/docs/devguide/data-binding) as a guideline in order to bind data between Polymer components. In Polymer, in order to bind values to a property of a child element, one has to use `dash-case` syntax instead of camel case (which is how what is being used to create the property). On top of that, in order to use a property as a DOM element's attribute, the syntax is this 
```
attribute$={{element-property}}
```

**Comment by ajinkya933** [comment]
your PR routes me to `localhost:8888/authservice/site/after_logout` with a blank page as a response. Is there a way by which I can hardcode a website for example: google.com to route to after logout button is clicked (provided the logout clears all cache)
