### ISSUE TITLE
Rename "Notebook" to "Workbench"

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/kubeflow#6981]
[Rename Notebooks to Workbenches]

In Kubeflow, we use "Notebook" to refer to generic web-based development environments. Out of the box, a user can create instances of JupyterLab, VSCode, and RStudio, possibly adding custom IDEs.

"Notebooks" is a term used since the beginning of the Kubeflow project since, at first, there was support just for Jupyter Notebooks, which then evolved into JupyterLab and more IDEs.

With the word "Notebooks" we interchangeably refer to:

1. A JupyterLab instance, but often VSCode and RStudio instances. We call them "Notebooks" because that's what the "Jupyter Web App" manages.
2. A notebook file within a JupyterLab instance

We propose using the term "Workbench" to refer to a generic web-based development environment and break free from any confusion in the notebook terminology. Workbench is already used in some projects to refer to a working/development environment. It is a generic enough term for web applications that exposes a programming/CLI interface.

To transition to this new terminology, we would need to scope two main (independent) threads of work:

1. UI and documentation: update the web app UIs to refer uniformly to Workbenches instead of Notebooks and the Kubeflow docs.
2. Technical discussion: Controllers and CRDs, web app changes, renames, factoring out of common code

cc @kimwnasptd @kubeflow/wg-notebooks-leads

**Comment by thesuperzapper** [comment]
@tzstoyanov @kimwnasptd @StefanoFioravanzo I think if we are going to make any breaking changes to the CRD, we should explore other ways to make the Notebook CRD more powerful instead of just a simple rename.

I have made a proposal in https://github.com/kubeflow/kubeflow/issues/7156, for what I am calling "Kubeflow Notebooks 2.0" (aka "Kubeflow Workspaces").

**Comment by juliusvonkohout** [comment]
> @tzstoyanov @kimwnasptd @StefanoFioravanzo I think if we are going to make any breaking changes to the CRD, we should explore other ways to make the Notebook CRD more powerful instead of just a simple rename.
> 
> I have made a proposal in #7156, for what I am calling "Kubeflow Notebooks 2.0" (aka "Kubeflow Workspaces").

That will be something for a second PR after the cosmetic changes here.

**Comment by thesuperzapper** [comment]
I __strongly believe__ that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.

**Comment by thesuperzapper** [comment]
@juliusvonkohout @tzstoyanov I __strongly believe__ that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout @tzstoyanov I __strongly believe__ that we should NOT do a rename unless there is a technical change, as that would just be confusing to users who already know about "Kubeflow Notebooks", which is effectively a brand at this point rather than a description.

We discussed this for almost one year in the meetings ;-) it was planned for 1.6 already. We even had community polls regarding the name.

The name is really just technically wrong and should not manifest as a brand. The longer it stays the longer it will be wrong. 

Let us rather focus on what you want to achieve on the technical level afterwards.

**Comment by thesuperzapper** [comment]
@juliusvonkohout @kimwnasptd, I understand the frustration that the name is not perfectly descriptive, but I am also aware that "Kubeflow Notebooks" has been the name for the last 4 years, and changing it will throw away all the brand recognition we have built (for example, [it's even on the Wikipedia](https://en.wikipedia.org/wiki/Kubeflow#Kubeflow_Notebooks_for_model_development)).

To be clear, I am not against a rebrand, it's just that this is not the right time.
I would like to propose the following:

1. We wait until after the CNCF donation is complete, to allow for that news to propagate first, and also allow us to use the CNCF to publicize the rebrand separately from the adoption.
2. We only rebrand when there is actually a behavior/technical change, this will allow us to use that hype to spread the news.

If there is strong disagreement with the above, I believe this is a situation where we must invoke the mediation of the interim steering committee (and after the CNCF adoption, the CNCF TOC), because I will not allow this change to go ahead at the current time, it would be significantly damaging to the health of the project.

**Comment by juliusvonkohout** [comment]
@thesuperzapper then please join the next wg meeting to discuss this extensively.

**Comment by thesuperzapper** [comment]
@juliusvonkohout I am happy to discuss this more at that meeting (assuming you are talking about the meeting on the 3rd of Aug at 8am PT).

_PS: I usually can't make that time, but I will reorganize for that one._

**Comment by juliusvonkohout** [comment]
@thesuperzapper yes, @tzstoyanov and or myself will try to attend this as well. Kimonas should be there anyway.

**Comment by thesuperzapper** [comment]
@juliusvonkohout At that meeting, we can also discuss my proposal for a V2 version of Kubeflow Notebooks: https://github.com/kubeflow/kubeflow/issues/7156

I have had a lot of positive feedback when floating the design proposed in that issue with Notebooks users.

**Comment by andreyvelich** [comment]
We can continue this discussion in the Kubeflow Notebooks 2.0 tracking issue.
