### ISSUE TITLE
"Your role" for "All namespaces" is displayed as "Contributor"

### ISSUE THREAD

**Issue by utsumi-fj** [kubeflow/kubeflow#7188]
/kind bug

**What steps did you take and what happened:**

In the `Manage Contributors` screen, `Your role` for `All namespaces` is displayed as `Contributor` by default.

![manage_contributors](https://github.com/kubeflow/kubeflow/assets/81412151/ad199141-690d-4da6-af95-6f2c34f9b9f6)

**What did you expect to happen:**

The row `All namespaces        Contributor` is not displayed.

**Anything else you would like to add:**

I installed Kubeflow 1.7.0 by [official manifests v1.7.0](https://github.com/kubeflow/manifests/tree/v1.7.0), and detected this issue.
In the Kubeflow 1.6.1 installed by [official manifests v1.6.1](https://github.com/kubeflow/manifests/tree/v1.6.1), this issue was not detected i.e. the row `All namespaces        Contributor` is not displayed in the `Manage Contributors` screen in 1.6.1.

**Environment:**

- Kubeflow version: 1.7.0
- kfctl version: not installed
- Kubernetes platform: Vanilla Kubernetes
- Kubernetes version: 1.24
- OS: Ubuntu 20.04

**Comment by kimwnasptd** [comment]
This should only be a visual bug, since the `All namespace` value is only added to the dropdown (and looks like it's copied here) only in the frontend side.

So it should be only a matter of not parsing and showing `All namespace` value in that page
https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/public/components/manage-users-view.js#L55-L69

/good-first-issue

**Comment by UdBe** [comment]
Hello @kimwnasptd. I would like to work on this issue.

**Comment by Aman123lug** [comment]
Hello, @kimwnasptd
this issue is still open?
I want to work on this.

**Comment by juliusvonkohout** [comment]
@david-thrower

**Comment by juliusvonkohout** [comment]
@utsumi-fj has a ready to merge PR here https://github.com/kubeflow/kubeflow/pull/7242
