### ISSUE TITLE
cannot load dashboard menu link

### ISSUE THREAD

**Issue by LLsmile** [kubeflow/kubeflow#7222]
Recently, the website interface of kubeflow has changed and report error like this:

![Screenshot from 2023-07-26 16-43-14](https://github.com/kubeflow/kubeflow/assets/18437178/1ab0d25e-7502-4f65-894b-65d33834197e)

I don't know what happened and how to solve it.

**Comment by diankasileymane** [comment]
Hi, I am having the same problem. 
![image](https://github.com/kubeflow/kubeflow/assets/140721656/8917e1eb-37c3-4356-bfe7-9f6e216fc25a)

I installed kubeflow  using the manifests with the latest release: 1.7.0

the logs of pod of the centraldashboard
`Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch Nodes Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch Application information: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
`   
I have followed the solution  from this issue https://github.com/kubeflow/manifests/issues/2171  but it did not work for me

Did you manage to solve the problem ?

**Comment by ReggieCarey** [comment]
Is your kubeproxy running correctly on the node hosting the dashboard? Logs look like a failure to get the configmap due to connectivity failures with 127.0.0.1:8080 likely the proxy to the K8s api server. Sent from my iPhoneOn Jul 27, 2023, at 09:35, diankasileymane ***@***.***> wrote:﻿
Hi, I am having the same problem.

I installed kubeflow  using the manifests with the latest release: 1.7.0
the logs of pod of the centraldashboard
Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch Nodes Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch Application information: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch Events for kubeflow-user-example-com: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } Unable to fetch ConfigMap: Error: connect ECONNREFUSED 127.0.0.1:8080 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) { errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 8080 } 
I have followed the solution  from this issue kubeflow/manifests#2171  but it did not work for me
Did you manage to solve the problem ?

**Comment by juliusvonkohout** [comment]
/close

please reopen if this still occurs in Kubeflow 1.9.1 from kubeflow/manifests
