### ISSUE TITLE
Kubeflow j1r0q0g6/notebooks ECR repo is missing 

### ISSUE THREAD

**Issue by sethgustafson** [kubeflow/kubeflow#7293]
/kind bug

**What steps did you take and what happened:**
We noticed that a portion of our Kubeflow cluster deployments were failed with an image pull backoff error. After investigating, we discovered that the official ECR repo (https://gallery.ecr.aws/j1r0q0g6/notebooks/) listed in the Kubeflow docs (https://www.kubeflow.org/docs/components/notebooks/container-images/) has been removed. 

![image](https://github.com/kubeflow/kubeflow/assets/107066183/f52cff14-4772-4926-ac27-13875765199b)

**What did you expect to happen:**
The image and ECR repo to be available

**Anything else you would like to add:**
Affected images:
admission-webhook
centraldashboard
jupyter-web-app
notebook-controller
profiles-deployment access-management
profiles-deployment profile-controller
tensorboards-web-app
training-operator

**Comment by liurong79** [comment]
This is holding up our deployment too. Would really appreciate it if we could bump this up the priority list!

**Comment by clownchrys** [comment]
Same issue occurs for me

**Comment by andreyvelich** [comment]
Thank you for creating this @sethgustafson.
@kubeflow/aws Please can you comment on this issue ?
As @surajkota mentioned here: https://github.com/kubeflow/testing/issues/1008#issuecomment-1196143000, AWS was planning to maintain these images to not break existing Kubeflow deployments that were using public ECR registry.

cc @kubeflow/wg-training-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-manifests-leads @jbottum

/priority p0

**Comment by cristianTeknoir** [comment]
Seems like they moved to docker.io/kubeflownotebookswg/

**Comment by thesuperzapper** [comment]
@surajkota do you know what happened on the AWS side, I thought the old ECR registry was meant to stay up?

---

Also for others needing a solution, Kubeflow 1.7 should not be using the ECR image registry anymore, so if you upgrade to that, you won't have this problem.

**Comment by surajkota** [comment]
We are looking into it. Some clarification, AWS does not own or maintain the account, we intentionally moved away from that model to accounts owned by community last year (https://github.com/kubeflow/testing/issues/1006#issuecomment-1153299757). Action items to renew credits this year was never done

@kimwnasptd and @johnugeorge also have access to the [management root account](https://github.com/kubeflow/testing/issues/1006#issuecomment-1170478429)

**Comment by ryansteakley** [comment]
Last Year in July the AWS account([kf.testing.aws@gmail.com](mailto:kf.testing.aws@gmail.com) AWS account-id 916080701582) was provided with 12 months of credits with $50,000, this credit was expired on 7/31/2023. The AWS account was suspended because of past due charges. There are about $30 per month of charges since July 2023. In the original post/proposal this account is owned/shared by the open-source community. Their was an expectation that the community would take necessary actions to be aware of credit usage etc and to monitor this, as described by Suraj here https://github.com/kubeflow/testing/issues/1006#issuecomment-1153299757. Today we got approval from AWS OSS program to renew the credit for 1 more year with $1500, the credit should be available on 9/28/2023. We don’t know if this credit will be applied to the past due charges($61.10), we will monitor this account tomorrow and update here.

Last year Kubeflow OSS community used only $264 out of $50,000 credits. Based on last 2 months of the usage, we believe $1500 credit should be good enough to keep ECR images for 1 more year. We believe Kubeflow OSS community has already migrated these images to the the newer public/[docker.io](http://docker.io/) for the latest versions(Kubeflow =>v1.7 version). We request Kubeflow OSS community to deprecate this ECR repository AAP so that we don’t have to renew 1 more year.

The account has a credit card provided by Arrikto as a payment method, we don’t know why the payment did not go through that card as a backup. Can someone from Arrikto look into this if the payment is declined for some reason?

**Comment by ryansteakley** [comment]
Update 9/28/2023: The account 916080701582 is suspended, so AWS OSS program team couldn’t issue credits($1500) to this account. Please note that the credit can’t cover its previous bill. We are working with AWS billing team to reactivate the account and get a one time exception to waive off the past due charges. We will monitor the ticket and post update here tomorrow. 

In case AWS billing cannot waive these charges, we will ask them to use the linked credit card to cover the past due charges($61.10) to re-activate the account. Once the account is activated AWS will credit($1500).

The account has a credit card provided by Arrikto as a payment method, we don’t know why the payment did not go through that card as a backup. Can someone from Arrikto look into this if the payment is declined for some reason?

**Comment by thesuperzapper** [comment]
@ryansteakley I think Arrikto no longer exists as a company, so I am not sure if that credit card will work, we might need to find another one, if that is a requirement.

**Comment by surajkota** [comment]
We were able to get the account temporarily activated but but have run into other issues because of account suspension. The ECR registry was inactivated due to account suspension and we are actively working with ECR team to restore it. This is taking longer than expected.

Thanks for your patience in the meantime.

**Comment by ryansteakley** [comment]
We have added budget reports to the account, and have provided @jbottum as the email that will receive messages if spending goes over $30 per month. The customer support team is now working on waiving the past-due charges.

**Comment by ryansteakley** [comment]
The repositories have been restored and should all now be available again https://gallery.ecr.aws/j1r0q0g6

**Comment by ryansteakley** [comment]
The credits will last 12 months, the Kubeflow Community before then will need to come up with a deprecation plan for this repository. To prevent this issue from reocurring in the future. @jbottum  @kimwnasptd  @thesuperzapper

**Comment by andreyvelich** [comment]
This should be resolved.
