### ISSUE TITLE
Deletion of a user

### ISSUE THREAD

**Issue by ralfluebben** [kubeflow/kubeflow#7297]
/kind question

Is there a default way to delete users from kubeflow?

I want to delete a user, e.g. user1:

I tried 
```
kubectl delete all -n user1
kubectl delete ns user1
```
but pods are destroyed and restarted, also the namespace remains.

I also tried 
```
kubectl delete profile ksa.user1.default
```
Which returns
```
Error from server: operation Delete is not supported on Profile(ksa.user1.default)
```

Thanks
Ralf

**Comment by hsayniaj79** [comment]
I had the same issue because the documentation for this is out of date. The resource name you are looking for is not "profiles" but instead is "profiles.kubeflow.org".

You can see all user profiles with:
`kubectl get profiles.kubeflow.org`

You can delete user1 with:
`kubectl delete profiles.kubeflow.org user1`

If you also wish the residual namespace, then you can do so with (assuming namespace is caled user1 as well):
`kubectl delete ns user1`

**Comment by juliusvonkohout** [comment]
/close

The namespace should be automatically deleted because it is owned by the profile
