### ISSUE TITLE
E2E test for Argo Package

### ISSUE THREAD

**Issue by jlewi** [kubeflow/kubeflow#740]
Related to #21.

We need an E2E test. An E2E test should verify

- We can deploy the CRD
- We can submit a simple workflow that does hello world.

**Comment by ankushagarwal** [comment]
Our current GKE e2e test uses the test cluster to test things out. I tried running the argo e2e test there but it broke things because it conflicted with the existing argo deployment on the test cluster. 

We should use a new cluster to run our e2e GKE tests - this will ensure that changes due to individual tests don't affect the test cluster.
