### ISSUE TITLE
Multi-Cluster setup

### ISSUE THREAD

**Issue by Rohithzr** [kubeflow/kubeflow#7493]
/kind question

**Scenario**
I have 3 Cloud providers, GCP, Azure and AWS with managed K8s clusters on each and I am looking only for Kubeflow Pipelines and maybe Knative Serving for my use case. I have a shared NFS on all 3 clouds and shared S3 Bucket.

**Goal**
Having a multi-cloud setup where I can process my pipelines/requests on a cluster where GPU nodes are available.

**Question:**
1. If I ask all 3 Kubeflows to connect to the same MySQL database, will that cause conflicts?
2. Is there any documented experiment to achieve the goal mentioned?
3. Is there a functionality to connect multiple kubeflows with each other, so they act as one?

**Comment by rimolive** [comment]
1. Probably, and with a shared NFS this will break your installation
2. I don't believe there is a public document or an attempt to achieve this
3. What's exactly the problem? I doubt there is a feature for that, but we need to understand the problem to propose the best solution to satisfy your needs

**Comment by Rohithzr** [comment]
@rimolive thanks for the response.

I have a scenario where I want to have a Kubeflow across multiple clusters on different providers, it's an architectural problem that I am maturing.

I will close this ticket for now.

**Comment by luis-mfc** [comment]
Hey, i had a similar scenario in the past.
Have since created a [repo](https://github.com/luis-mfc/multi-cluster-kubeflow) with a proof-of-concept deployment of Kubeflow in multiple clusters that may be useful. It looks possible but, since Kubeflow was not designed for multiple clusters as far as i know, i would expect an approach like that to have problems (also not sure if admiralty is production ready tbh).
