### ISSUE TITLE
when create  profile,it need to pull image from internet,i need to switch it  private registry

### ISSUE THREAD

**Issue by lordebj** [kubeflow/kubeflow#7550]
when create profile,it need to pull image from internet,i need to switch it  private registry

**Comment by lordebj** [comment]
i create a profile, which designates user and namespace
it create namespace and create two deploy in the namespace 
ml-pipeline-ui-artifact
ml-pipeline-visualizationserver
this two deploy create pod pulling image from internet
the image is gcr.io/ml-pipeline/frontend:2.0.3
how can switch it to my private registry without patch the deploy but by changing the profile controller

**Comment by lordebj** [comment]
there is a same case  when i new a notebook in the central dashboard.
is there a another way just not to patch the deploy but the environment.

**Comment by thesuperzapper** [comment]
@lordebj Using a private container registry (or air-gapped cluster) is very complex with upstream Kubeflow.

Since this is a very specialized use-case we are unlikely to ever support it officially.

However, you can achieve this with deployKF, please see this guide for more info:

- https://www.deploykf.org/guides/platform/offline/
