### ISSUE TITLE
Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io":       failed to call webhook: Post "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp 10.96.44.217:443: connect: connection refused

### ISSUE THREAD

**Issue by ALPHA-1503** [kubeflow/kubeflow#7562]
/kind bug

Hey everyone,

I'm currently in the process of installing Kubeflow on Tanzu Kubernetes Grid, but I've hit a roadblock with the knative-serving and knative-eventing deployments. The pods aren't initializing due to the following error:

"Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: Post "[https://istiod.istio-system.svc:443/inject?timeout=10s](https://istiod.istio-system.svc/inject?timeout=10s)": dial tcp 10.96.44.217:443: connect: connection refused"

As I'm relatively new to Kubernetes technology, I apologize if I might not grasp all the intricacies of this issue.

![image](https://github.com/kubeflow/kubeflow/assets/130001527/800aa3c0-b15a-469a-bb07-e9dc7759ca75)
![image](https://github.com/kubeflow/kubeflow/assets/130001527/c27cd3c2-aeb8-4c7d-87d1-559bbb048623)
![image](https://github.com/kubeflow/kubeflow/assets/130001527/1561bff3-6036-47bc-834a-6d732e591d35)

- Kubeflow version: 1.8
- Kubernetes platform: Tanzu Kurbenetes VMware
- Kubernetes version: v1.26.4+vmware.wcp.0
- Ubuntu (for gpu compatibility)

**Comment by AndersBennedsgaard** [comment]
This would suggest an issue with Istio, and not Kubeflow, but let's break down the error log:

`Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io"` suggests that Kubernetes has failed calling the Istio sidecar injector service.

The next line explains that connection refused to the Kubernetes Service `istiod` in the `istio-system` namespace on port 443 because of a connection refused:
`failed to call webhook: Post "[https://istiod.istio-system.svc:443/inject?timeout=10s](https://istiod.istio-system.svc/inject?timeout=10s)": dial tcp 10.96.44.217:443: connect: connection refused`

Often times `connection refused` means that pods aren't ready to receive traffic at this time. So check if the Istio pods are up and ready.
If it continues failing, you might want to get help from https://github.com/istio/istio/issues

**Comment by juliusvonkohout** [comment]
Istio is maintained in Kubeflow/manifests 

From https://github.com/kubeflow/manifests
You can join the CNCF Slack and access our meetings at the [Kubeflow Community](https://www.kubeflow.org/docs/about/community/) website. Our channel on the CNCF Slack is here [#kubeflow-platform](https://app.slack.com/client/T08PSQ7BQ/C073W572LA2). You can also find there our [biweekly meetings](https://bit.ly/kf-wg-manifests-meet), including the commentable [Agenda](https://bit.ly/kf-wg-manifests-notes).

/close
