### ISSUE TITLE
Support install kubeflow by Deployment Manager

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/kubeflow#757]
To provide better user experience on GCP,
we should provide installing kubeflow through Deployment Manager.
Installation should be as simple as:
1. Insert into templates info like email...
2. gcloud deployment-manager deployments create XXX (preprare all resources, including a dev pod)
3. (should we automate this step?) Enter dev pod and "apply kubeflow components".

**Comment by inc0** [comment]
Can you leverage our statefulset for that? bootstrap/examples/kubeflow-toolbox.yaml

**Comment by jlewi** [comment]
We want to use deployment manager to setup non K8s resources; e.g. GKE, static ips, buckets, service accounts etc...

The goal is to provide declarative configs that make it easy to get started with Kubeflow on GCP.

We'd like this infrastructure to connect with the bootstrapper e.g. by launching the stateful set to run the bootstrapper to initialize the app.

**Comment by jlewi** [comment]
Here's an [example](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/examples/v2/gke/daemonsets)  of using Deployment Manager to create a daemonset. I suspect a similar approach could be used to

 * Create the namespace
*  Create the clusterrolebinding
 * Create the statefulset for the bootstrapper

**Comment by kkasravi** [comment]
@jlewi this has similarities with the bootstrapper modifications [proposal](https://github.com/kubeflow/community/pull/124) (i'm addressing your comments under there separately). 

Would using the deployment manager couple kubeflow to GCP or would there be other deployment managers for other cloud-providers?

Having an initial infrastructure to create resources required for the bootstrapper to run is what I was suggesting in the proposal but using a CRD and 2 controllers with different RBACs. The idea was to enable self-serve for data scientists so they are able deploy kubeflow w/o requiring cluster level RBACs, rather they could have rolebindings specific to the namespace. 

I think this does the same thing by using the deployment manager API rather than a CRD.

**Comment by jlewi** [comment]
No this would not couple Kubeflow to GCP. We will never do that.

The goal here is to provide recommendations about how to setup Kubeflow on GCP (#240 and #241). As part of that, we want to recommend using deployment manager mostly to setup non GCP resources (e.g. DNS, buckets, IAM roles, secrets etc...). The reason I'm advocating for using deployment manager (as opposed to say a shell script for running gcloud), is because I want to follow the K8s pattern of managing infrastructure declaratively.

The intent here is that each Cloud Provider or K8s distribution should provide best practices/recommendations for their platform (issue #240).

**Comment by jlewi** [comment]
For comparison, at Kubecon @sfabel of Canonical demo'd using Juju to provision resources and then deploy Kubeflow.

**Comment by jlewi** [comment]
We can close this once #875 is committed.
