### ISSUE TITLE
Verify Central UI is working

### ISSUE THREAD

**Issue by lluunn** [kubeflow/kubeflow#805]

**Comment by jlewi** [comment]
/assign @jlewi

I tested it out and there are a couple issues

#808 - There is a strange box that says "nothing to display here"
There is no link to JupyterHub

The central UI doesn't work with IAP because the proxy before Ambassador is mapping "/" to JupyterHub. 

Will open individual issues for these issues.

**Comment by jlewi** [comment]
Lets leave this issue open until all the fixes are submitted and verified.

**Comment by jlewi** [comment]
#810 add link to JupyterHub.

**Comment by jlewi** [comment]
I tested it out and the central box is fixed

But there is a problem #957 with the central UI not rendering if the screen is too small.

**Comment by jlewi** [comment]
All the bugs appear to be fixed. 
Need to build an image from head and then update the core component to pin the image.

**Comment by jlewi** [comment]
HEAD is updated. Waiting on the next RC to verify this.

**Comment by swiftdiaries** [comment]
Awesome 🙌

**Comment by jlewi** [comment]
I verified this using configs @ HEAD which are using image
 gcr.io/kubeflow-images-public/centraldashboard:v20180618-v0.2.0-rc.0-5-g715aafc8-e3b0c4

Marking this as fixed.
